import { createDiagnostic,type IndicatorOutputDefinition,type MarketField,type TimeSeriesIndicatorDefinition } from '../../contracts';
import { defineCategoryIndicator,type CategoryIndicatorSpec } from '../shared/category-definition';
import * as indicatorLogic from './logic';
import { category,event,integer,number,pane,string,type Params,type Rules } from './shared';
interface Input{backlogId:string;id:string;name:string;ar:string;description:string;defaults:Params;rules:Rules;outputs:readonly IndicatorOutputDefinition[];minimumHistory:number;requiredFields:readonly MarketField[];requiredSymbol?:string;unavailableCapability?:string;requiredRole?:string;compute:CategoryIndicatorSpec<Params>['compute'];}
function define(input:Input):TimeSeriesIndicatorDefinition<Params>{return defineCategoryIndicator({backlogId:input.backlogId,id:input.id,category:"relative-intermarket",name:input.name,description:{en:input.description,ar:input.ar},requiredFields:input.requiredFields,requiredCapabilities:input.requiredRole?['numeric-series']:[],defaults:input.defaults,parameterRules:input.rules,outputs:input.outputs,minimumHistory:input.minimumHistory,tags:["relative-intermarket",'data-bound'],references:['Ticknal canonical indicator program'],availability:(frame,_parameters,inputs)=>input.requiredRole&&inputs.seriesByRole[input.requiredRole]===undefined?createDiagnostic('DATA_CAPABILITY_MISSING','indicator.data.requiredRoleMissing',{role:input.requiredRole}):input.unavailableCapability?createDiagnostic('DATA_FIELD_MISSING','indicator.data.capabilityUnavailable',{capability:input.unavailableCapability}):input.requiredSymbol&&!frame.meta.symbol.toUpperCase().includes(input.requiredSymbol)?createDiagnostic('DATA_FIELD_MISSING','indicator.data.capabilityUnavailable',{capability:'selected '+input.requiredSymbol+' index series'}):null,compute:input.compute});}
export const RELATIVE_INTERMARKET_DEFINITIONS:readonly TimeSeriesIndicatorDefinition<object>[]=Object.freeze([
  define({backlogId:"REL-001",id:"relative-price-ratio",name:"Price Ratio",ar:"مؤشر Price Ratio",description:"One asset divided by another to show relative performance.",defaults:{comparisonSymbol:'COMPARISON'},rules:{comparisonSymbol:string()},outputs:[pane("ratio","ratio","dimensionless"),pane("normalized-ratio","normalized ratio","dimensionless")],minimumHistory:1,requiredFields:["close"],requiredRole:'comparison',compute:indicatorLogic.relativePriceRatio}),
  define({backlogId:"REL-002",id:"relative-relative-strength-versus-benchmark",name:"Relative Strength versus Benchmark",ar:"مؤشر Relative Strength versus Benchmark",description:"Asset return minus benchmark return.",defaults:{period:20,benchmarkSymbol:'EGX30'},rules:{period:integer(),benchmarkSymbol:string()},outputs:[pane("relative-return","relative_return","percent"),pane("period","period","dimensionless"),pane("benchmark","benchmark","percent")],minimumHistory:21,requiredFields:["close"],requiredRole:'benchmark',compute:indicatorLogic.relativeRelativeStrengthVersusBenchmark}),
  define({backlogId:"REL-003",id:"relative-relative-strength-line",name:"Relative Strength Line",ar:"مؤشر Relative Strength Line",description:"Cumulative asset-to-benchmark ratio.",defaults:{benchmarkSymbol:'EGX30'},rules:{benchmarkSymbol:string()},outputs:[pane("rs-line","RS line","dimensionless"),event("new-high-event","new high event")],minimumHistory:1,requiredFields:["close"],requiredRole:'benchmark',compute:indicatorLogic.relativeRelativeStrengthLine}),
  define({backlogId:"REL-004",id:"relative-relative-strength-momentum",name:"Relative Strength Momentum",ar:"مؤشر Relative Strength Momentum",description:"Rate of change of the relative-strength line.",defaults:{period:20,benchmarkSymbol:'EGX30'},rules:{period:integer(),benchmarkSymbol:string()},outputs:[pane("rs-momentum","RS momentum","percent"),pane("period","period","dimensionless")],minimumHistory:21,requiredFields:["close"],requiredRole:'benchmark',compute:indicatorLogic.relativeRelativeStrengthMomentum}),
  define({backlogId:"REL-005",id:"relative-mansfield-relative-strength",name:"Mansfield Relative Strength",ar:"مؤشر Mansfield Relative Strength",description:"Relative performance normalized around its long-term average.",defaults:{period:52,benchmarkSymbol:'EGX30'},rules:{period:integer(2),benchmarkSymbol:string()},outputs:[pane("mansfield-rs","Mansfield RS","dimensionless"),pane("period","period","dimensionless")],minimumHistory:52,requiredFields:["close"],requiredRole:'benchmark',compute:indicatorLogic.relativeMansfieldRelativeStrength}),
  define({backlogId:"REL-006",id:"relative-relative-rotation-graph-metrics",name:"Relative Rotation Graph metrics",ar:"مؤشر Relative Rotation Graph metrics",description:"Relative strength and momentum coordinates versus a benchmark.",defaults:{period:20,momentumPeriod:10,benchmarkSymbol:'EGX30'},rules:{period:integer(2),momentumPeriod:integer(),benchmarkSymbol:string()},outputs:[pane("jdk-rs-ratio","JdK RS-ratio","dimensionless"),pane("rs-momentum","RS-momentum","percent"),category("quadrant","quadrant")],minimumHistory:30,requiredFields:["close"],requiredRole:'benchmark',compute:indicatorLogic.relativeRelativeRotationGraphMetrics}),
  define({backlogId:"REL-007",id:"relative-cross-sectional-momentum-rank",name:"Cross-sectional momentum rank",ar:"مؤشر Cross-sectional momentum rank",description:"Ranks all eligible assets by recent return.",defaults:{},rules:{},outputs:[pane("rank","rank","dimensionless"),pane("percentile","percentile","percent"),pane("universe","universe","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"aligned authenticated comparison or benchmark series: EGX universe, B",compute:indicatorLogic.relativeCrossSectionalMomentumRank}),
  define({backlogId:"REL-008",id:"relative-risk-adjusted-momentum-rank",name:"Risk-adjusted momentum rank",ar:"مؤشر Risk-adjusted momentum rank",description:"Ranks return after accounting for volatility or drawdown.",defaults:{},rules:{},outputs:[pane("rank","rank","dimensionless"),pane("score","score","dimensionless"),pane("periods","periods","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"aligned authenticated comparison or benchmark series: EGX universe, B",compute:indicatorLogic.relativeRiskAdjustedMomentumRank}),
  define({backlogId:"REL-009",id:"relative-dual-momentum",name:"Dual Momentum",ar:"مؤشر Dual Momentum",description:"Combines absolute positive momentum with benchmark-relative momentum.",defaults:{period:60,benchmarkSymbol:'EGX30'},rules:{period:integer(),benchmarkSymbol:string()},outputs:[category("absolute-state","absolute state"),pane("relative-rank","relative rank","dimensionless")],minimumHistory:61,requiredFields:["close"],requiredRole:'benchmark',compute:indicatorLogic.relativeDualMomentum}),
  define({backlogId:"REL-010",id:"relative-sector-relative-strength",name:"Sector Relative Strength",ar:"مؤشر Sector Relative Strength",description:"Sector performance versus EGX30, EGX70, or the full market.",defaults:{},rules:{},outputs:[pane("ratio","ratio","dimensionless"),pane("return-spread","return spread","percent"),pane("rank","rank","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"aligned authenticated comparison or benchmark series: EGX sectors, BM",compute:indicatorLogic.relativeSectorRelativeStrength}),
  define({backlogId:"REL-011",id:"relative-rolling-correlation-matrix",name:"Rolling Correlation Matrix",ar:"مؤشر Rolling Correlation Matrix",description:"Pairwise co-movement between selected assets.",defaults:{period:60,comparisonSymbol:'COMPARISON'},rules:{period:integer(2),comparisonSymbol:string()},outputs:[pane("correlations","correlations","dimensionless"),category("clusters","clusters")],minimumHistory:61,requiredFields:["close"],requiredRole:'comparison',compute:indicatorLogic.relativeRollingCorrelationMatrix}),
  define({backlogId:"REL-012",id:"relative-rolling-beta-matrix",name:"Rolling Beta Matrix",ar:"مؤشر Rolling Beta Matrix",description:"Sensitivity of assets or sectors to a benchmark.",defaults:{period:60,benchmarkSymbol:'EGX30'},rules:{period:integer(2),benchmarkSymbol:string()},outputs:[pane("betas","betas","dimensionless"),pane("period","period","dimensionless")],minimumHistory:61,requiredFields:["close"],requiredRole:'benchmark',compute:indicatorLogic.relativeRollingBetaMatrix}),
  define({backlogId:"REL-013",id:"relative-lead-lag-correlation",name:"Lead-Lag Correlation",ar:"مؤشر Lead-Lag Correlation",description:"Tests whether one series tends to move before another.",defaults:{period:60,maxLag:5,comparisonSymbol:'COMPARISON'},rules:{period:integer(2),maxLag:integer(0,50),comparisonSymbol:string()},outputs:[pane("best-lag","best lag","dimensionless"),pane("correlation","correlation by lag","dimensionless")],minimumHistory:66,requiredFields:["close"],requiredRole:'comparison',compute:indicatorLogic.relativeLeadLagCorrelation}),
  define({backlogId:"REL-014",id:"relative-cointegration-spread",name:"Cointegration Spread",ar:"مؤشر Cointegration Spread",description:"Residual spread between a statistically linked pair.",defaults:{period:60,comparisonSymbol:'COMPARISON'},rules:{period:integer(2),comparisonSymbol:string()},outputs:[pane("hedge-ratio","hedge ratio","dimensionless"),pane("spread","spread","percent"),pane("z-score","z-score","dimensionless")],minimumHistory:60,requiredFields:["close"],requiredRole:'comparison',compute:indicatorLogic.relativeCointegrationSpread}),
  define({backlogId:"REL-015",id:"relative-pair-ratio-z-score",name:"Pair Ratio Z-score",ar:"مؤشر Pair Ratio Z-score",description:"Standardized asset ratio for relative-value monitoring.",defaults:{period:60,comparisonSymbol:'COMPARISON'},rules:{period:integer(2),comparisonSymbol:string()},outputs:[pane("ratio","ratio","dimensionless"),pane("z-score","z-score","dimensionless"),pane("period","period","dimensionless")],minimumHistory:60,requiredFields:["close"],requiredRole:'comparison',compute:indicatorLogic.relativePairRatioZScore}),
  define({backlogId:"REL-016",id:"relative-egx-versus-gold-relative-strength",name:"EGX versus Gold Relative Strength",ar:"مؤشر EGX versus Gold Relative Strength",description:"Local equities compared with EGP gold performance.",defaults:{period:20},rules:{period:integer()},outputs:[pane("ratio","ratio","dimensionless"),pane("return-spread","return spread","percent"),category("trend","trend")],minimumHistory:21,requiredFields:["close"],requiredRole:'gold',compute:indicatorLogic.relativeEgxVersusGoldRelativeStrength}),
  define({backlogId:"REL-017",id:"relative-egx-versus-usd-relative-strength",name:"EGX versus USD Relative Strength",ar:"مؤشر EGX versus USD Relative Strength",description:"Local equities compared with USD/EGP depreciation.",defaults:{period:20},rules:{period:integer()},outputs:[pane("real-nominal-relative-return","real and nominal relative return","percent")],minimumHistory:21,requiredFields:["close"],requiredRole:'usdEgp',compute:indicatorLogic.relativeEgxVersusUsdRelativeStrength}),
  define({backlogId:"REL-018",id:"relative-fund-versus-benchmark-attribution",name:"Fund versus Benchmark Attribution",ar:"مؤشر Fund versus Benchmark Attribution",description:"Fund performance relative to its declared benchmark.",defaults:{period:60,annualization:252,benchmarkSymbol:'EGX30'},rules:{period:integer(2),annualization:integer(),benchmarkSymbol:string()},outputs:[pane("excess-return","excess return","percent"),pane("beta","beta","dimensionless"),pane("tracking-error","tracking error","percent")],minimumHistory:61,requiredFields:["close"],requiredRole:'benchmark',compute:indicatorLogic.relativeFundVersusBenchmarkAttribution}),
  define({backlogId:"REL-019",id:"relative-currency-adjusted-return",name:"Currency-adjusted return",ar:"مؤشر Currency-adjusted return",description:"Converts an asset return into EGP or USD terms.",defaults:{period:1,currency:'USD'},rules:{period:integer(),currency:{kind:'select',values:['EGP','USD']}},outputs:[pane("adjusted-return","adjusted_return","percent"),category("selected-currency","selected currency")],minimumHistory:2,requiredFields:["close"],requiredRole:'usdEgp',compute:indicatorLogic.relativeCurrencyAdjustedReturn}),
  define({backlogId:"REL-020",id:"relative-inflation-adjusted-return",name:"Inflation-adjusted return",ar:"مؤشر Inflation-adjusted return",description:"Twelve-month nominal return deflated by Egyptian CPI.",defaults:{},rules:{},outputs:[pane("real-return","real_return","percent"),pane("annualized-real-return","annualized_real_return","percent")],minimumHistory:13,requiredFields:["close"],requiredRole:'egyptCpiIndex',compute:indicatorLogic.relativeInflationAdjustedReturn}),
]);
const OPERATIONAL=new Set([
  'REL-001','REL-002','REL-003','REL-004','REL-005','REL-006','REL-009','REL-011',
  'REL-012','REL-013','REL-014','REL-015','REL-016','REL-017','REL-018','REL-019','REL-020',
]);
export const RELATIVE_INTERMARKET_OPERATIONAL_DEFINITIONS=Object.freeze(RELATIVE_INTERMARKET_DEFINITIONS.filter((definition)=>OPERATIONAL.has(definition.backlogId)));
