import { createDiagnostic,type IndicatorOutputDefinition,type MarketField,type TimeSeriesIndicatorDefinition } from '../../contracts';
import { defineCategoryIndicator,type CategoryIndicatorSpec } from '../shared/category-definition';
import * as indicatorLogic from './logic';
import { category,event,integer,number,pane,type Params,type Rules } from './shared';
interface Input{backlogId:string;id:string;name:string;ar:string;description:string;defaults:Params;rules:Rules;outputs:readonly IndicatorOutputDefinition[];minimumHistory:number;requiredFields:readonly MarketField[];requiredSymbol?:string;unavailableCapability?:string;requiredModels?:readonly string[];requiresIndicatorOutputs?:boolean;compute:CategoryIndicatorSpec<Params>['compute'];}
function define(input:Input):TimeSeriesIndicatorDefinition<Params>{return defineCategoryIndicator({backlogId:input.backlogId,id:input.id,category:"ticknal-composites",name:input.name,description:{en:input.description,ar:input.ar},requiredFields:input.requiredFields,requiredCapabilities:input.requiredModels?['model-output']:input.requiresIndicatorOutputs?['indicator-output']:[],defaults:input.defaults,parameterRules:input.rules,outputs:input.outputs,minimumHistory:input.minimumHistory,tags:["ticknal-composites",'data-bound'],references:['Ticknal canonical indicator program'],availability:(frame,parameters,inputs)=>{const missingModel=input.requiredModels?.find((modelId)=>inputs.modelOutputsById[modelId]===undefined);if(missingModel)return createDiagnostic('DATA_CAPABILITY_MISSING','indicator.data.requiredModelMissing',{modelId:missingModel});if(input.requiresIndicatorOutputs&&Object.keys(inputs.indicatorOutputsById).length<(parameters.minimumInputs as number))return createDiagnostic('DATA_CAPABILITY_MISSING','indicator.data.insufficientIndicatorInputs',{minimumInputs:parameters.minimumInputs});return input.unavailableCapability?createDiagnostic('DATA_FIELD_MISSING','indicator.data.capabilityUnavailable',{capability:input.unavailableCapability}):input.requiredSymbol&&!frame.meta.symbol.toUpperCase().includes(input.requiredSymbol)?createDiagnostic('DATA_FIELD_MISSING','indicator.data.capabilityUnavailable',{capability:'selected '+input.requiredSymbol+' index series'}):null;},compute:input.compute});}
export const TICKNAL_COMPOSITE_DEFINITIONS:readonly TimeSeriesIndicatorDefinition<object>[]=Object.freeze([
  define({backlogId:"TKL-001",id:"ticknal-typhon-or-psi-8-master-index",name:"Typhon or PSI 8 Master Index",ar:"مؤشر Typhon or PSI 8 Master Index",description:"Proprietary strategy combining normalized price, RSI, banker flow, Bollinger position, Supertrend, DMI, MA spread, and slope.",defaults:{},rules:{},outputs:[pane("raw-index","raw index","dimensionless"),pane("master-index","master index","dimensionless"),pane("adjusted-index","adjusted index","dimensionless"),pane("levels-crossed","levels crossed","dimensionless")],minimumHistory:1,requiredFields:["close"],requiredModels:['typhon'],compute:indicatorLogic.ticknalTyphonOrPsi8MasterIndex}),
  define({backlogId:"TKL-002",id:"ticknal-psi-40-score",name:"PSI 40 Score",ar:"مؤشر PSI 40 Score",description:"Internal 40-condition momentum, trend, volatility, volume, and statistical score.",defaults:{},rules:{},outputs:[pane("score-0-100","score_0_100","dimensionless"),pane("category-subscores","category subscores","dimensionless"),pane("agreement-count","agreement count","count")],minimumHistory:1,requiredFields:["close"],requiredModels:['psi40'],compute:indicatorLogic.ticknalPsi40Score}),
  define({backlogId:"TKL-003",id:"ticknal-cerberus-or-psi-v2",name:"Cerberus or PSI V2",ar:"مؤشر Cerberus or PSI V2",description:"Three-headed stateful swing and regime strategy.",defaults:{},rules:{},outputs:[pane("zone","zone","dimensionless"),pane("up","up","dimensionless"),pane("down","down","dimensionless"),category("regime-direction","regime direction"),category("state-changes","state changes")],minimumHistory:1,requiredFields:["close"],requiredModels:['cerberus'],compute:indicatorLogic.ticknalCerberusOrPsiV2}),
  define({backlogId:"TKL-004",id:"ticknal-hydra-strategy",name:"HYDRA Strategy",ar:"مؤشر HYDRA Strategy",description:"Strategy built around the HYDRA regime model.",defaults:{},rules:{},outputs:[category("position-state","position state"),category("regime-value","regime value"),pane("dynamic-theta","dynamic theta","dimensionless"),event("entry-exit-events","entry and exit events")],minimumHistory:1,requiredFields:["close"],requiredModels:['hydra'],compute:indicatorLogic.ticknalHydraStrategy}),
  define({backlogId:"TKL-005",id:"ticknal-champion-strategy-resolver",name:"Champion Strategy Resolver",ar:"مؤشر Champion Strategy Resolver",description:"Chooses the positive-alpha strategy for each ticker.",defaults:{},rules:{},outputs:[category("winning-model","winning model"),pane("alpha","alpha","dimensionless"),pane("confidence","confidence","probability"),pane("comparison-metrics","comparison metrics","dimensionless")],minimumHistory:1,requiredFields:["close"],requiredModels:['champion'],compute:indicatorLogic.ticknalChampionStrategyResolver}),
  define({backlogId:"TKL-006",id:"ticknal-smart-money-flow",name:"Smart Money Flow",ar:"مؤشر Smart Money Flow",description:"Chart indicator using verified transaction statistics and price-volume absorption.",defaults:{"period":20},rules:{period:integer(2)},outputs:[pane("ats","Average trade size","price"),pane("relative_ats","Relative ATS","dimensionless"),pane("absorption","Absorption","dimensionless"),category("state","State")],minimumHistory:20,requiredFields:["high","low","close","volume","trades"],compute:indicatorLogic.ticknalSmartMoneyFlow}),
  define({backlogId:"TKL-007",id:"ticknal-strategy-consensus",name:"Strategy Consensus",ar:"مؤشر Strategy Consensus",description:"Agreement across Typhon, Cerberus, and HYDRA.",defaults:{},rules:{},outputs:[pane("vote-count","vote count","count"),category("consensus-state","consensus state"),pane("disagreement","disagreement","dimensionless")],minimumHistory:1,requiredFields:["close"],requiredModels:['typhon','cerberus','hydra'],compute:indicatorLogic.ticknalStrategyConsensus}),
  define({backlogId:"TKL-008",id:"ticknal-opportunity-quality-score",name:"Opportunity Quality Score",ar:"مؤشر Opportunity Quality Score",description:"Candidate ranking using signal age, alpha, risk, liquidity, and regime.",defaults:{},rules:{},outputs:[pane("score","score","dimensionless"),pane("rank","rank","dimensionless"),pane("component-explanations","component explanations","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"protected strategy or selected-indicator service outputs: EGX equities, PVT",compute:indicatorLogic.ticknalOpportunityQualityScore}),
  define({backlogId:"TKL-009",id:"ticknal-indicator-consensus-score",name:"Indicator Consensus Score",ar:"مؤشر Indicator Consensus Score",description:"User-selected set of normalized indicators combined without becoming a strategy.",defaults:{bullishThreshold:0.2,bearishThreshold:-0.2,minimumCoverage:0.5,minimumInputs:2,indicatorIds:'percentage-change,z-score'},rules:{bullishThreshold:number(-1,1),bearishThreshold:number(-1,1),minimumCoverage:number(0,1),minimumInputs:integer(1,100),indicatorIds:{kind:'string',minLength:1}},outputs:[event("bullish","bullish"),event("bearish","bearish"),pane("neutral-agreement-coverage","neutral agreement and coverage","dimensionless")],minimumHistory:1,requiredFields:["close"],requiresIndicatorOutputs:true,compute:indicatorLogic.ticknalIndicatorConsensusScore}),
  define({backlogId:"TKL-010",id:"ticknal-data-confidence-score",name:"Data Confidence Score",ar:"مؤشر Data Confidence Score",description:"Rates whether an indicator result is trustworthy given history length, gaps, volume, and freshness.",defaults:{},rules:{},outputs:[pane("confidence_0_100","Confidence","percent"),pane("warning_count","Warning count","count"),category("coverage_state","Coverage state")],minimumHistory:1,requiredFields:["close"],compute:indicatorLogic.ticknalDataConfidenceScore}),
]);
const OPERATIONAL=new Set([
  'TKL-001','TKL-002','TKL-003','TKL-004','TKL-005','TKL-006','TKL-007','TKL-009','TKL-010',
]);
export const TICKNAL_COMPOSITE_OPERATIONAL_DEFINITIONS=Object.freeze(TICKNAL_COMPOSITE_DEFINITIONS.filter((definition)=>OPERATIONAL.has(definition.backlogId)));
