import { createDiagnostic, type IndicatorInputCapability, type IndicatorOutputDefinition, type TimeSeriesIndicatorDefinition } from '../../contracts';
import { summarizeCompletedTrades } from '../../core/contextual/trade-statistics';
import { defineCategoryIndicator, type CategoryIndicatorSpec } from '../shared/category-definition';
import * as indicatorLogic from './logic';
import { category, integer, number, pane, type Params, type Rules } from './shared';
interface Input { backlogId:string; id:string; name:string; ar:string; description:string; defaults:Params; rules:Rules; outputs:readonly IndicatorOutputDefinition[]; minimumHistory:number; unavailableCapability?:string; requiredRoles?:readonly string[]; requiredCapabilities?:readonly IndicatorInputCapability[]; requireHoldingSeries?:boolean; compute:CategoryIndicatorSpec<Params>['compute']; }
function define(input:Input):TimeSeriesIndicatorDefinition<Params>{const capabilities=[...(input.requiredRoles?['numeric-series' as const]:[]),...(input.requiredCapabilities??[])];return defineCategoryIndicator({backlogId:input.backlogId,id:input.id,category:'risk-portfolio',name:input.name,description:{en:input.description,ar:input.ar},requiredFields:['close'],requiredCapabilities:capabilities,defaults:input.defaults,parameterRules:input.rules,outputs:input.outputs,minimumHistory:input.minimumHistory,tags:['risk','performance','portfolio'],references:['Ticknal canonical risk and portfolio specification'],availability:(_frame,_parameters,inputs)=>{const missing=input.requiredRoles?.find((role)=>inputs.seriesByRole[role]===undefined);if(missing)return createDiagnostic('DATA_CAPABILITY_MISSING','indicator.data.requiredRoleMissing',{role:missing});if(input.requiredCapabilities?.includes('completed-trades')&&inputs.completedTrades!==null){const diagnostic=summarizeCompletedTrades(inputs.completedTrades.trades).diagnostics[0];if(diagnostic!==undefined)return diagnostic;}if(input.requiredCapabilities?.includes('portfolio')&&inputs.portfolio!==null){if(inputs.portfolio.totalValue<=0||inputs.portfolio.holdings.some((holding)=>holding.marketValue<0))return createDiagnostic('DATA_FIELD_MISSING','indicator.data.invalidPortfolioValue',{field:'portfolio.totalValue'});if(input.requireHoldingSeries){const holdingRole=inputs.portfolio.holdings.map((holding)=>`holding:${holding.symbol}`).find((role)=>inputs.seriesByRole[role]===undefined);if(holdingRole)return createDiagnostic('DATA_CAPABILITY_MISSING','indicator.data.requiredRoleMissing',{role:holdingRole});}}return input.unavailableCapability?createDiagnostic('DATA_FIELD_MISSING','indicator.data.capabilityUnavailable',{capability:input.unavailableCapability}):null;},compute:input.compute});}
export const RISK_PORTFOLIO_DEFINITIONS:readonly TimeSeriesIndicatorDefinition<object>[]=Object.freeze([
  define({ backlogId:'RSK-001', id:'simple-return', name:"Simple return", ar:"العائد البسيط", description:"Percentage gain or loss over a selected bar horizon", defaults:{"horizon":1}, rules:{horizon:integer()}, outputs:[pane('return_pct','Return','percent')], minimumHistory:2, compute:indicatorLogic.simpleReturn }),
  define({ backlogId:'RSK-002', id:'annualized-return', name:"Annualized return", ar:"العائد السنوي", description:"Rolling compound return translated to an annual rate", defaults:{"period":252,"annualization":252}, rules:{period:integer(2),annualization:integer()}, outputs:[pane('annualized_return_pct','Annualized return','percent')], minimumHistory:253, compute:indicatorLogic.annualizedReturn }),
  define({ backlogId:'RSK-003', id:'compound-annual-growth-rate', name:"Compound Annual Growth Rate (CAGR)", ar:"معدل النمو السنوي المركب", description:"Expanding compound annual growth from the first observation", defaults:{"annualization":252}, rules:{annualization:integer()}, outputs:[pane('cagr_pct','CAGR','percent')], minimumHistory:2, compute:indicatorLogic.compoundAnnualGrowthRate }),
  define({ backlogId:'RSK-004', id:'maximum-drawdown', name:"Maximum Drawdown", ar:"أقصى تراجع", description:"Largest observed peak-to-trough decline", defaults:{}, rules:{}, outputs:[pane('max_drawdown_pct','Maximum drawdown','percent'),pane('drawdown_pct','Drawdown','percent'),pane('duration','Duration','count')], minimumHistory:1, compute:indicatorLogic.maximumDrawdown }),
  define({ backlogId:'RSK-005', id:'current-drawdown', name:"Current Drawdown", ar:"التراجع الحالي", description:"Current decline from the running peak and its duration", defaults:{}, rules:{}, outputs:[pane('current_drawdown_pct','Current drawdown','percent'),pane('duration','Duration','count')], minimumHistory:1, compute:indicatorLogic.currentDrawdown }),
  define({ backlogId:'RSK-006', id:'drawdown-duration', name:"Drawdown Duration", ar:"مدة التراجع", description:"Current and maximum time spent below a prior peak", defaults:{}, rules:{}, outputs:[pane('current_duration','Current duration','count'),pane('maximum_duration','Maximum duration','count')], minimumHistory:1, compute:indicatorLogic.drawdownDuration }),
  define({ backlogId:'RSK-007', id:'volatility', name:"Volatility", ar:"التقلب", description:"Annualized rolling standard deviation of returns", defaults:{"period":20,"annualization":252}, rules:{period:integer(2),annualization:integer()}, outputs:[pane('volatility_pct','Volatility','percent')], minimumHistory:21, compute:indicatorLogic.volatility }),
  define({ backlogId:'RSK-008', id:'downside-deviation', name:"Downside Deviation", ar:"الانحراف السلبي", description:"Annualized deviation of returns below a target", defaults:{"period":20,"annualization":252,"targetAnnualPct":0}, rules:{period:integer(2),annualization:integer(),targetAnnualPct:number(-100,100)}, outputs:[pane('downside_deviation_pct','Downside deviation','percent')], minimumHistory:21, compute:indicatorLogic.downsideDeviation }),
  define({ backlogId:'RSK-009', id:'sharpe-ratio', name:"Sharpe Ratio", ar:"نسبة شارب", description:"Annualized excess return per unit of total volatility", defaults:{"period":60,"annualization":252,"riskFreeAnnualPct":0}, rules:{period:integer(2),annualization:integer(),riskFreeAnnualPct:number(-100,100)}, outputs:[pane('sharpe','Sharpe','dimensionless')], minimumHistory:61, compute:indicatorLogic.sharpeRatio }),
  define({ backlogId:'RSK-010', id:'sortino-ratio', name:"Sortino Ratio", ar:"نسبة سورتينو", description:"Annualized excess return per unit of downside deviation", defaults:{"period":60,"annualization":252,"targetAnnualPct":0}, rules:{period:integer(2),annualization:integer(),targetAnnualPct:number(-100,100)}, outputs:[pane('sortino','Sortino','dimensionless')], minimumHistory:61, compute:indicatorLogic.sortinoRatio }),
  define({ backlogId:'RSK-011', id:'calmar-ratio', name:"Calmar Ratio", ar:"نسبة كالمار", description:"Annualized return divided by absolute maximum drawdown", defaults:{"period":252,"annualization":252}, rules:{period:integer(2),annualization:integer()}, outputs:[pane('calmar','Calmar','dimensionless')], minimumHistory:253, compute:indicatorLogic.calmarRatio }),
  define({ backlogId:'RSK-012', id:'omega-ratio', name:"Omega Ratio", ar:"نسبة أوميغا", description:"Sum of gains above a threshold divided by shortfalls below it", defaults:{"period":60,"annualization":252,"thresholdAnnualPct":0}, rules:{period:integer(2),annualization:integer(),thresholdAnnualPct:number(-100,100)}, outputs:[pane('omega','Omega','dimensionless')], minimumHistory:61, compute:indicatorLogic.omegaRatio }),
  define({ backlogId:'RSK-013', id:'information-ratio', name:"Information Ratio", ar:"نسبة المعلومات", description:"Active return per unit of tracking error", defaults:{period:60,annualization:252,riskFreeAnnualPct:0}, rules:{period:integer(2),annualization:integer(),riskFreeAnnualPct:number(-100,100)}, outputs:[pane('information_ratio','Information ratio','dimensionless')], minimumHistory:61, requiredRoles:['benchmark'], compute:indicatorLogic.informationRatio }),
  define({ backlogId:'RSK-014', id:'treynor-ratio', name:"Treynor Ratio", ar:"نسبة ترينور", description:"Excess return per unit of authenticated market beta", defaults:{period:60,annualization:252,riskFreeAnnualPct:0}, rules:{period:integer(2),annualization:integer(),riskFreeAnnualPct:number(-100,100)}, outputs:[pane('treynor','Treynor','dimensionless')], minimumHistory:61, requiredRoles:['benchmark'], compute:indicatorLogic.treynorRatio }),
  define({ backlogId:'RSK-015', id:'jensen-alpha', name:"Jensen Alpha", ar:"ألفا جنسن", description:"CAPM risk-adjusted excess return against a benchmark", defaults:{period:60,annualization:252,riskFreeAnnualPct:0}, rules:{period:integer(2),annualization:integer(),riskFreeAnnualPct:number(-100,100)}, outputs:[pane('alpha_pct','Alpha','percent'),pane('beta','Beta','dimensionless')], minimumHistory:61, requiredRoles:['benchmark'], compute:indicatorLogic.jensenAlpha }),
  define({ backlogId:'RSK-016', id:'tracking-error', name:"Tracking Error", ar:"خطأ التتبع", description:"Volatility of returns relative to an authenticated benchmark", defaults:{period:60,annualization:252,riskFreeAnnualPct:0}, rules:{period:integer(2),annualization:integer(),riskFreeAnnualPct:number(-100,100)}, outputs:[pane('tracking_error_pct','Tracking error','percent')], minimumHistory:61, requiredRoles:['benchmark'], compute:indicatorLogic.trackingError }),
  define({ backlogId:'RSK-017', id:'historical-value-at-risk', name:"Value at Risk (Historical VaR)", ar:"القيمة المعرضة للخطر التاريخية", description:"Empirical lower-tail loss threshold", defaults:{"period":100,"confidencePct":95,"horizon":1}, rules:{period:integer(5),confidencePct:number(50,99.99),horizon:integer()}, outputs:[pane('var_pct','Historical VaR','percent')], minimumHistory:101, compute:indicatorLogic.historicalValueAtRisk }),
  define({ backlogId:'RSK-018', id:'parametric-value-at-risk', name:"Parametric VaR", ar:"القيمة المعرضة للخطر المعلمية", description:"Normal-distribution loss threshold using rolling mean and volatility", defaults:{"period":100,"confidencePct":95,"horizon":1}, rules:{period:integer(5),confidencePct:number(50,99.99),horizon:integer()}, outputs:[pane('var_pct','Parametric VaR','percent')], minimumHistory:101, compute:indicatorLogic.parametricValueAtRisk }),
  define({ backlogId:'RSK-019', id:'conditional-value-at-risk', name:"Conditional VaR or Expected Shortfall", ar:"الخسارة المتوقعة", description:"Average empirical loss beyond historical VaR", defaults:{"period":100,"confidencePct":95}, rules:{period:integer(5),confidencePct:number(50,99.99)}, outputs:[pane('cvar_pct','Expected shortfall','percent')], minimumHistory:101, compute:indicatorLogic.conditionalValueAtRisk }),
  define({ backlogId:'RSK-020', id:'maximum-adverse-excursion', name:"Maximum Adverse Excursion", ar:"أقصى حركة معاكسة", description:"Worst move against each completed historical trade", defaults:{}, rules:{}, outputs:[pane('mae_pct','MAE','percent'),pane('average_mae_pct','Average MAE','percent')], minimumHistory:1, requiredCapabilities:['completed-trades'], compute:indicatorLogic.maximumAdverseExcursion }),
  define({ backlogId:'RSK-021', id:'maximum-favorable-excursion', name:"Maximum Favorable Excursion", ar:"أقصى حركة مواتية", description:"Best move in favor of each completed historical trade", defaults:{}, rules:{}, outputs:[pane('mfe_pct','MFE','percent'),pane('average_mfe_pct','Average MFE','percent')], minimumHistory:1, requiredCapabilities:['completed-trades'], compute:indicatorLogic.maximumFavorableExcursion }),
  define({ backlogId:'RSK-022', id:'profit-factor', name:"Profit Factor", ar:"عامل الربح", description:"Gross strategy gains divided by gross losses", defaults:{}, rules:{}, outputs:[pane('profit_factor','Profit factor','dimensionless')], minimumHistory:1, requiredCapabilities:['completed-trades'], compute:indicatorLogic.profitFactor }),
  define({ backlogId:'RSK-023', id:'win-rate', name:"Win Rate", ar:"معدل الفوز", description:"Percentage of completed trades that were profitable", defaults:{}, rules:{}, outputs:[pane('win_rate_pct','Win rate','percent'),pane('sample_count','Sample count','count')], minimumHistory:1, requiredCapabilities:['completed-trades'], compute:indicatorLogic.winRate }),
  define({ backlogId:'RSK-024', id:'expectancy', name:"Expectancy", ar:"القيمة المتوقعة", description:"Average expected profit or loss per completed trade", defaults:{}, rules:{}, outputs:[pane('expectancy_amount','Expectancy','price'),pane('expectancy_pct','Expectancy','percent')], minimumHistory:1, requiredCapabilities:['completed-trades'], compute:indicatorLogic.expectancy }),
  define({ backlogId:'RSK-025', id:'payoff-ratio', name:"Payoff Ratio", ar:"نسبة العائد إلى الخسارة", description:"Average winning trade divided by average losing trade", defaults:{}, rules:{}, outputs:[pane('payoff_ratio','Payoff ratio','dimensionless')], minimumHistory:1, requiredCapabilities:['completed-trades'], compute:indicatorLogic.payoffRatio }),
  define({ backlogId:'RSK-026', id:'kelly-fraction', name:"Kelly Fraction", ar:"كسر كيلي", description:"Theoretical capital fraction from win rate and payoff", defaults:{fraction:0.5}, rules:{fraction:number(0,1)}, outputs:[pane('full_kelly','Full Kelly','percent'),pane('fractional_kelly','Fractional Kelly','percent')], minimumHistory:1, requiredCapabilities:['completed-trades'], compute:indicatorLogic.kellyFraction }),
  define({ backlogId:'RSK-027', id:'risk-of-ruin', name:"Risk of Ruin", ar:"خطر الإفلاس", description:"Estimated probability of breaching a capital-loss threshold", defaults:{capitalLossPct:20,riskPerTradePct:2}, rules:{capitalLossPct:number(0.1,100),riskPerTradePct:number(0.01,100)}, outputs:[pane('ruin_probability','Risk of ruin','probability')], minimumHistory:1, requiredCapabilities:['completed-trades'], compute:indicatorLogic.riskOfRuin }),
  define({ backlogId:'RSK-028', id:'ulcer-performance-index', name:"Ulcer Performance Index", ar:"مؤشر أداء أولسر", description:"Annualized return divided by root-mean-square drawdown", defaults:{"period":252,"annualization":252,"riskFreeAnnualPct":0}, rules:{period:integer(5),annualization:integer(),riskFreeAnnualPct:number(-100,100)}, outputs:[pane('upi','Ulcer performance index','dimensionless')], minimumHistory:253, compute:indicatorLogic.ulcerPerformanceIndex }),
  define({ backlogId:'RSK-029', id:'gain-to-pain-ratio', name:"Gain-to-Pain Ratio", ar:"نسبة المكسب إلى الألم", description:"Sum of rolling returns divided by absolute losses", defaults:{"period":60}, rules:{period:integer(2)}, outputs:[pane('gain_to_pain','Gain to pain','dimensionless')], minimumHistory:61, compute:indicatorLogic.gainToPainRatio }),
  define({ backlogId:'RSK-030', id:'recovery-factor', name:"Recovery Factor", ar:"عامل الاسترداد", description:"Net completed-trade profit divided by maximum realized-equity drawdown", defaults:{}, rules:{}, outputs:[pane('recovery_factor','Recovery factor','dimensionless')], minimumHistory:1, requiredCapabilities:['completed-trades'], compute:indicatorLogic.recoveryFactor }),
  define({ backlogId:'RSK-031', id:'portfolio-beta', name:"Portfolio Beta", ar:"بيتا المحفظة", description:"Weighted portfolio sensitivity to a benchmark", defaults:{period:60,annualization:252}, rules:{period:integer(2),annualization:integer()}, outputs:[pane('beta','Portfolio beta','dimensionless'),pane('component_contribution','Largest component beta contribution','dimensionless')], minimumHistory:61, requiredRoles:['benchmark'], requiredCapabilities:['portfolio'], requireHoldingSeries:true, compute:indicatorLogic.portfolioBeta }),
  define({ backlogId:'RSK-032', id:'marginal-risk-contribution', name:"Marginal Risk Contribution", ar:"المساهمة الحدية في المخاطر", description:"Largest holding contribution to portfolio volatility", defaults:{period:60,annualization:252}, rules:{period:integer(2),annualization:integer()}, outputs:[pane('marginal_contribution','Largest marginal contribution','dimensionless'),pane('percentage_contribution','Largest percentage contribution','percent')], minimumHistory:61, requiredCapabilities:['portfolio','numeric-series'], requireHoldingSeries:true, compute:indicatorLogic.marginalRiskContribution }),
  define({ backlogId:'RSK-033', id:'concentration-hhi', name:"Concentration and HHI", ar:"التركيز ومؤشر هيرفندال", description:"Portfolio concentration and effective holding count", defaults:{period:60,annualization:252}, rules:{period:integer(2),annualization:integer()}, outputs:[pane('hhi','HHI','dimensionless'),pane('effective_holdings','Effective holdings','count')], minimumHistory:1, requiredCapabilities:['portfolio'], compute:indicatorLogic.concentrationHhi }),
  define({ backlogId:'RSK-034', id:'diversification-ratio', name:"Diversification Ratio", ar:"نسبة التنويع", description:"Weighted asset volatility divided by portfolio volatility", defaults:{period:60,annualization:252}, rules:{period:integer(2),annualization:integer()}, outputs:[pane('diversification_ratio','Diversification ratio','dimensionless')], minimumHistory:61, requiredCapabilities:['portfolio','numeric-series'], requireHoldingSeries:true, compute:indicatorLogic.diversificationRatio }),
  define({ backlogId:'RSK-035', id:'correlation-stress', name:"Correlation Stress", ar:"ضغط الارتباط", description:"Portfolio risk under elevated cross-asset correlations", defaults:{period:60,annualization:252,stressCorrelation:0.8}, rules:{period:integer(2),annualization:integer(),stressCorrelation:number(-1,1)}, outputs:[pane('stressed_volatility_pct','Stressed volatility','percent'),pane('delta_risk_pct','Delta risk','percent')], minimumHistory:61, requiredCapabilities:['portfolio','numeric-series'], requireHoldingSeries:true, compute:indicatorLogic.correlationStress }),
  define({ backlogId:'RSK-036', id:'inflation-drag', name:"Inflation drag", ar:"أثر التضخم", description:"Nominal portfolio value lost to Egyptian inflation", defaults:{}, rules:{}, outputs:[pane('real_value','Real value','price'),pane('drag_amount','Drag amount','price'),pane('drag_pct','Drag','percent')], minimumHistory:1, unavailableCapability:"Egyptian CPI series and portfolio value history", compute:indicatorLogic.inflationDrag }),
]);
const OPERATIONAL=new Set([
  'RSK-001','RSK-002','RSK-003','RSK-004','RSK-005','RSK-006','RSK-007','RSK-008',
  'RSK-009','RSK-010','RSK-011','RSK-012','RSK-013','RSK-014','RSK-015','RSK-016',
  'RSK-017','RSK-018','RSK-019','RSK-020','RSK-021','RSK-022','RSK-023','RSK-024',
  'RSK-025','RSK-026','RSK-027','RSK-028','RSK-029','RSK-030','RSK-031','RSK-032',
  'RSK-033','RSK-034','RSK-035',
]);
export const RISK_PORTFOLIO_OPERATIONAL_DEFINITIONS=Object.freeze(RISK_PORTFOLIO_DEFINITIONS.filter((definition)=>OPERATIONAL.has(definition.backlogId)));
