import type { IndicatorOutputDefinition, IndicatorOutputs, TimeSeriesFrame, TimeSeriesIndicatorDefinition } from '../../contracts';
import { atr, linearRegressionEnd, rollingMax, rollingMin, rollingStdDev, sma } from '../../core/series';
import { defineCategoryIndicator, type CategoryIndicatorSpec, type CategoryParameterRule } from '../shared/category-definition';
import * as indicatorLogic from './logic';
import { Params, Rules, category, event, integer, number, overlay, pane, previous } from './shared';

interface Input { backlogId: string; id: string; name: string; ar: string; description: string; defaults?: Params; rules?: Rules; outputs: readonly IndicatorOutputDefinition[]; minimumHistory: number; compute: CategoryIndicatorSpec<Params>['compute']; repaintBehavior?: CategoryIndicatorSpec<Params>['repaintBehavior']; confirmationDelay?: number; }
function define(input: Input): TimeSeriesIndicatorDefinition<Params> { return defineCategoryIndicator({ backlogId: input.backlogId, id: input.id, category: 'market-structure', name: input.name, description: { en: input.description, ar: input.ar }, requiredFields: ['open', 'high', 'low', 'close'], defaults: input.defaults ?? {}, parameterRules: input.rules ?? {}, outputs: input.outputs, minimumHistory: input.minimumHistory, tags: ['market-structure', 'levels'], references: ['Ticknal canonical market structure specification'], repaintBehavior: input.repaintBehavior, confirmationDelay: input.confirmationDelay, compute: input.compute }); }

const classicOutputs = ['pivot', 'r1', 's1', 'r2', 's2', 'r3', 's3', 'r4', 's4', 'r5', 's5'].map((key) => overlay(key, key.toUpperCase()));
const fibOutputs = ['pivot', 'r1', 's1', 'r2', 's2', 'r3', 's3'].map((key) => overlay(key, key.toUpperCase()));

export const MARKET_STRUCTURE_DEFINITIONS: readonly TimeSeriesIndicatorDefinition<object>[] = Object.freeze([
  define({ backlogId: 'STR-001', id: 'confirmed-pivot-highs-lows', name: 'Confirmed pivot highs and lows', ar: 'القمم والقيعان المحورية المؤكدة', description: 'Local extrema confirmed by bars on both sides.', defaults: { left: 3, right: 3 }, rules: { left: integer(), right: integer() }, outputs: [overlay('pivot_high', 'Pivot high'), overlay('pivot_low', 'Pivot low')], minimumHistory: 7, repaintBehavior: 'confirmed-with-delay', confirmationDelay: 3, compute: indicatorLogic.confirmedPivotHighsLows }),
  define({ backlogId: 'STR-002', id: 'swing-mapper', name: 'Swing Mapper', ar: 'خريطة التأرجحات', description: 'Directional swings that reverse after an ATR threshold.', defaults: { atrPeriod: 14, multiplier: 2 }, rules: { atrPeriod: integer(), multiplier: number(0.1, 20) }, outputs: [overlay('swing_high', 'Swing high'), overlay('swing_low', 'Swing low'), category('direction', 'Direction')], minimumHistory: 14, repaintBehavior: 'provisional-latest', compute: indicatorLogic.swingMapper }),
  define({ backlogId: 'STR-003', id: 'zig-zag', name: 'Zig Zag', ar: 'الزجزاج', description: 'Price reversals exceeding a configurable percentage.', defaults: { reversalPct: 5 }, rules: { reversalPct: number(0.1, 100) }, outputs: [overlay('pivots', 'Pivots'), pane('legs', 'Leg direction', 'count'), pane('change_pct', 'Change', 'percent')], minimumHistory: 2, repaintBehavior: 'provisional-latest', compute: indicatorLogic.zigZag }),
  define({ backlogId: 'STR-004', id: 'ticknal-support-resistance', name: 'Ticknal Support and Resistance', ar: 'دعم ومقاومة تيكنال', description: 'Adaptive rolling support, resistance, midpoint, and trend channel.', defaults: { period: 50 }, rules: { period: integer() }, outputs: [overlay('resistance', 'Resistance'), overlay('support', 'Support'), overlay('midpoint', 'Midpoint'), overlay('upper_trend', 'Upper trend'), overlay('lower_trend', 'Lower trend')], minimumHistory: 50, compute: indicatorLogic.ticknalSupportResistance }),
  define({ backlogId: 'STR-005', id: 'classic-pivot-points', name: 'Classic Pivot Points', ar: 'نقاط الارتكاز الكلاسيكية', description: 'Previous-bar classic support and resistance levels.', outputs: classicOutputs, minimumHistory: 2, compute: indicatorLogic.classicPivotPoints }),
  define({ backlogId: 'STR-006', id: 'fibonacci-pivot-points', name: 'Fibonacci Pivot Points', ar: 'نقاط ارتكاز فيبوناتشي', description: 'Previous-bar pivot with Fibonacci range offsets.', outputs: fibOutputs, minimumHistory: 2, compute: indicatorLogic.fibonacciPivotPoints }),
  define({ backlogId: 'STR-007', id: 'camarilla-pivot-points', name: 'Camarilla Pivot Points', ar: 'نقاط ارتكاز كاماريلا', description: 'Close-centered support and resistance levels from previous range.', outputs: Array.from({ length: 6 }, (_, i) => [overlay(`h${i + 1}`, `H${i + 1}`), overlay(`l${i + 1}`, `L${i + 1}`)]).flat(), minimumHistory: 2, compute: indicatorLogic.camarillaPivotPoints }),
  define({ backlogId: 'STR-008', id: 'woodie-pivot-points', name: 'Woodie Pivot Points', ar: 'نقاط ارتكاز وودي', description: 'Pivot levels weighted toward the current open.', outputs: classicOutputs, minimumHistory: 2, compute: indicatorLogic.woodiePivotPoints }),
  define({ backlogId: 'STR-009', id: 'demark-pivot-points', name: 'DeMark Pivot Points', ar: 'نقاط ارتكاز ديمارك', description: 'Conditional pivot, support, and resistance from prior open-close direction.', outputs: [overlay('pivot', 'Pivot'), overlay('support', 'Support'), overlay('resistance', 'Resistance')], minimumHistory: 2, compute: indicatorLogic.demarkPivotPoints }),
  define({ backlogId: 'STR-010', id: 'fibonacci-retracement', name: 'Fibonacci Retracement', ar: 'تصحيح فيبوناتشي', description: 'Rolling swing retracement levels.', defaults: { period: 50 }, rules: { period: integer() }, outputs: [overlay('level_236', '23.6%'), overlay('level_382', '38.2%'), overlay('level_500', '50%'), overlay('level_618', '61.8%'), overlay('level_786', '78.6%')], minimumHistory: 50, compute: indicatorLogic.fibonacciRetracement }),
  define({ backlogId: 'STR-011', id: 'fibonacci-extension', name: 'Fibonacci Extension', ar: 'امتداد فيبوناتشي', description: 'Rolling swing extension targets.', defaults: { period: 50 }, rules: { period: integer() }, outputs: [overlay('level_1272', '127.2%'), overlay('level_1618', '161.8%'), overlay('level_2618', '261.8%')], minimumHistory: 50, compute: indicatorLogic.fibonacciExtension }),
  define({ backlogId: 'STR-012', id: 'auto-fibonacci', name: 'Auto Fibonacci', ar: 'فيبوناتشي التلقائي', description: 'Automatically anchored rolling Fibonacci levels.', defaults: { period: 50, confirmation: 3 }, rules: { period: integer(), confirmation: integer() }, outputs: [overlay('swing_high', 'Swing high'), overlay('swing_low', 'Swing low'), overlay('level_382', '38.2%'), overlay('level_618', '61.8%')], minimumHistory: 53, repaintBehavior: 'confirmed-with-delay', confirmationDelay: 3, compute: indicatorLogic.autoFibonacci }),
  define({ backlogId: 'STR-013', id: 'rolling-support-resistance', name: 'Rolling support and resistance', ar: 'الدعم والمقاومة المتحركة', description: 'Rolling high, low, and midpoint.', defaults: { period: 20 }, rules: { period: integer() }, outputs: [overlay('support', 'Support'), overlay('resistance', 'Resistance'), overlay('midpoint', 'Midpoint')], minimumHistory: 20, compute: indicatorLogic.rollingSupportResistance }),
  define({ backlogId: 'STR-014', id: 'touch-count-price-zones', name: 'Touch-count price zones', ar: 'مناطق السعر بعدد اللمسات', description: 'Rolling zone around the mean with touch count inside tolerance.', defaults: { period: 50, tolerancePct: 1 }, rules: { period: integer(), tolerancePct: number(0.01, 20) }, outputs: [overlay('zone_center', 'Zone center'), overlay('zone_upper', 'Zone upper'), overlay('zone_lower', 'Zone lower'), pane('touches', 'Touches', 'count'), pane('strength', 'Strength', 'percent')], minimumHistory: 50, compute: indicatorLogic.touchCountPriceZones }),
  define({ backlogId: 'STR-015', id: 'atr-support-resistance-zones', name: 'ATR support and resistance zones', ar: 'مناطق الدعم والمقاومة بالنطاق الحقيقي', description: 'Rolling levels expanded into ATR-scaled zones.', defaults: { period: 20, atrPeriod: 14, multiplier: 0.5 }, rules: { period: integer(), atrPeriod: integer(), multiplier: number(0.01, 10) }, outputs: [overlay('resistance_upper', 'Resistance upper'), overlay('resistance_lower', 'Resistance lower'), overlay('support_upper', 'Support upper'), overlay('support_lower', 'Support lower')], minimumHistory: 20, compute: indicatorLogic.atrSupportResistanceZones }),
  define({ backlogId: 'STR-016', id: 'trendlines-from-pivots', name: 'Trendlines from pivots', ar: 'خطوط الاتجاه من المحاور', description: 'Rolling high and low regression trendlines.', defaults: { period: 50 }, rules: { period: integer() }, outputs: [overlay('upper_trendline', 'Upper trendline'), overlay('lower_trendline', 'Lower trendline'), pane('upper_slope', 'Upper slope', 'price'), pane('lower_slope', 'Lower slope', 'price')], minimumHistory: 50, compute: indicatorLogic.trendlinesFromPivots }),
  define({ backlogId: 'STR-017', id: 'linear-regression-channel', name: 'Linear Regression Channel', ar: 'قناة الانحدار الخطي', description: 'Rolling regression with standard-deviation bands, slope, and R-squared.', defaults: { period: 100, deviations: 2 }, rules: { period: integer(2), deviations: number(0.1, 10) }, outputs: [overlay('regression', 'Regression'), overlay('upper', 'Upper'), overlay('lower', 'Lower'), pane('slope', 'Slope', 'price'), pane('r_squared', 'R squared')], minimumHistory: 100, compute: indicatorLogic.linearRegressionChannel }),
  define({ backlogId: 'STR-018', id: 'raff-regression-channel', name: 'Raff Regression Channel', ar: 'قناة انحدار راف', description: 'Regression center with bands set by maximum residual deviation.', defaults: { period: 100 }, rules: { period: integer(2) }, outputs: [overlay('center', 'Center'), overlay('upper', 'Upper'), overlay('lower', 'Lower')], minimumHistory: 100, compute: indicatorLogic.raffRegressionChannel }),
  define({ backlogId: 'STR-019', id: 'andrews-pitchfork', name: 'Andrews Pitchfork', ar: 'شوكة أندروز', description: 'Rolling median line with parallel lines through price extremes.', defaults: { period: 50 }, rules: { period: integer(3) }, outputs: [overlay('median', 'Median'), overlay('upper', 'Upper parallel'), overlay('lower', 'Lower parallel')], minimumHistory: 50, compute: indicatorLogic.andrewsPitchfork }),
  define({ backlogId: 'STR-020', id: 'break-of-structure', name: 'Break of Structure (BOS)', ar: 'كسر الهيكل', description: 'Close breaks a prior rolling swing boundary.', defaults: { period: 20 }, rules: { period: integer() }, outputs: [event('bullish_bos', 'Bullish BOS'), event('bearish_bos', 'Bearish BOS'), overlay('level', 'Broken level')], minimumHistory: 21, compute: indicatorLogic.breakOfStructure }),
  define({ backlogId: 'STR-021', id: 'change-of-character', name: 'Change of Character (CHoCH)', ar: 'تغير السلوك', description: 'First structural break against the prevailing regression direction.', defaults: { period: 20 }, rules: { period: integer() }, outputs: [event('bullish_choch', 'Bullish CHoCH'), event('bearish_choch', 'Bearish CHoCH')], minimumHistory: 21, compute: indicatorLogic.changeOfCharacter }),
  define({ backlogId: 'STR-022', id: 'higher-high-higher-low-state', name: 'Higher-high and higher-low state', ar: 'حالة القمم والقيعان الصاعدة', description: 'Labels changes in rolling swing highs and lows.', defaults: { period: 10 }, rules: { period: integer() }, outputs: [event('higher_high', 'Higher high'), event('higher_low', 'Higher low'), event('lower_high', 'Lower high'), event('lower_low', 'Lower low'), category('trend_state', 'Trend state')], minimumHistory: 11, compute: indicatorLogic.higherHighHigherLowState }),
  define({ backlogId: 'STR-023', id: 'consolidation-range', name: 'Consolidation range', ar: 'نطاق التجميع', description: 'Tight rolling range with duration and width.', defaults: { period: 20, maximumWidthPct: 5 }, rules: { period: integer(), maximumWidthPct: number(0.1, 100) }, outputs: [overlay('upper', 'Upper'), overlay('lower', 'Lower'), pane('duration', 'Duration', 'count'), pane('width_pct', 'Width', 'percent')], minimumHistory: 20, compute: indicatorLogic.consolidationRange }),
  define({ backlogId: 'STR-024', id: 'range-breakout', name: 'Range breakout', ar: 'اختراق النطاق', description: 'Close exits a prior tight rolling range.', defaults: { period: 20, maximumWidthPct: 5 }, rules: { period: integer(), maximumWidthPct: number(0.1, 100) }, outputs: [event('breakout_up', 'Breakout up'), event('breakout_down', 'Breakout down'), overlay('level', 'Breakout level')], minimumHistory: 21, compute: indicatorLogic.rangeBreakout }),
  define({ backlogId: 'STR-025', id: 'opening-range', name: 'Opening range', ar: 'نطاق الافتتاح', description: 'High and low of the first configured bars in the loaded session.', defaults: { bars: 5 }, rules: { bars: integer() }, outputs: [overlay('opening_high', 'Opening high'), overlay('opening_low', 'Opening low'), event('breakout_up', 'Breakout up'), event('breakout_down', 'Breakout down')], minimumHistory: 6, compute: indicatorLogic.openingRange }),
  define({ backlogId: 'STR-026', id: 'previous-period-levels', name: 'Previous period levels', ar: 'مستويات الفترة السابقة', description: 'Previous bar open, high, low, and close levels.', outputs: [overlay('prior_open', 'Prior open'), overlay('prior_high', 'Prior high'), overlay('prior_low', 'Prior low'), overlay('prior_close', 'Prior close')], minimumHistory: 2, compute: indicatorLogic.previousPeriodLevels }),
  define({ backlogId: 'STR-027', id: 'all-time-52-week-levels', name: 'All-time and 52-week levels', ar: 'مستويات كل الزمن و52 أسبوعاً', description: 'Expanding all-time and rolling one-year extremes with distance.', defaults: { yearBars: 252 }, rules: { yearBars: integer() }, outputs: [overlay('all_time_high', 'All-time high'), overlay('all_time_low', 'All-time low'), overlay('year_high', '52-week high'), overlay('year_low', '52-week low'), pane('distance_to_high_pct', 'Distance to high', 'percent')], minimumHistory: 1, compute: indicatorLogic.allTime52WeekLevels }),
  define({ backlogId: 'STR-028', id: 'fair-value-gap', name: 'Fair Value Gap', ar: 'فجوة القيمة العادلة', description: 'Three-candle imbalance where outer candle ranges do not overlap.', outputs: [overlay('bullish_upper', 'Bullish upper'), overlay('bullish_lower', 'Bullish lower'), overlay('bearish_upper', 'Bearish upper'), overlay('bearish_lower', 'Bearish lower'), category('fill_state', 'Fill state')], minimumHistory: 3, compute: indicatorLogic.fairValueGap }),
  define({ backlogId: 'STR-029', id: 'price-gap-zones', name: 'Price gap zones', ar: 'مناطق فجوات السعر', description: 'Range gaps between consecutive bars with fill percentage and state.', outputs: [overlay('upper', 'Gap upper'), overlay('lower', 'Gap lower'), pane('fill_pct', 'Fill', 'percent'), category('state', 'State')], minimumHistory: 2, compute: indicatorLogic.priceGapZones }),
  define({ backlogId: 'STR-030', id: 'supply-demand-zones', name: 'Supply and demand zones', ar: 'مناطق العرض والطلب', description: 'Compact bases followed by ATR-scaled directional impulses.', defaults: { baseBars: 3, atrPeriod: 14, impulseMultiple: 1.5 }, rules: { baseBars: integer(2), atrPeriod: integer(), impulseMultiple: number(0.5, 10) }, outputs: [overlay('zone_upper', 'Zone upper'), overlay('zone_lower', 'Zone lower'), category('direction', 'Direction'), pane('strength', 'Strength')], minimumHistory: 17, compute: indicatorLogic.supplyDemandZones }),
  define({ backlogId: 'STR-031', id: 'order-block-heuristic', name: 'Order block heuristic', ar: 'استدلال كتلة الأوامر', description: 'Last opposing candle before an ATR-scaled structural impulse.', defaults: { atrPeriod: 14, impulseMultiple: 1.5 }, rules: { atrPeriod: integer(), impulseMultiple: number(0.5, 10) }, outputs: [overlay('zone_upper', 'Zone upper'), overlay('zone_lower', 'Zone lower'), category('direction', 'Direction'), overlay('invalidation', 'Invalidation')], minimumHistory: 15, compute: indicatorLogic.orderBlockHeuristic }),
  define({ backlogId: 'STR-032', id: 'market-structure-score', name: 'Market structure score', ar: 'درجة هيكل السوق', description: 'Composite score from regression direction, breakouts, and range position.', defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('score', 'Structure score', 'count'), event('bullish', 'Bullish'), event('bearish', 'Bearish'), event('neutral', 'Neutral')], minimumHistory: 21, compute: indicatorLogic.marketStructureScore }),
]);
