import type { IndicatorOutputDefinition, IndicatorOutputs, MarketField, TimeSeriesFrame, TimeSeriesIndicatorDefinition } from '../../contracts';
import { atr, ema, percentileRank, rma, rollingMax, rollingMin, rsi, sma, wma } from '../../core/series';
import { rollingSum } from '../../core/rolling/sum';
import { defineCategoryIndicator, type CategoryIndicatorSpec, type CategoryParameterRule } from '../shared/category-definition';
import * as indicatorLogic from './logic';
import { Params, Rules, category, change, divergence, event, integer, number, pane, stochastic } from './shared';

interface Input {
  backlogId: string; id: string; name: string; ar: string; description: string; defaults: Params; rules: Rules;
  outputs: readonly IndicatorOutputDefinition[]; minimumHistory: number; compute: CategoryIndicatorSpec<Params>['compute'];
  requiredFields?: readonly MarketField[]; repaintBehavior?: CategoryIndicatorSpec<Params>['repaintBehavior']; confirmationDelay?: number;
}

function define(input: Input): TimeSeriesIndicatorDefinition<Params> {
  return defineCategoryIndicator({ backlogId: input.backlogId, id: input.id, category: 'momentum', name: input.name,
    description: { en: input.description, ar: input.ar }, requiredFields: input.requiredFields ?? ['close'], defaults: input.defaults,
    parameterRules: input.rules, outputs: input.outputs, minimumHistory: input.minimumHistory, tags: ['momentum', 'oscillator'],
    references: ['Ticknal canonical formula specification'], repaintBehavior: input.repaintBehavior, confirmationDelay: input.confirmationDelay, compute: input.compute });
}

export const MOMENTUM_DEFINITIONS: readonly TimeSeriesIndicatorDefinition<object>[] = Object.freeze([
  define({ backlogId: 'MOM-001', id: 'relative-strength-index', name: 'Relative Strength Index (RSI)', ar: 'مؤشر القوة النسبية', description: 'Wilder ratio of average gains to average losses.', defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('rsi', 'RSI', 'percent')], minimumHistory: 15, compute: indicatorLogic.relativeStrengthIndex }),
  define({ backlogId: 'MOM-002', id: 'stochastic-oscillator', name: 'Stochastic Oscillator', ar: 'مذبذب ستوكاستيك', description: 'Close position within the recent high-low range.', requiredFields: ['high', 'low', 'close'], defaults: { period: 14, smoothK: 3, smoothD: 3 }, rules: { period: integer(), smoothK: integer(), smoothD: integer() }, outputs: [pane('percent_k', '%K', 'percent'), pane('percent_d', '%D', 'percent')], minimumHistory: 18, compute: indicatorLogic.stochasticOscillator }),
  define({ backlogId: 'MOM-003', id: 'stochastic-rsi', name: 'Stochastic RSI', ar: 'ستوكاستيك القوة النسبية', description: 'Stochastic normalization of RSI.', defaults: { rsiPeriod: 14, stochPeriod: 14, smoothK: 3, smoothD: 3 }, rules: { rsiPeriod: integer(), stochPeriod: integer(), smoothK: integer(), smoothD: integer() }, outputs: [pane('stoch_rsi_k', 'Stoch RSI K', 'percent'), pane('stoch_rsi_d', 'Stoch RSI D', 'percent')], minimumHistory: 31, compute: indicatorLogic.stochasticRsi }),
  define({ backlogId: 'MOM-004', id: 'commodity-channel-index', name: 'Commodity Channel Index (CCI)', ar: 'مؤشر قناة السلع', description: 'Typical-price distance from its mean, scaled by mean absolute deviation.', requiredFields: ['high', 'low', 'close'], defaults: { period: 20, constant: 0.015 }, rules: { period: integer(), constant: number(0.0001, 1) }, outputs: [pane('cci', 'CCI')], minimumHistory: 20, compute: indicatorLogic.commodityChannelIndex }),
  define({ backlogId: 'MOM-005', id: 'williams-percent-r', name: 'Williams Percent R', ar: 'مؤشر ويليامز النسبي', description: 'Close position in the recent range on a minus-100-to-zero scale.', requiredFields: ['high', 'low', 'close'], defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('williams_r', 'Williams %R', 'percent')], minimumHistory: 14, compute: indicatorLogic.williamsPercentR }),
  define({ backlogId: 'MOM-006', id: 'rate-of-change', name: 'Rate of Change (ROC)', ar: 'معدل التغير', description: 'Percentage price change from a selected number of bars earlier.', defaults: { period: 12 }, rules: { period: integer() }, outputs: [pane('roc_pct', 'ROC', 'percent')], minimumHistory: 13, compute: indicatorLogic.rateOfChange }),
  define({ backlogId: 'MOM-007', id: 'momentum', name: 'Momentum', ar: 'الزخم', description: 'Raw price difference from a selected number of bars earlier.', defaults: { period: 10 }, rules: { period: integer() }, outputs: [pane('momentum', 'Momentum', 'price')], minimumHistory: 11, compute: indicatorLogic.momentum }),
  define({ backlogId: 'MOM-008', id: 'chande-momentum-oscillator', name: 'Chande Momentum Oscillator (CMO)', ar: 'مذبذب زخم تشاند', description: 'Difference between rolling gains and losses divided by their sum.', defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('cmo', 'CMO', 'percent')], minimumHistory: 15, compute: indicatorLogic.chandeMomentumOscillator }),
  define({ backlogId: 'MOM-009', id: 'ultimate-oscillator', name: 'Ultimate Oscillator', ar: 'المذبذب النهائي', description: 'Weighted blend of buying pressure over three horizons.', requiredFields: ['high', 'low', 'close'], defaults: { short: 7, medium: 14, long: 28 }, rules: { short: integer(), medium: integer(), long: integer() }, outputs: [pane('ultimate_oscillator', 'Ultimate Oscillator', 'percent')], minimumHistory: 29, compute: indicatorLogic.ultimateOscillator }),
  define({ backlogId: 'MOM-010', id: 'true-strength-index', name: 'True Strength Index (TSI)', ar: 'مؤشر القوة الحقيقية', description: 'Double-smoothed momentum divided by double-smoothed absolute momentum.', defaults: { long: 25, short: 13, signal: 7 }, rules: { long: integer(), short: integer(), signal: integer() }, outputs: [pane('tsi', 'TSI', 'percent'), pane('signal', 'Signal', 'percent')], minimumHistory: 45, compute: indicatorLogic.trueStrengthIndex }),
  define({ backlogId: 'MOM-011', id: 'relative-vigor-index', name: 'Relative Vigor Index (RVI)', ar: 'مؤشر النشاط النسبي', description: 'Smoothed close-open strength divided by high-low range.', requiredFields: ['open', 'high', 'low', 'close'], defaults: { period: 10, signal: 4 }, rules: { period: integer(), signal: integer() }, outputs: [pane('rvi', 'RVI'), pane('signal', 'Signal')], minimumHistory: 13, compute: indicatorLogic.relativeVigorIndex }),
  define({ backlogId: 'MOM-012', id: 'connors-rsi', name: 'Connors RSI', ar: 'مؤشر كونرز للقوة النسبية', description: 'Average of short RSI, streak RSI, and one-bar return percentile rank.', defaults: { rsiPeriod: 3, streakPeriod: 2, rankPeriod: 100 }, rules: { rsiPeriod: integer(), streakPeriod: integer(), rankPeriod: integer() }, outputs: [pane('connors_rsi', 'Connors RSI', 'percent')], minimumHistory: 101, compute: indicatorLogic.connorsRsi }),
  define({ backlogId: 'MOM-013', id: 'laguerre-rsi', name: 'Laguerre RSI', ar: 'مؤشر لاجير للقوة النسبية', description: 'Four-stage Laguerre filter converted to a bounded oscillator.', defaults: { gamma: 0.7 }, rules: { gamma: number(0, 0.99) }, outputs: [pane('laguerre_rsi', 'Laguerre RSI', 'percent')], minimumHistory: 5, compute: indicatorLogic.laguerreRsi }),
  define({ backlogId: 'MOM-014', id: 'fisher-transform', name: 'Fisher Transform', ar: 'تحويل فيشر', description: 'Log transform of normalized median-price range position.', requiredFields: ['high', 'low'], defaults: { period: 10 }, rules: { period: integer(2) }, outputs: [pane('fisher', 'Fisher'), pane('trigger', 'Trigger')], minimumHistory: 11, compute: indicatorLogic.fisherTransform }),
  define({ backlogId: 'MOM-015', id: 'inverse-fisher-transform', name: 'Inverse Fisher Transform', ar: 'تحويل فيشر العكسي', description: 'Hyperbolic transform of smoothed RSI.', defaults: { rsiPeriod: 14, smoothing: 9 }, rules: { rsiPeriod: integer(), smoothing: integer() }, outputs: [pane('inverse_fisher', 'Inverse Fisher')], minimumHistory: 22, compute: indicatorLogic.inverseFisherTransform }),
  define({ backlogId: 'MOM-016', id: 'awesome-oscillator', name: 'Awesome Oscillator', ar: 'المذبذب الرائع', description: 'Fast minus slow simple average of median price.', requiredFields: ['high', 'low'], defaults: { fast: 5, slow: 34 }, rules: { fast: integer(), slow: integer() }, outputs: [pane('awesome', 'Awesome Oscillator', 'price')], minimumHistory: 34, compute: indicatorLogic.awesomeOscillator }),
  define({ backlogId: 'MOM-017', id: 'accelerator-oscillator', name: 'Accelerator Oscillator', ar: 'مذبذب التسارع', description: 'Awesome Oscillator minus its short moving average.', requiredFields: ['high', 'low'], defaults: { fast: 5, slow: 34, signal: 5 }, rules: { fast: integer(), slow: integer(), signal: integer() }, outputs: [pane('accelerator', 'Accelerator', 'price')], minimumHistory: 38, compute: indicatorLogic.acceleratorOscillator }),
  define({ backlogId: 'MOM-018', id: 'klinger-volume-oscillator', name: 'Klinger Volume Oscillator', ar: 'مذبذب حجم كلينجر', description: 'Fast-minus-slow EMA of signed volume force.', requiredFields: ['high', 'low', 'close', 'volume'], defaults: { fast: 34, slow: 55, signal: 13 }, rules: { fast: integer(), slow: integer(), signal: integer() }, outputs: [pane('kvo', 'KVO', 'volume'), pane('signal', 'Signal', 'volume')], minimumHistory: 67, compute: indicatorLogic.klingerVolumeOscillator }),
  define({ backlogId: 'MOM-019', id: 'know-sure-thing', name: 'Know Sure Thing (KST)', ar: 'مؤشر اليقين', description: 'Weighted blend of four smoothed rates of change.', defaults: { roc1: 10, roc2: 15, roc3: 20, roc4: 30, smooth1: 10, smooth2: 10, smooth3: 10, smooth4: 15, signal: 9 }, rules: { roc1: integer(), roc2: integer(), roc3: integer(), roc4: integer(), smooth1: integer(), smooth2: integer(), smooth3: integer(), smooth4: integer(), signal: integer() }, outputs: [pane('kst', 'KST', 'percent'), pane('signal', 'Signal', 'percent')], minimumHistory: 45, compute: indicatorLogic.knowSureThing }),
  define({ backlogId: 'MOM-020', id: 'coppock-curve', name: 'Coppock Curve', ar: 'منحنى كوبوك', description: 'Weighted moving average of two long-horizon rates of change.', defaults: { shortRoc: 11, longRoc: 14, wmaPeriod: 10 }, rules: { shortRoc: integer(), longRoc: integer(), wmaPeriod: integer() }, outputs: [pane('coppock', 'Coppock', 'percent')], minimumHistory: 24, compute: indicatorLogic.coppockCurve }),
  define({ backlogId: 'MOM-021', id: 'detrended-price-oscillator', name: 'Detrended Price Oscillator (DPO)', ar: 'مذبذب السعر منزوع الاتجاه', description: 'Shifted price minus its moving average.', defaults: { period: 20 }, rules: { period: integer(2) }, outputs: [pane('dpo', 'DPO', 'price')], minimumHistory: 32, compute: indicatorLogic.detrendedPriceOscillator }),
  define({ backlogId: 'MOM-022', id: 'elder-ray-index', name: 'Elder Ray Index', ar: 'مؤشر إلدر راي', description: 'Bull and bear power around an exponential average.', requiredFields: ['high', 'low', 'close'], defaults: { period: 13 }, rules: { period: integer() }, outputs: [pane('bull_power', 'Bull power', 'price'), pane('bear_power', 'Bear power', 'price')], minimumHistory: 13, compute: indicatorLogic.elderRayIndex }),
  define({ backlogId: 'MOM-023', id: 'balance-of-power', name: 'Balance of Power (BOP)', ar: 'توازن القوة', description: 'Candle body divided by candle range, optionally smoothed.', requiredFields: ['open', 'high', 'low', 'close'], defaults: { smoothing: 1 }, rules: { smoothing: integer() }, outputs: [pane('bop', 'BOP')], minimumHistory: 1, compute: indicatorLogic.balanceOfPower }),
  define({ backlogId: 'MOM-024', id: 'psychological-line', name: 'Psychological Line (PSY)', ar: 'الخط النفسي', description: 'Percentage of rising closes in a rolling window.', defaults: { period: 12 }, rules: { period: integer() }, outputs: [pane('psy_0_100', 'PSY', 'percent')], minimumHistory: 13, compute: indicatorLogic.psychologicalLine }),
  define({ backlogId: 'MOM-025', id: 'qstick', name: 'Qstick', ar: 'مؤشر كيوستيك', description: 'Moving average of candle bodies.', requiredFields: ['open', 'close'], defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('qstick', 'Qstick', 'price')], minimumHistory: 14, compute: indicatorLogic.qstick }),
  define({ backlogId: 'MOM-026', id: 'pretty-good-oscillator', name: 'Pretty Good Oscillator (PGO)', ar: 'المذبذب الجيد', description: 'Distance from a moving average measured in ATR units.', requiredFields: ['high', 'low', 'close'], defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('pgo', 'PGO')], minimumHistory: 14, compute: indicatorLogic.prettyGoodOscillator }),
  define({ backlogId: 'MOM-027', id: 'schaff-trend-cycle', name: 'Schaff Trend Cycle (STC)', ar: 'دورة اتجاه شاف', description: 'Double stochastic normalization of MACD.', defaults: { fast: 23, slow: 50, cycle: 10, smoothing: 3 }, rules: { fast: integer(), slow: integer(), cycle: integer(), smoothing: integer() }, outputs: [pane('stc', 'STC', 'percent')], minimumHistory: 62, compute: indicatorLogic.schaffTrendCycle }),
  define({ backlogId: 'MOM-028', id: 'smi-ergodic-indicator', name: 'SMI Ergodic Indicator', ar: 'مؤشر إس إم آي الإرجودي', description: 'Double-smoothed momentum ratio with signal line.', defaults: { long: 20, short: 5, signal: 5 }, rules: { long: integer(), short: integer(), signal: integer() }, outputs: [pane('smi', 'SMI', 'percent'), pane('signal', 'Signal', 'percent')], minimumHistory: 29, compute: indicatorLogic.smiErgodicIndicator }),
  define({ backlogId: 'MOM-029', id: 'stochastic-momentum-index', name: 'Stochastic Momentum Index (SMI)', ar: 'مؤشر الزخم العشوائي', description: 'Double-smoothed distance from the midpoint of a rolling range.', requiredFields: ['high', 'low', 'close'], defaults: { period: 14, smooth1: 3, smooth2: 3, signal: 3 }, rules: { period: integer(), smooth1: integer(), smooth2: integer(), signal: integer() }, outputs: [pane('smi', 'SMI', 'percent'), pane('signal', 'Signal', 'percent')], minimumHistory: 21, compute: indicatorLogic.stochasticMomentumIndex }),
  define({ backlogId: 'MOM-030', id: 'dynamic-momentum-index', name: 'Dynamic Momentum Index', ar: 'مؤشر الزخم الديناميكي', description: 'RSI whose lookback contracts as volatility rises.', defaults: { basePeriod: 14, volatilityPeriod: 10, minPeriod: 5, maxPeriod: 30 }, rules: { basePeriod: integer(), volatilityPeriod: integer(), minPeriod: integer(), maxPeriod: integer() }, outputs: [pane('dynamic_rsi', 'Dynamic RSI', 'percent'), pane('adaptive_period', 'Adaptive period', 'count')], minimumHistory: 31, compute: indicatorLogic.dynamicMomentumIndex }),
  define({ backlogId: 'MOM-031', id: 'relative-momentum-index', name: 'Relative Momentum Index (RMI)', ar: 'مؤشر الزخم النسبي', description: 'RSI-style ratio using multi-bar price changes.', defaults: { period: 14, momentum: 5 }, rules: { period: integer(), momentum: integer() }, outputs: [pane('rmi', 'RMI', 'percent')], minimumHistory: 20, compute: indicatorLogic.relativeMomentumIndex }),
  define({ backlogId: 'MOM-032', id: 'intraday-momentum-index', name: 'Intraday Momentum Index (IMI)', ar: 'مؤشر الزخم اليومي', description: 'RSI-style ratio of up and down candle bodies.', requiredFields: ['open', 'close'], defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('imi', 'IMI', 'percent')], minimumHistory: 14, compute: indicatorLogic.intradayMomentumIndex }),
  define({ backlogId: 'MOM-033', id: 'demarker-indicator', name: 'DeMarker Indicator', ar: 'مؤشر ديماركر', description: 'Ratio of recent high advances to high advances plus low declines.', requiredFields: ['high', 'low'], defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('demarker', 'DeMarker', 'percent')], minimumHistory: 15, compute: indicatorLogic.demarkerIndicator }),
  define({ backlogId: 'MOM-034', id: 'center-of-gravity-oscillator', name: 'Center of Gravity Oscillator', ar: 'مذبذب مركز الثقل', description: 'Weighted rolling price center expressed as a lead oscillator.', defaults: { period: 10, signal: 3 }, rules: { period: integer(), signal: integer() }, outputs: [pane('cog', 'COG'), pane('signal', 'Signal')], minimumHistory: 12, compute: indicatorLogic.centerOfGravityOscillator }),
  define({ backlogId: 'MOM-035', id: 'moving-average-oscillator', name: 'Moving Average Oscillator', ar: 'مذبذب المتوسط المتحرك', description: 'Percentage distance between fast and slow exponential averages.', defaults: { fast: 10, slow: 20 }, rules: { fast: integer(), slow: integer() }, outputs: [pane('mao', 'MAO', 'percent')], minimumHistory: 20, compute: indicatorLogic.movingAverageOscillator }),
  define({ backlogId: 'MOM-036', id: 'price-oscillator', name: 'Price Oscillator', ar: 'مذبذب السعر', description: 'Price-unit difference between fast and slow exponential averages.', defaults: { fast: 10, slow: 20 }, rules: { fast: integer(), slow: integer() }, outputs: [pane('oscillator', 'Price Oscillator', 'price')], minimumHistory: 20, compute: indicatorLogic.priceOscillator }),
  define({ backlogId: 'MOM-037', id: 'momentum-percentile-rank', name: 'Momentum percentile rank', ar: 'الرتبة المئوية للزخم', description: 'Current multi-bar momentum ranked within its own recent history.', defaults: { momentumPeriod: 10, rankPeriod: 100 }, rules: { momentumPeriod: integer(), rankPeriod: integer() }, outputs: [pane('percentile_0_100', 'Momentum percentile', 'rank')], minimumHistory: 110, compute: indicatorLogic.momentumPercentileRank }),
  define({ backlogId: 'MOM-038', id: 'rsi-divergence-detector', name: 'RSI divergence detector', ar: 'كاشف تباعد القوة النسبية', description: 'Confirmed pivot disagreement between price and RSI.', defaults: { rsiPeriod: 14, left: 5, right: 5 }, rules: { rsiPeriod: integer(), left: integer(), right: integer() }, outputs: [event('bullish', 'Bullish divergence'), event('bearish', 'Bearish divergence')], minimumHistory: 25, repaintBehavior: 'confirmed-with-delay', confirmationDelay: 5, compute: indicatorLogic.rsiDivergenceDetector }),
  define({ backlogId: 'MOM-039', id: 'macd-divergence-detector', name: 'MACD divergence detector', ar: 'كاشف تباعد الماكد', description: 'Confirmed pivot disagreement between price and MACD.', defaults: { fast: 12, slow: 26, left: 5, right: 5 }, rules: { fast: integer(), slow: integer(), left: integer(), right: integer() }, outputs: [event('bullish', 'Bullish divergence'), event('bearish', 'Bearish divergence')], minimumHistory: 36, repaintBehavior: 'confirmed-with-delay', confirmationDelay: 5, compute: indicatorLogic.macdDivergenceDetector }),
  define({ backlogId: 'MOM-040', id: 'multi-oscillator-consensus', name: 'Multi-oscillator consensus', ar: 'إجماع المذبذبات', description: 'Agreement score across RSI, stochastic, CCI, and rate of change.', requiredFields: ['high', 'low', 'close'], defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('score', 'Consensus score', 'count'), category('state', 'Consensus state')], minimumHistory: 20, compute: indicatorLogic.multiOscillatorConsensus }),
]);
