import { defineProgramCategory } from './define-category';

export const BREADTH_PROGRAM_ENTRIES = defineProgramCategory("breadth", [
  ["BRD-001", null, "Advance-Decline Line", "Cumulative number of advancing stocks minus declining stocks.", "AD line, daily net advances", "Market", "EGX universe, B", ["B"], "T1", "New", "unimplemented"],
  ["BRD-002", null, "Advance-Decline Ratio", "Advancers divided by decliners.", "AD ratio", "Market", "EGX universe, B", ["B"], "T1", "New", "unimplemented"],
  ["BRD-003", null, "Advance-Decline Percent", "Net advances as a percentage of active stocks.", "AD percent", "Market", "EGX universe, B", ["B"], "T1", "New", "unimplemented"],
  ["BRD-004", null, "Up-Down Volume", "Advancing volume versus declining volume.", "up volume, down volume, net volume", "Market", "EGX universe, BV", ["V", "B"], "T1", "New", "unimplemented"],
  ["BRD-005", null, "Up-Down Volume Ratio", "Advancing volume divided by declining volume.", "volume ratio", "Market", "EGX universe, BV", ["V", "B"], "T1", "New", "unimplemented"],
  ["BRD-006", null, "Arms Index (TRIN)", "Advance-decline ratio adjusted by up-down volume.", "TRIN", "Market", "EGX universe, BV", ["V", "B"], "T2", "New", "unimplemented"],
  ["BRD-007", null, "McClellan Oscillator", "Smoothed net advances showing breadth momentum.", "oscillator, fast, slow", "Pane", "EGX universe, B", ["B"], "T2", "New", "unimplemented"],
  ["BRD-008", null, "McClellan Summation Index", "Cumulative breadth trend from the McClellan Oscillator.", "summation_index", "Pane", "EGX universe, B", ["B"], "T2", "New", "unimplemented"],
  ["BRD-009", null, "New Highs-New Lows", "Difference between stocks making new highs and new lows.", "net highs, highs, lows, lookback", "Market", "EGX universe, B", ["B"], "T1", "New", "unimplemented"],
  ["BRD-010", null, "High-Low Logic Index", "Identifies unusual simultaneous new highs and lows.", "logic_index", "Market", "EGX universe, B", ["B"], "T3", "New", "unimplemented"],
  ["BRD-011", null, "Percent Above Moving Average", "Share of stocks above a chosen SMA or EMA.", "percent_above, period", "Market", "EGX universe, B", ["B"], "T1", "New", "unimplemented"],
  ["BRD-012", null, "Bullish Percent Index", "Share of stocks with bullish point-and-figure states.", "bullish_percent", "Market", "EGX universe, B", ["B"], "T3", "New", "unimplemented"],
  ["BRD-013", null, "Breadth Thrust", "Sudden shift from weak to broad participation.", "thrust_value, trigger event", "Pane", "EGX universe, B", ["B"], "T2", "New", "unimplemented"],
  ["BRD-014", null, "Zweig Breadth Thrust", "Ten-day smoothed advance ratio with classic thrust thresholds.", "ZBT, trigger", "Pane", "EGX universe, B", ["B"], "T2", "New", "unimplemented"],
  ["BRD-015", null, "Absolute Breadth Index", "Absolute difference between advancing and declining issues.", "ABI", "Market", "EGX universe, B", ["B"], "T2", "New", "unimplemented"],
  ["BRD-016", null, "Breadth Momentum", "Rate of change of advance-decline participation.", "breadth_roc, period", "Pane", "EGX universe, B", ["B"], "T2", "New", "unimplemented"],
  ["BRD-017", null, "Sector Breadth", "Participation measures calculated separately for each EGX sector.", "AD percent, percent above MA, highs-lows", "Market", "EGX sectors, B", ["B"], "T1", "New", "unimplemented"],
  ["BRD-018", null, "Index Participation Score", "Percentage of index members confirming the index direction.", "score_0_100, confirmed_count", "Market", "EGX index membership, B", ["B"], "T1", "New", "unimplemented"],
  ["BRD-019", null, "Equal-Weight versus Cap-Weight Spread", "Shows whether large stocks or the broader market lead.", "return_spread, trend", "Pane", "EGX universe, B", ["B"], "T2", "New", "unimplemented"],
  ["BRD-020", null, "Median Stock Return", "Typical constituent return, less distorted by the largest names.", "median_return, horizon", "Market", "EGX universe, B", ["B"], "T1", "New", "unimplemented"],
  ["BRD-021", null, "Cross-sectional dispersion", "Spread of constituent returns across the market.", "dispersion, percentile", "Market", "EGX universe, B", ["B"], "T2", "New", "unimplemented"],
  ["BRD-022", null, "Market Concentration", "Share of index move or market cap controlled by top constituents.", "top 5 and top 10 concentration, HHI", "Market", "EGX universe, B", ["B"], "T2", "Existing adjacent data", "unimplemented"],
  ["BRD-023", null, "Breadth Divergence", "Index makes a new high or low without matching breadth.", "bullish, bearish divergence", "Overlay", "EGX index and B", ["B"], "T2", "New", "unimplemented"],
  ["BRD-024", null, "Volume Breadth Divergence", "Index direction disagrees with up-down volume.", "bullish, bearish divergence", "Pane", "EGX universe, BV", ["V", "B"], "T2", "New", "unimplemented"],
  ["BRD-025", null, "Participation Regime", "Composite state from advances, volume, highs-lows, and MA breadth.", "broad bull, narrow bull, broad bear, narrow bear", "Market", "EGX universe, B", ["B"], "T2", "New composite", "unimplemented"],
], [
  "breadth-advance-decline-line",
  "breadth-advance-decline-ratio",
  "breadth-advance-decline-percent",
  "breadth-up-down-volume",
  "breadth-up-down-volume-ratio",
  "breadth-arms-index-trin",
  "breadth-mcclellan-oscillator",
  "breadth-mcclellan-summation-index",
  "breadth-new-highs-new-lows",
  "breadth-high-low-logic-index",
  "breadth-percent-above-moving-average",
  "breadth-bullish-percent-index",
  "breadth-breadth-thrust",
  "breadth-zweig-breadth-thrust",
  "breadth-absolute-breadth-index",
  "breadth-breadth-momentum",
  "breadth-sector-breadth",
  "breadth-index-participation-score",
  "breadth-equal-weight-versus-cap-weight-spread",
  "breadth-median-stock-return",
  "breadth-cross-sectional-dispersion",
  "breadth-market-concentration",
  "breadth-breadth-divergence",
  "breadth-volume-breadth-divergence",
  "breadth-participation-regime",
]);
