import { defineProgramCategory } from './define-category';

export const CYCLES_PROGRAM_ENTRIES = defineProgramCategory("cycles", [
  ["CYC-001", null, "Even Better Sinewave", "Ehlers cycle filter for low-lag turning points and cycle projection.", "wave, projected line, reversal events", "Pane or Overlay", "All, P", ["P"], "T0", "Existing chart", "unimplemented"],
  ["CYC-002", null, "Ehlers Sinewave", "Estimates cycle phase using dominant-cycle processing.", "sine, lead_sine, phase", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["CYC-003", null, "Hilbert Transform Dominant Cycle Period", "Estimates the market's current dominant cycle length.", "dominant_period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["CYC-004", null, "Hilbert Transform Trend Mode", "Distinguishes cycle mode from trend mode.", "trend_mode, cycle_mode", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["CYC-005", null, "MESA Adaptive Moving Average (MAMA)", "Adaptive average driven by estimated market phase.", "mama, fama, cross events", "Overlay", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["CYC-006", null, "Cyber Cycle", "Recursive cycle oscillator designed by John Ehlers.", "cycle, trigger, period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["CYC-007", null, "Roofing Filter", "Removes long trends and high-frequency noise to isolate tradable cycles.", "filtered_series, high-pass, low-pass periods", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["CYC-008", null, "Super Smoother Filter", "Low-lag digital low-pass filter.", "smoothed_series, period, poles", "Overlay", "All, P", ["P"], "T2", "New primitive", "unimplemented"],
  ["CYC-009", null, "Two-pole High-Pass Filter", "Removes slow trend components from price.", "high_pass, period", "Pane", "All, P", ["P"], "T3", "New primitive", "unimplemented"],
  ["CYC-010", null, "Band-Pass Filter", "Isolates movement near a selected cycle period.", "band_pass, trigger, period, bandwidth", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["CYC-011", null, "Decycler", "Removes shorter cycles to expose underlying trend.", "decycler, period", "Overlay", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["CYC-012", null, "Decycler Oscillator", "Difference between price and its decycled trend.", "oscillator, period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["CYC-013", null, "Instantaneous Trendline", "Low-lag Ehlers trendline estimate.", "itrend, trigger", "Overlay", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["CYC-014", null, "Autocorrelation Periodogram", "Estimates dominant cycles through rolling autocorrelation power.", "power spectrum, dominant_period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["CYC-015", null, "Fourier dominant cycle", "Estimates strongest periodic components with a rolling Fourier transform.", "dominant periods, amplitudes, phases", "Pane", "All, P", ["P"], "R", "Research", "unimplemented"],
  ["CYC-016", null, "Goertzel Cycle Detector", "Efficiently measures power at selected cycle frequencies.", "power by period, dominant period", "Pane", "All, P", ["P"], "R", "Research", "unimplemented"],
  ["CYC-017", null, "Wavelet energy", "Separates short, medium, and long horizon movement.", "scale energies, dominant scale", "Pane", "All, P", ["P"], "R", "Research", "unimplemented"],
  ["CYC-018", null, "Hodrick-Prescott trend and cycle", "Separates smooth trend from cyclical deviation.", "trend, cycle, lambda", "Pane", "All, P", ["P"], "R", "Research, endpoint sensitivity", "unimplemented"],
  ["CYC-019", null, "Baxter-King cycle filter", "Band-pass economic cycle filter.", "cycle_component, periods", "Pane", "Long macro series, M", ["M"], "R", "Research", "unimplemented"],
  ["CYC-020", null, "Christiano-Fitzgerald filter", "Flexible band-pass filter for trend-cycle separation.", "trend, cycle, periods", "Pane", "Long macro series, M", ["M"], "R", "Research", "unimplemented"],
  ["CYC-021", null, "Seasonal return profile", "Average return by weekday, month, or trading-session segment.", "seasonal_mean, win_rate, sample_count", "Market", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["CYC-022", null, "Ramadan and holiday seasonality", "Egyptian-market return and volume behavior around local calendar events.", "average return, volume ratio, sample count", "Market", "EGX, calendar and P", ["P"], "R", "Research", "unimplemented"],
  ["CYC-023", null, "Cycle phase state", "Converts a cycle oscillator into rising, peak, falling, and trough states.", "phase_state, phase_angle", "Pane", "All, P", ["P"], "T2", "New primitive", "unimplemented"],
  ["CYC-024", null, "Filter bank consensus", "Agreement across several cycle periods or digital filters.", "score, dominant horizon, state", "Pane", "All, P", ["P"], "R", "Research composite", "unimplemented"],
], [
  "even-better-sinewave",
  "ehlers-sinewave",
  "hilbert-transform-dominant-cycle-period",
  "hilbert-transform-trend-mode",
  "mesa-adaptive-moving-average",
  "cyber-cycle",
  "roofing-filter",
  "super-smoother-filter",
  "two-pole-high-pass-filter",
  "band-pass-filter",
  "decycler",
  "decycler-oscillator",
  "instantaneous-trendline",
  "autocorrelation-periodogram",
  "fourier-dominant-cycle",
  "goertzel-cycle-detector",
  "wavelet-energy",
  "hodrick-prescott-trend-cycle",
  "baxter-king-cycle-filter",
  "christiano-fitzgerald-filter",
  "seasonal-return-profile",
  "ramadan-holiday-seasonality",
  "cycle-phase-state",
  "filter-bank-consensus",
]);
