import { defineProgramCategory } from './define-category';

export const EGYPT_PROGRAM_ENTRIES = defineProgramCategory("egypt", [
  ["EGY-001", null, "EGX30 Return and Trend", "Performance and technical state of Egypt's large-cap benchmark.", "return, trend, volatility, drawdown", "Market", "EGX30, P", ["P"], "T1", "Existing adjacent data", "unimplemented"],
  ["EGY-002", null, "EGX70 Return and Trend", "Performance and technical state of the smaller-company benchmark.", "return, trend, volatility, drawdown", "Market", "EGX70, P", ["P"], "T1", "Existing adjacent data", "unimplemented"],
  ["EGY-003", null, "EGX100 Return and Trend", "Broad benchmark performance and state.", "return, trend, volatility, drawdown", "Market", "EGX100, P", ["P"], "T1", "Existing adjacent data", "unimplemented"],
  ["EGY-004", null, "EGX Index Breadth", "Participation of constituents behind each EGX index move.", "AD percent, percent above MA, highs-lows", "Market", "Index membership, B", ["B"], "T1", "New", "unimplemented"],
  ["EGY-005", null, "Egyptian Investor Net Flow", "Net buying or selling by Egyptian investors.", "daily and cumulative net flow", "Market", "EGX investor flows, M", ["M"], "T0", "Existing adjacent feature", "unimplemented"],
  ["EGY-006", null, "Arab Investor Net Flow", "Net buying or selling by Arab investors.", "daily and cumulative net flow", "Market", "EGX investor flows, M", ["M"], "T0", "Existing adjacent feature", "unimplemented"],
  ["EGY-007", null, "Foreign Investor Net Flow", "Net buying or selling by non-Arab foreign investors.", "daily and cumulative net flow", "Market", "EGX investor flows, M", ["M"], "T0", "Existing adjacent feature", "unimplemented"],
  ["EGY-008", null, "Institutional versus Retail Flow", "Net participation split by investor type.", "institutional and retail net flow", "Market", "EGX investor flows, M", ["M"], "T2", "Data-gated", "unimplemented"],
  ["EGY-009", null, "Investor Flow Z-score", "Whether current investor flows are unusually large.", "z-score, percentile, period", "Pane", "EGX flow history, M", ["M"], "T1", "New", "unimplemented"],
  ["EGY-010", null, "Flow Trend and Persistence", "Whether a participant group has accumulated or sold for several sessions.", "rolling sum, streak, trend", "Pane", "EGX flow history, M", ["M"], "T1", "New", "unimplemented"],
  ["EGY-011", null, "Flow-Price Divergence", "Index rises during foreign selling or falls during accumulation.", "divergence state, strength", "Pane", "EGX index and flows, M", ["M"], "T2", "New", "unimplemented"],
  ["EGY-012", null, "Sector Rotation Score", "Relative momentum, breadth, flow, and volatility by EGX sector.", "score, rank, quadrant", "Market", "EGX sectors, B and M", ["B", "M"], "T1", "Existing adjacent feature", "unimplemented"],
  ["EGY-013", null, "Industry Group Rotation", "Same rotation framework at the industry-group level.", "score, rank, quadrant", "Market", "EGX taxonomy, B", ["B"], "T2", "Existing adjacent data", "unimplemented"],
  ["EGY-014", null, "Sector Concentration Risk", "Dependence of a sector move on its largest constituents.", "concentration, contribution, breadth gap", "Market", "EGX sectors, B", ["B"], "T1", "Existing adjacent feature", "unimplemented"],
  ["EGY-015", null, "EGX Market Heat Score", "Composite of breadth, volume, volatility, momentum, and flows.", "score_0_100, regime", "Market", "EGX universe, BVM", ["V", "B", "M"], "T2", "New composite", "unimplemented"],
  ["EGY-016", null, "Official USD/EGP Trend", "Trend, momentum, and volatility of the official exchange rate.", "rate, return, trend, volatility", "Market", "FX, M", ["M"], "T1", "Existing adjacent data", "unimplemented"],
  ["EGY-017", null, "Real USD/EGP Fair Value", "Model-derived purchasing-power or macro fair-value estimate.", "fair value, misvaluation_pct, confidence", "Market", "FX and macro, M", ["M"], "T0", "Existing adjacent feature", "unimplemented"],
  ["EGY-018", null, "FX Devaluation Risk", "Composite probability or risk state from FX, reserves, inflation, rates, and liquidity.", "risk score, state, drivers", "Market", "Macro, M", ["M"], "T0", "Existing adjacent feature", "unimplemented"],
  ["EGY-019", null, "Parallel-Market FX Premium", "Difference between official and verifiable alternative FX prices.", "premium_pct, trend", "Market", "Licensed or verified FX data, M", ["M"], "R", "Data and compliance gated", "unimplemented"],
  ["EGY-020", null, "ADR-Implied USD/EGP", "FX rate implied by Egyptian local shares and corresponding overseas receipts.", "implied FX, premium, stale-data flag", "Market", "ADR pairs and FX, BM", ["BM"], "R", "Data-gated", "unimplemented"],
  ["EGY-021", null, "Gold in EGP per Gram", "International gold translated through USD/EGP into local units.", "EGP per gram, return, premium", "Market", "Gold and FX, BM", ["BM"], "T1", "Existing adjacent data", "unimplemented"],
  ["EGY-022", null, "Silver in EGP per Gram", "International silver translated through USD/EGP into local units.", "EGP per gram, return, premium", "Market", "Silver and FX, BM", ["BM"], "T1", "Existing adjacent data", "unimplemented"],
  ["EGY-023", null, "Local Gold Premium", "Local retail bullion price versus international implied EGP value.", "premium_pct, spread", "Market", "Verified local gold quotes, M", ["M"], "R", "Data-gated", "unimplemented"],
  ["EGY-024", null, "Gold versus EGP Hedge Effectiveness", "How well local gold has offset currency weakness or inflation.", "correlation, hedge ratio, real return", "Pane", "Gold, FX, inflation, BM", ["BM"], "T2", "New", "unimplemented"],
  ["EGY-025", null, "CBE Policy Rate", "Current rate, direction, and real rate after inflation.", "nominal rate, real rate, change", "Market", "CBE and CPI, M", ["M"], "T1", "Existing adjacent data", "unimplemented"],
  ["EGY-026", null, "Yield Curve Slope", "Difference between long- and short-term Egyptian government yields.", "spreads, inversion state", "Market", "Treasury yields, M", ["M"], "R", "Data-gated", "unimplemented"],
  ["EGY-027", null, "Inflation Momentum", "Change in monthly, annual, and annualized short-run Egyptian inflation.", "CPI momentum, acceleration", "Market", "CAPMAS or CBE CPI, M", ["M"], "T1", "Existing adjacent data", "unimplemented"],
  ["EGY-028", null, "Real Equity Return", "EGX return after Egyptian inflation.", "real return, real drawdown", "Pane", "EGX and CPI, M", ["M"], "T1", "New", "unimplemented"],
  ["EGY-029", null, "M2 Liquidity Growth", "Growth and acceleration of Egyptian broad money.", "YoY, MoM, acceleration", "Market", "Money supply, M", ["M"], "T0", "Existing adjacent feature", "unimplemented"],
  ["EGY-030", null, "Liquidity versus EGX Divergence", "Difference between money growth and equity-market performance.", "divergence, rolling beta", "Pane", "M2 and EGX, M", ["M"], "T2", "New", "unimplemented"],
  ["EGY-031", null, "Fund Discount or Premium", "Fund market price versus reported NAV where both exist.", "premium_discount_pct, z-score", "Pane", "Listed funds and NAV", [], "T2", "Data-gated", "unimplemented"],
  ["EGY-032", null, "Fund Tracking Difference", "Fund return minus its benchmark return.", "active return, tracking error", "Card", "Funds and BM", ["BM"], "T2", "New", "unimplemented"],
  ["EGY-033", null, "EGX Trading Activity Pulse", "Composite of turnover, trades count, active tickers, and volume breadth.", "pulse_0_100, state", "Market", "EGX trade statistics, BVT", ["V", "T", "B"], "T2", "New composite", "unimplemented"],
  ["EGY-034", null, "Suspension and Staleness Flag", "Warns when an asset has missing sessions, stale NAV, or suspended trading.", "stale, missing bars, last valid date", "Card", "All local assets, P", ["P"], "T1", "New data-quality primitive", "unimplemented"],
  ["EGY-035", null, "Corporate Action Integrity Flag", "Identifies price discontinuities that may require split or dividend adjustment.", "suspected event, adjusted state", "Card", "EGX equities, P and FND", ["P", "FND"], "T1", "Existing adjacent integrity logic", "unimplemented"],
  ["EGY-036", null, "EGP Purchasing Power Index", "Indexed value of one EGP after cumulative inflation.", "purchasing_power, loss_pct", "Market", "CPI, M", ["M"], "T2", "New", "unimplemented"],
], [
  "egypt-egx30-return-trend",
  "egypt-egx70-return-trend",
  "egypt-egx100-return-trend",
  "egypt-egx-index-breadth",
  "egypt-egyptian-investor-net-flow",
  "egypt-arab-investor-net-flow",
  "egypt-foreign-investor-net-flow",
  "egypt-institutional-versus-retail-flow",
  "egypt-investor-flow-z-score",
  "egypt-flow-trend-and-persistence",
  "egypt-flow-price-divergence",
  "egypt-sector-rotation-score",
  "egypt-industry-group-rotation",
  "egypt-sector-concentration-risk",
  "egypt-egx-market-heat-score",
  "egypt-official-usd-egp-trend",
  "egypt-real-usd-egp-fair-value",
  "egypt-fx-devaluation-risk",
  "egypt-parallel-market-fx-premium",
  "egypt-adr-implied-usd-egp",
  "egypt-gold-in-egp-per-gram",
  "egypt-silver-in-egp-per-gram",
  "egypt-local-gold-premium",
  "egypt-gold-versus-egp-hedge-effectiveness",
  "egypt-cbe-policy-rate",
  "egypt-yield-curve-slope",
  "egypt-inflation-momentum",
  "egypt-real-equity-return",
  "egypt-m2-liquidity-growth",
  "egypt-liquidity-versus-egx-divergence",
  "egypt-fund-discount-or-premium",
  "egypt-fund-tracking-difference",
  "egypt-egx-trading-activity-pulse",
  "egypt-suspension-staleness-flag",
  "egypt-corporate-action-integrity-flag",
  "egypt-egp-purchasing-power-index",
]);
