import { defineProgramCategory } from './define-category';

export const MARKET_STRUCTURE_PROGRAM_ENTRIES = defineProgramCategory("market-structure", [
  ["STR-001", null, "Confirmed pivot highs and lows", "Local turning points confirmed after bars appear on both sides.", "pivot_high, pivot_low, left, right", "Overlay", "All, P", ["P"], "T1", "New primitive, delayed", "unimplemented"],
  ["STR-002", null, "Swing Mapper", "Maps directional swings using an adaptive range threshold.", "swing_high, swing_low, direction", "Overlay", "All, P", ["P"], "T0", "Existing chart", "unimplemented"],
  ["STR-003", null, "Zig Zag", "Filters price moves smaller than a chosen percentage or ATR threshold.", "pivots, legs, change_pct", "Overlay", "All, P", ["P"], "T1", "New, repaint-aware", "unimplemented"],
  ["STR-004", null, "Ticknal Support and Resistance", "Adaptive step channels, clustered zones, and trendline channels.", "levels, zones, trend lines", "Overlay", "All, P", ["P"], "T0", "Existing chart", "unimplemented"],
  ["STR-005", null, "Classic Pivot Points", "Previous-period support and resistance from high, low, and close.", "pivot, S1–S5, R1–R5", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["STR-006", null, "Fibonacci Pivot Points", "Pivot levels using Fibonacci ratios.", "pivot, Fibonacci supports and resistances", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["STR-007", null, "Camarilla Pivot Points", "Close-focused intraday support and resistance levels.", "H1–H6, L1–L6", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["STR-008", null, "Woodie Pivot Points", "Pivot system giving extra weight to the current open.", "pivot, supports, resistances", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["STR-009", null, "DeMark Pivot Points", "Conditional pivot calculation based on open-close relationship.", "pivot, support, resistance", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["STR-010", null, "Fibonacci Retracement", "Retracement levels between two selected or confirmed swing points.", "levels 23.6–78.6, anchors", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["STR-011", null, "Fibonacci Extension", "Potential targets beyond a completed swing.", "levels 127.2, 161.8, 261.8", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["STR-012", null, "Auto Fibonacci", "Automatically anchors Fibonacci levels to confirmed swings.", "levels, selected anchors", "Overlay", "All, P", ["P"], "T2", "New, confirmed delay", "unimplemented"],
  ["STR-013", null, "Rolling support and resistance", "Highest and lowest prices over a rolling window.", "support, resistance, midpoint", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["STR-014", null, "Touch-count price zones", "Clusters levels that price repeatedly tested.", "zone center, width, touches, strength", "Overlay", "All, P", ["P"], "T2", "Existing component", "unimplemented"],
  ["STR-015", null, "ATR support and resistance zones", "Expands levels into zones using volatility.", "upper and lower zone bounds, multiplier", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["STR-016", null, "Trendlines from pivots", "Connects confirmed higher lows or lower highs.", "upper and lower trendlines, slope", "Overlay", "All, P", ["P"], "T2", "Existing component", "unimplemented"],
  ["STR-017", null, "Linear Regression Channel", "Trend line with statistical deviation bands.", "regression, upper, lower, slope, R squared", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["STR-018", null, "Raff Regression Channel", "Regression trend with bands set by maximum deviation.", "center, upper, lower", "Overlay", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["STR-019", null, "Andrews Pitchfork", "Median-line structure from three confirmed pivots.", "median and parallel lines", "Overlay", "All, P", ["P"], "T3", "New, anchor dependent", "unimplemented"],
  ["STR-020", null, "Break of Structure (BOS)", "Price breaks a previous confirmed swing high or low.", "bullish_bos, bearish_bos, level", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["STR-021", null, "Change of Character (CHoCH)", "First structural break against the existing swing direction.", "bullish_choch, bearish_choch", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["STR-022", null, "Higher-high and higher-low state", "Labels bullish, bearish, or mixed swing sequences.", "HH, HL, LH, LL, trend_state", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["STR-023", null, "Consolidation range", "Detects tight price ranges lasting a minimum number of bars.", "upper, lower, duration, width", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["STR-024", null, "Range breakout", "Event when price closes outside a confirmed consolidation.", "breakout_up, breakout_down, level", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["STR-025", null, "Opening range", "High and low of the first selected minutes or bars.", "OR high, OR low, breakout", "Overlay", "Intraday, P", ["P"], "T2", "New", "unimplemented"],
  ["STR-026", null, "Previous period levels", "Previous day, week, month, or year OHLC levels.", "prior OHLC levels", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["STR-027", null, "All-time and 52-week levels", "Distance to major long-term highs and lows.", "high, low, distance_pct", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["STR-028", null, "Fair Value Gap", "Three-candle price imbalance zone.", "bullish and bearish zones, fill state", "Overlay", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["STR-029", null, "Price gap zones", "Untraded areas between one bar's range and the next.", "gap bounds, fill_pct, state", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["STR-030", null, "Supply and demand zones", "Impulsive departures from compact bases, scored by freshness and reaction.", "zones, direction, strength", "Overlay", "All, P", ["P"], "T3", "Research", "unimplemented"],
  ["STR-031", null, "Order block heuristic", "Last opposing candle before a structural impulse.", "zone, direction, invalidation", "Overlay", "All, P", ["P"], "R", "Research, subjective definition", "unimplemented"],
  ["STR-032", null, "Market structure score", "Combines swing direction, breaks, distance from levels, and range state.", "score, bullish, bearish, neutral", "Pane", "All, P", ["P"], "T2", "New composite", "unimplemented"],
], [
  "confirmed-pivot-highs-lows",
  "swing-mapper",
  "zig-zag",
  "ticknal-support-resistance",
  "classic-pivot-points",
  "fibonacci-pivot-points",
  "camarilla-pivot-points",
  "woodie-pivot-points",
  "demark-pivot-points",
  "fibonacci-retracement",
  "fibonacci-extension",
  "auto-fibonacci",
  "rolling-support-resistance",
  "touch-count-price-zones",
  "atr-support-resistance-zones",
  "trendlines-from-pivots",
  "linear-regression-channel",
  "raff-regression-channel",
  "andrews-pitchfork",
  "break-of-structure",
  "change-of-character",
  "higher-high-higher-low-state",
  "consolidation-range",
  "range-breakout",
  "opening-range",
  "previous-period-levels",
  "all-time-52-week-levels",
  "fair-value-gap",
  "price-gap-zones",
  "supply-demand-zones",
  "order-block-heuristic",
  "market-structure-score",
]);
