import { defineProgramCategory } from './define-category';

export const MOMENTUM_PROGRAM_ENTRIES = defineProgramCategory("momentum", [
  ["MOM-001", null, "Relative Strength Index (RSI)", "Measures recent gains versus losses on a 0–100 scale.", "rsi, period, zones", "Pane", "All, P", ["P"], "T1", "Internal only", "unimplemented"],
  ["MOM-002", null, "Stochastic Oscillator", "Compares close to the recent high-low range.", "percent_k, percent_d, period, smoothing", "Pane", "All, P", ["P"], "T1", "Internal only", "unimplemented"],
  ["MOM-003", null, "Stochastic RSI", "Applies stochastic normalization to RSI for faster signals.", "stoch_rsi_k, stoch_rsi_d, periods", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["MOM-004", null, "Commodity Channel Index (CCI)", "Measures distance from a statistical mean.", "cci, period, constant", "Pane", "All, P", ["P"], "T1", "Internal only", "unimplemented"],
  ["MOM-005", null, "Williams Percent R", "Shows where close sits in the recent range on a -100 to 0 scale.", "williams_r, period", "Pane", "All, P", ["P"], "T1", "Internal only", "unimplemented"],
  ["MOM-006", null, "Rate of Change (ROC)", "Percentage price change over a selected number of bars.", "roc_pct, period", "Pane", "All, P", ["P"], "T1", "Internal only", "unimplemented"],
  ["MOM-007", null, "Momentum", "Raw price difference from N bars ago.", "momentum, period", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["MOM-008", null, "Chande Momentum Oscillator (CMO)", "Balanced sum of gains and losses on a -100 to 100 scale.", "cmo, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-009", null, "Ultimate Oscillator", "Blends short, medium, and long momentum to reduce false divergences.", "uo, periods 7, 14, 28, weights", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-010", null, "True Strength Index (TSI)", "Double-smoothed price momentum with a signal line.", "tsi, signal, long, short, signal period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-011", null, "Relative Vigor Index (RVI)", "Compares close-open strength to high-low range.", "rvi, signal, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-012", null, "Connors RSI", "Combines short RSI, streak length, and percentile rank.", "crsi, rsi period, streak period, rank period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-013", null, "Laguerre RSI", "Low-lag filtered RSI designed to react smoothly.", "laguerre_rsi, gamma", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["MOM-014", null, "Fisher Transform", "Converts range position into a near-normal oscillator that highlights turning points.", "fisher, trigger, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-015", null, "Inverse Fisher Transform", "Compresses an oscillator into a bounded, fast-switching signal.", "inverse_fisher, source, smoothing", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["MOM-016", null, "Awesome Oscillator", "Fast versus slow median-price momentum.", "ao, fast, slow", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["MOM-017", null, "Accelerator Oscillator", "Change in Awesome Oscillator momentum.", "ac", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-018", null, "Klinger Volume Oscillator", "Combines price trend and volume force.", "kvo, signal, fast, slow", "Pane", "All with V", ["V"], "T2", "New", "unimplemented"],
  ["MOM-019", null, "Know Sure Thing (KST)", "Weighted blend of multiple smoothed rates of change.", "kst, signal, four ROC periods", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-020", null, "Coppock Curve", "Long-term momentum curve traditionally used for major bottoms.", "coppock, ROC periods, WMA period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-021", null, "Detrended Price Oscillator (DPO)", "Removes trend to make shorter cycles easier to see.", "dpo, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-022", null, "Elder Ray Index", "Bull and bear power around an EMA.", "bull_power, bear_power, ema period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-023", null, "Balance of Power (BOP)", "Measures buyer versus seller control within each candle.", "bop, smoothing", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["MOM-024", null, "Psychological Line (PSY)", "Percentage of rising closes in a lookback window.", "psy_0_100, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-025", null, "Qstick", "Moving average of candle bodies to estimate buying or selling pressure.", "qstick, period, average type", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-026", null, "Pretty Good Oscillator (PGO)", "Distance from an SMA measured in ATR units.", "pgo, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-027", null, "Schaff Trend Cycle (STC)", "Applies stochastic cycling to MACD for quicker trend changes.", "stc, fast, slow, cycle, smoothing", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-028", null, "SMI Ergodic Indicator", "Smoothed momentum oscillator with a signal line.", "smi, signal, long, short, signal", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-029", null, "Stochastic Momentum Index (SMI)", "Measures close relative to the midpoint of the recent range.", "smi, signal, periods", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-030", null, "Dynamic Momentum Index", "RSI whose period adapts to volatility.", "dmi_oscillator, min and max periods", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["MOM-031", null, "Relative Momentum Index (RMI)", "RSI-style momentum using multi-bar changes.", "rmi, length, momentum lookback", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-032", null, "Intraday Momentum Index (IMI)", "RSI-style comparison of up and down candle bodies.", "imi, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-033", null, "DeMarker Indicator", "Compares recent highs and lows to estimate exhaustion.", "demarker, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["MOM-034", null, "Center of Gravity Oscillator", "Low-lag oscillator for possible turning points.", "cog, signal, period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["MOM-035", null, "Moving Average Oscillator", "Difference or percentage distance between two averages.", "mao, fast, slow, average type", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["MOM-036", null, "Price Oscillator", "Fast versus slow price average in price units.", "oscillator, fast, slow", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["MOM-037", null, "Momentum percentile rank", "Current momentum relative to its own recent history.", "percentile_0_100, momentum period, rank period", "Pane", "All, P", ["P"], "T2", "New primitive", "unimplemented"],
  ["MOM-038", null, "RSI divergence detector", "Flags price and RSI moving in opposite directions between confirmed pivots.", "bullish, bearish, pivot windows", "Overlay", "All, P", ["P"], "T2", "New, confirmed delay", "unimplemented"],
  ["MOM-039", null, "MACD divergence detector", "Flags price and MACD disagreement between confirmed pivots.", "bullish, bearish, pivot windows", "Overlay", "All, P", ["P"], "T2", "New, confirmed delay", "unimplemented"],
  ["MOM-040", null, "Multi-oscillator consensus", "Counts bullish, bearish, overbought, and oversold agreement.", "score, state, selected oscillators", "Pane", "All, P", ["P"], "T2", "New composite", "unimplemented"],
], [
  "relative-strength-index",
  "stochastic-oscillator",
  "stochastic-rsi",
  "commodity-channel-index",
  "williams-percent-r",
  "rate-of-change",
  "momentum",
  "chande-momentum-oscillator",
  "ultimate-oscillator",
  "true-strength-index",
  "relative-vigor-index",
  "connors-rsi",
  "laguerre-rsi",
  "fisher-transform",
  "inverse-fisher-transform",
  "awesome-oscillator",
  "accelerator-oscillator",
  "klinger-volume-oscillator",
  "know-sure-thing",
  "coppock-curve",
  "detrended-price-oscillator",
  "elder-ray-index",
  "balance-of-power",
  "psychological-line",
  "qstick",
  "pretty-good-oscillator",
  "schaff-trend-cycle",
  "smi-ergodic-indicator",
  "stochastic-momentum-index",
  "dynamic-momentum-index",
  "relative-momentum-index",
  "intraday-momentum-index",
  "demarker-indicator",
  "center-of-gravity-oscillator",
  "moving-average-oscillator",
  "price-oscillator",
  "momentum-percentile-rank",
  "rsi-divergence-detector",
  "macd-divergence-detector",
  "multi-oscillator-consensus",
]);
