import { defineProgramCategory } from './define-category';

export const PRICE_ACTION_PROGRAM_ENTRIES = defineProgramCategory("price-action", [
  ["PAT-001", null, "Candle Anatomy", "Body, upper wick, lower wick, and range proportions.", "body_pct, wick ratios, direction", "Pane", "All, P", ["P"], "T1", "New primitive", "unimplemented"],
  ["PAT-002", null, "Doji family", "Candle with a very small body relative to its range.", "doji, long-legged, dragonfly, gravestone", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["PAT-003", null, "Hammer and Hanging Man", "Small body with a long lower wick, interpreted using context.", "hammer, hanging_man", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["PAT-004", null, "Inverted Hammer and Shooting Star", "Small body with a long upper wick, interpreted using context.", "inverted_hammer, shooting_star", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["PAT-005", null, "Bullish and Bearish Engulfing", "Current body fully covers the previous opposing body.", "bullish, bearish event", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["PAT-006", null, "Harami", "Small body contained inside the previous large body.", "bullish, bearish event", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["PAT-007", null, "Piercing Line and Dark Cloud Cover", "Two-candle reversal patterns with deep body penetration.", "bullish, bearish event, penetration", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["PAT-008", null, "Morning and Evening Star", "Three-candle potential reversal sequence.", "bullish, bearish event", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["PAT-009", null, "Three White Soldiers and Three Black Crows", "Three strong consecutive directional candles.", "bullish, bearish event", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["PAT-010", null, "Marubozu", "Candle dominated by its body with little or no wick.", "bullish, bearish, tolerance", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["PAT-011", null, "Inside Bar", "Current high-low range sits inside the previous bar.", "inside_bar, mother range", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["PAT-012", null, "Outside Bar", "Current range exceeds the previous bar on both sides.", "outside_bar, direction", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["PAT-013", null, "Pin Bar", "Long rejection wick relative to body and opposite wick.", "bullish, bearish, ratios", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["PAT-014", null, "Tweezer Top and Bottom", "Consecutive bars with approximately equal highs or lows.", "top, bottom, tolerance", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["PAT-015", null, "Gap Up and Gap Down", "Current range opens or remains beyond the previous range.", "full_gap, partial_gap, direction", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["PAT-016", null, "NR4 and NR7", "Narrowest range in four or seven bars.", "NR4, NR7", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["PAT-017", null, "Wide Range Bar", "Bar range unusually large versus recent history.", "event, range ratio, percentile", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["PAT-018", null, "Climax Volume Candle", "Wide candle with extreme relative volume.", "bullish, bearish, exhaustion candidate", "Overlay", "Assets with V", ["V"], "T2", "New", "unimplemented"],
  ["PAT-019", null, "Reversal Candle Score", "Continuous score from body, wick, gap, volume, and context.", "score -100 to 100, components", "Pane", "Assets with V", ["V"], "T2", "New composite", "unimplemented"],
  ["PAT-020", null, "Multi-candle Pattern Filter", "Generic sequence rule over candle anatomy rather than named patterns.", "sequence match, parameters", "Overlay", "All, P", ["P"], "T2", "New builder primitive", "unimplemented"],
], [
  "candle-anatomy",
  "doji-family",
  "hammer-hanging-man",
  "inverted-hammer-shooting-star",
  "bullish-bearish-engulfing",
  "harami",
  "piercing-dark-cloud",
  "morning-evening-star",
  "three-soldiers-crows",
  "marubozu",
  "inside-bar",
  "outside-bar",
  "pin-bar",
  "tweezer-top-bottom",
  "gap-up-down",
  "nr4-nr7",
  "wide-range-bar",
  "climax-volume-candle",
  "reversal-candle-score",
  "multi-candle-pattern-filter",
]);
