import { defineProgramCategory } from './define-category';

export const QUANTITATIVE_PROGRAM_ENTRIES = defineProgramCategory("quantitative", [
  ["QNT-001", null, "Z-score", "Number of standard deviations a value is from its rolling mean.", "z_score, period, source", "Pane", "All, P", ["P"], "T1", "New primitive", "unimplemented"],
  ["QNT-002", null, "Rolling mean and variance", "Local average and dispersion used by many quantitative rules.", "mean, variance, period", "Pane", "All, P", ["P"], "T1", "New primitive", "unimplemented"],
  ["QNT-003", null, "Rolling median and MAD", "Robust center and dispersion less affected by outliers.", "median, MAD, robust_z, period", "Pane", "All, P", ["P"], "T2", "Internal component", "unimplemented"],
  ["QNT-004", null, "Percentile rank", "Position of a value inside its own rolling history.", "percentile_0_100, period", "Pane", "All, P", ["P"], "T1", "New primitive", "unimplemented"],
  ["QNT-005", null, "Rolling skewness", "Whether return distribution has a longer upside or downside tail.", "skewness, period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["QNT-006", null, "Rolling kurtosis", "Whether extreme returns are unusually frequent.", "kurtosis, excess_kurtosis, period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["QNT-007", null, "Rolling correlation", "Strength and direction of co-movement with another asset.", "correlation, period, second series", "Pane", "All, P and BM", ["P", "BM"], "T1", "New", "unimplemented"],
  ["QNT-008", null, "Rolling covariance", "Joint variability between two return series.", "covariance, period", "Pane", "All, P and BM", ["P", "BM"], "T2", "New", "unimplemented"],
  ["QNT-009", null, "Rolling beta", "Sensitivity of an asset to a benchmark.", "beta, alpha, period, benchmark", "Pane", "All, P and BM", ["P", "BM"], "T1", "New", "unimplemented"],
  ["QNT-010", null, "Rolling alpha", "Return unexplained by benchmark beta over a rolling window.", "alpha_pct, period, benchmark", "Pane", "All, P and BM", ["P", "BM"], "T2", "New", "unimplemented"],
  ["QNT-011", null, "Linear regression slope", "Rate and direction of a fitted trend.", "slope, intercept, period", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["QNT-012", null, "Regression R-squared", "How closely price follows a linear trend.", "r_squared, period", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["QNT-013", null, "Regression residual Z-score", "Unusual distance from a fitted trend.", "residual, z_score, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["QNT-014", null, "Kalman Adaptive Velocity", "Recursive estimate of fair value, latent velocity, and innovation shocks.", "mean, velocity, bands, shock_z", "Overlay", "All, P", ["P"], "T0", "Existing chart", "unimplemented"],
  ["QNT-015", null, "Kalman trend state", "Converts Kalman velocity and uncertainty into trend regimes.", "direction, confidence, velocity", "Pane", "All, P", ["P"], "T2", "Existing component", "unimplemented"],
  ["QNT-016", null, "Hurst Exponent", "Estimates whether behavior is trending, random, or mean-reverting.", "hurst, state, period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["QNT-017", null, "Variance Ratio", "Tests whether returns resemble a random walk across horizons.", "variance_ratio, horizon", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["QNT-018", null, "Augmented Dickey-Fuller state", "Rolling stationarity test for possible mean reversion.", "test statistic, p-value, stationary", "Pane", "All, P", ["P"], "R", "Research", "unimplemented"],
  ["QNT-019", null, "Half-life of mean reversion", "Estimated time for a deviation to decay by half.", "half_life, AR coefficient", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["QNT-020", null, "Permutation Entropy", "Measures order versus randomness in price sequences.", "entropy, regime, adaptive channel", "Pane", "All, P", ["P"], "T0", "Existing chart", "unimplemented"],
  ["QNT-021", null, "Shannon Entropy", "Information content of discretized returns.", "entropy, normalized_entropy, period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["QNT-022", null, "Sample Entropy", "Measures repetitiveness and complexity in a time series.", "sample_entropy, dimension, tolerance", "Pane", "All, P", ["P"], "R", "Research", "unimplemented"],
  ["QNT-023", null, "Approximate Entropy", "Measures regularity of sequential observations.", "approximate_entropy, parameters", "Pane", "All, P", ["P"], "R", "Research", "unimplemented"],
  ["QNT-024", null, "Fractal Dimension Index", "Estimates whether price is smooth and trending or rough and noisy.", "dimension_1_2, period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["QNT-025", null, "Detrended Fluctuation Analysis", "Long-memory and scaling estimate robust to local trends.", "scaling_exponent, period", "Pane", "All, P", ["P"], "R", "Research", "unimplemented"],
  ["QNT-026", null, "Rescaled Range Analysis", "Classic long-memory statistic related to the Hurst exponent.", "R over S, hurst estimate", "Pane", "All, P", ["P"], "R", "Research", "unimplemented"],
  ["QNT-027", null, "Change-point detector", "Flags statistically meaningful shifts in mean or variance.", "change_event, score, state", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["QNT-028", null, "CUSUM Filter", "Accumulates deviations to detect structural moves.", "positive_cusum, negative_cusum, event", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["QNT-029", null, "Bayesian Online Change Point", "Probability that a new market regime has begun.", "change_probability, run_length", "Pane", "All, P", ["P"], "R", "Research", "unimplemented"],
  ["QNT-030", null, "Hidden Markov regime", "Probabilistic bull, bear, calm, or volatile state.", "state probabilities, active state", "Pane", "All, P", ["P"], "R", "Research", "unimplemented"],
  ["QNT-031", null, "Gaussian Mixture regime", "Clusters return and volatility observations into regimes.", "cluster, probabilities", "Pane", "All, P", ["P"], "R", "Research", "unimplemented"],
  ["QNT-032", null, "Mahalanobis anomaly score", "Multivariate distance from normal market conditions.", "anomaly_score, percentile", "Pane", "All, multiple indicators", [], "R", "Research", "unimplemented"],
  ["QNT-033", null, "Rolling Sharpe signal", "Recent excess return per unit of volatility.", "rolling_sharpe, period, risk-free rate", "Pane", "All, P and M", ["P", "M"], "T2", "New", "unimplemented"],
  ["QNT-034", null, "Rolling Sortino signal", "Recent excess return per unit of downside volatility.", "rolling_sortino, period, target return", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["QNT-035", null, "Trend quality score", "Combines slope, R-squared, persistence, and volatility.", "score_0_100, state", "Pane", "All, P", ["P"], "T2", "New composite", "unimplemented"],
  ["QNT-036", null, "Mean-reversion score", "Combines stationarity, half-life, Z-score, and entropy.", "score_0_100, direction", "Pane", "All, P", ["P"], "T3", "New composite", "unimplemented"],
  ["QNT-037", null, "HYDRA Binary Index", "Proprietary adaptive regime state and continuous curve.", "binary state, continuous value, markers", "Pane", "EGX equities, P", ["P"], "T0", "Existing chart", "unimplemented"],
  ["QNT-038", null, "Ensemble regime consensus", "Agreement across trend, volatility, entropy, and change-point states.", "regime, confidence, component votes", "Pane", "All, P", ["P"], "R", "Research composite", "unimplemented"],
], [
  "z-score",
  "rolling-mean-variance",
  "rolling-median-mad",
  "quantile-percentile-rank",
  "rolling-skewness",
  "rolling-kurtosis",
  "rolling-correlation",
  "rolling-covariance",
  "rolling-beta",
  "rolling-alpha",
  "linear-regression-slope",
  "regression-r-squared",
  "regression-residual-z-score",
  "kalman-adaptive-velocity",
  "kalman-trend-state",
  "hurst-exponent",
  "variance-ratio",
  "augmented-dickey-fuller-state",
  "half-life-mean-reversion",
  "permutation-entropy",
  "shannon-entropy",
  "sample-entropy",
  "approximate-entropy",
  "fractal-dimension-index",
  "detrended-fluctuation-analysis",
  "rescaled-range-analysis",
  "change-point-detector",
  "cusum-filter",
  "bayesian-online-change-point",
  "hidden-markov-regime",
  "gaussian-mixture-regime",
  "mahalanobis-anomaly-score",
  "rolling-sharpe-signal",
  "rolling-sortino-signal",
  "trend-quality-score",
  "mean-reversion-score",
  "hydra-binary-index",
  "ensemble-regime-consensus",
]);
