import { defineProgramCategory } from './define-category';

export const RELATIVE_INTERMARKET_PROGRAM_ENTRIES = defineProgramCategory("relative-intermarket", [
  ["REL-001", null, "Price Ratio", "One asset divided by another to show relative performance.", "ratio, normalized ratio", "Pane", "All, P and BM", ["P", "BM"], "T1", "New primitive", "unimplemented"],
  ["REL-002", null, "Relative Strength versus Benchmark", "Asset return minus benchmark return.", "relative_return, period, benchmark", "Pane", "All, P and BM", ["P", "BM"], "T1", "New", "unimplemented"],
  ["REL-003", null, "Relative Strength Line", "Cumulative asset-to-benchmark ratio.", "RS line, new high event", "Pane", "All, P and BM", ["P", "BM"], "T1", "New", "unimplemented"],
  ["REL-004", null, "Relative Strength Momentum", "Rate of change of the relative-strength line.", "RS momentum, period", "Pane", "All, P and BM", ["P", "BM"], "T2", "New", "unimplemented"],
  ["REL-005", null, "Mansfield Relative Strength", "Relative performance normalized around its long-term average.", "Mansfield RS, period", "Pane", "Equities and sectors, BM", ["BM"], "T2", "New", "unimplemented"],
  ["REL-006", null, "Relative Rotation Graph metrics", "Relative strength and momentum coordinates versus a benchmark.", "JdK RS-ratio, RS-momentum, quadrant", "Market", "Sectors or assets, BM", ["BM"], "T2", "New", "unimplemented"],
  ["REL-007", null, "Cross-sectional momentum rank", "Ranks all eligible assets by recent return.", "rank, percentile, universe", "Market", "EGX universe, B", ["B"], "T1", "New", "unimplemented"],
  ["REL-008", null, "Risk-adjusted momentum rank", "Ranks return after accounting for volatility or drawdown.", "rank, score, periods", "Market", "EGX universe, B", ["B"], "T2", "New", "unimplemented"],
  ["REL-009", null, "Dual Momentum", "Combines absolute positive momentum with benchmark-relative momentum.", "absolute state, relative rank", "Market", "All, BM", ["BM"], "T2", "New", "unimplemented"],
  ["REL-010", null, "Sector Relative Strength", "Sector performance versus EGX30, EGX70, or the full market.", "ratio, return spread, rank", "Market", "EGX sectors, BM", ["BM"], "T1", "New", "unimplemented"],
  ["REL-011", null, "Rolling Correlation Matrix", "Pairwise co-movement between selected assets.", "correlations, clusters", "Market", "Multiple assets, BM", ["BM"], "T2", "New", "unimplemented"],
  ["REL-012", null, "Rolling Beta Matrix", "Sensitivity of assets or sectors to a benchmark.", "betas, period", "Market", "Multiple assets, BM", ["BM"], "T2", "New", "unimplemented"],
  ["REL-013", null, "Lead-Lag Correlation", "Tests whether one series tends to move before another.", "best lag, correlation by lag", "Pane", "Two assets, BM", ["BM"], "T3", "New", "unimplemented"],
  ["REL-014", null, "Cointegration Spread", "Residual spread between a statistically linked pair.", "hedge ratio, spread, z-score", "Pane", "Two assets, BM", ["BM"], "T3", "New", "unimplemented"],
  ["REL-015", null, "Pair Ratio Z-score", "Standardized asset ratio for relative-value monitoring.", "ratio, z-score, period", "Pane", "Two assets, BM", ["BM"], "T2", "New", "unimplemented"],
  ["REL-016", null, "EGX versus Gold Relative Strength", "Local equities compared with EGP gold performance.", "ratio, return spread, trend", "Pane", "EGX and local gold, BM", ["BM"], "T2", "New", "unimplemented"],
  ["REL-017", null, "EGX versus USD Relative Strength", "Local equities compared with USD/EGP depreciation.", "real and nominal relative return", "Pane", "EGX and FX, BM", ["BM"], "T2", "New", "unimplemented"],
  ["REL-018", null, "Fund versus Benchmark Attribution", "Fund performance relative to its declared benchmark.", "excess return, beta, tracking error", "Card", "Funds, BM", ["BM"], "T2", "New", "unimplemented"],
  ["REL-019", null, "Currency-adjusted return", "Converts an asset return into EGP, USD, or real purchasing-power terms.", "adjusted_return, selected currency", "Pane", "All, P and M", ["P", "M"], "T1", "New", "unimplemented"],
  ["REL-020", null, "Inflation-adjusted return", "Nominal return minus or deflated by Egyptian inflation.", "real_return, annualized_real_return", "Pane", "All, P and M", ["P", "M"], "T1", "Existing adjacent logic", "unimplemented"],
], [
  "relative-price-ratio",
  "relative-relative-strength-versus-benchmark",
  "relative-relative-strength-line",
  "relative-relative-strength-momentum",
  "relative-mansfield-relative-strength",
  "relative-relative-rotation-graph-metrics",
  "relative-cross-sectional-momentum-rank",
  "relative-risk-adjusted-momentum-rank",
  "relative-dual-momentum",
  "relative-sector-relative-strength",
  "relative-rolling-correlation-matrix",
  "relative-rolling-beta-matrix",
  "relative-lead-lag-correlation",
  "relative-cointegration-spread",
  "relative-pair-ratio-z-score",
  "relative-egx-versus-gold-relative-strength",
  "relative-egx-versus-usd-relative-strength",
  "relative-fund-versus-benchmark-attribution",
  "relative-currency-adjusted-return",
  "relative-inflation-adjusted-return",
]);
