import { defineProgramCategory } from './define-category';

export const RISK_PORTFOLIO_PROGRAM_ENTRIES = defineProgramCategory("risk-portfolio", [
  ["RSK-001", null, "Simple return", "Gain or loss over a chosen period.", "return_pct, horizon", "Card", "All, P", ["P"], "T1", "New primitive", "unimplemented"],
  ["RSK-002", null, "Annualized return", "Return translated into a yearly rate.", "annualized_return", "Card", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["RSK-003", null, "Compound Annual Growth Rate (CAGR)", "Smoothed annual growth from start to end.", "CAGR", "Card", "All, P", ["P"], "T1", "Existing strategy metric", "unimplemented"],
  ["RSK-004", null, "Maximum Drawdown", "Largest peak-to-trough loss.", "max_drawdown_pct, dates, duration", "Card", "All, P", ["P"], "T1", "Existing strategy metric", "unimplemented"],
  ["RSK-005", null, "Current Drawdown", "Present decline from the most recent peak.", "current_drawdown, duration", "Card", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["RSK-006", null, "Drawdown Duration", "Time spent below a previous peak.", "current and maximum duration", "Card", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["RSK-007", null, "Volatility", "Annualized variability of returns.", "volatility_pct, period", "Card", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["RSK-008", null, "Downside Deviation", "Variability of returns below a target.", "downside_deviation, target", "Card", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["RSK-009", null, "Sharpe Ratio", "Excess return per unit of total volatility.", "Sharpe, risk-free rate, period", "Card", "All, P and M", ["P", "M"], "T1", "Existing strategy metric", "unimplemented"],
  ["RSK-010", null, "Sortino Ratio", "Excess return per unit of downside volatility.", "Sortino, target return", "Card", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["RSK-011", null, "Calmar Ratio", "Annual return divided by maximum drawdown.", "Calmar", "Card", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["RSK-012", null, "Omega Ratio", "Probability-weighted gains versus losses around a threshold.", "Omega, threshold", "Card", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["RSK-013", null, "Information Ratio", "Active return per unit of tracking error.", "information_ratio, benchmark", "Card", "All, P and BM", ["P", "BM"], "T2", "New", "unimplemented"],
  ["RSK-014", null, "Treynor Ratio", "Excess return per unit of market beta.", "Treynor, beta, risk-free rate", "Card", "All, P, BM, M", ["P", "BM", "M"], "T3", "New", "unimplemented"],
  ["RSK-015", null, "Jensen Alpha", "Risk-adjusted excess return versus CAPM expectation.", "alpha, beta, risk-free rate", "Card", "All, P, BM, M", ["P", "BM", "M"], "T2", "New", "unimplemented"],
  ["RSK-016", null, "Tracking Error", "Volatility of returns versus a benchmark.", "tracking_error", "Card", "Funds and portfolios, BM", ["BM"], "T1", "New", "unimplemented"],
  ["RSK-017", null, "Value at Risk (Historical VaR)", "Loss threshold exceeded only at a chosen probability.", "VaR, confidence, horizon", "Card", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["RSK-018", null, "Parametric VaR", "Normal-distribution estimate of a loss threshold.", "VaR, confidence, horizon", "Card", "All, P", ["P"], "T3", "New with caveat", "unimplemented"],
  ["RSK-019", null, "Conditional VaR or Expected Shortfall", "Average loss beyond the VaR threshold.", "CVaR, confidence", "Card", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["RSK-020", null, "Maximum Adverse Excursion", "Worst move against each historical trade.", "MAE, average MAE", "Card", "Strategies, trade history", [], "T1", "Existing strategy metric", "unimplemented"],
  ["RSK-021", null, "Maximum Favorable Excursion", "Best move in favor of each historical trade.", "MFE, average MFE", "Card", "Strategies, trade history", [], "T1", "Existing strategy metric", "unimplemented"],
  ["RSK-022", null, "Profit Factor", "Gross strategy gains divided by gross strategy losses.", "profit_factor", "Card", "Strategies, trade history", [], "T1", "Existing strategy metric", "unimplemented"],
  ["RSK-023", null, "Win Rate", "Percentage of completed trades that were profitable.", "win_rate, sample_count", "Card", "Strategies, trade history", [], "T1", "Existing strategy metric", "unimplemented"],
  ["RSK-024", null, "Expectancy", "Average expected profit or loss per trade.", "expectancy amount and pct", "Card", "Strategies, trade history", [], "T1", "New", "unimplemented"],
  ["RSK-025", null, "Payoff Ratio", "Average win divided by average loss.", "payoff_ratio", "Card", "Strategies, trade history", [], "T1", "Existing adjacent metric", "unimplemented"],
  ["RSK-026", null, "Kelly Fraction", "Theoretical capital fraction based on win rate and payoff.", "full and fractional Kelly", "Card", "Strategies, trade history", [], "T3", "New with strong warning", "unimplemented"],
  ["RSK-027", null, "Risk of Ruin", "Estimated probability of breaching a capital-loss threshold.", "probability, assumptions", "Card", "Strategies, trade history", [], "T3", "New", "unimplemented"],
  ["RSK-028", null, "Ulcer Performance Index", "Excess return divided by the Ulcer Index.", "UPI", "Card", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["RSK-029", null, "Gain-to-Pain Ratio", "Sum of returns divided by absolute losses.", "gain_to_pain", "Card", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["RSK-030", null, "Recovery Factor", "Net profit divided by maximum drawdown.", "recovery_factor", "Card", "Strategies and portfolios", [], "T2", "New", "unimplemented"],
  ["RSK-031", null, "Portfolio Beta", "Weighted sensitivity of the portfolio to a benchmark.", "beta, component contributions", "Card", "Portfolio, BM", ["BM"], "T2", "New", "unimplemented"],
  ["RSK-032", null, "Marginal Risk Contribution", "Each holding's contribution to total portfolio volatility.", "marginal and percentage contribution", "Card", "Portfolio, covariance data", [], "T3", "New", "unimplemented"],
  ["RSK-033", null, "Concentration and HHI", "How concentrated the portfolio is in positions, sectors, or currencies.", "HHI, effective holdings", "Card", "Portfolio", [], "T1", "New", "unimplemented"],
  ["RSK-034", null, "Diversification Ratio", "Weighted asset volatility divided by portfolio volatility.", "diversification_ratio", "Card", "Portfolio, covariance data", [], "T3", "New", "unimplemented"],
  ["RSK-035", null, "Correlation Stress", "Portfolio risk under elevated cross-asset correlation.", "stressed_volatility, delta risk", "Card", "Portfolio", [], "R", "Research", "unimplemented"],
  ["RSK-036", null, "Inflation drag", "Nominal value lost to Egyptian inflation over time.", "real value, drag amount, drag pct", "Card", "Portfolio, M", ["M"], "T0", "Existing adjacent feature", "unimplemented"],
], [
  "simple-return",
  "annualized-return",
  "compound-annual-growth-rate",
  "maximum-drawdown",
  "current-drawdown",
  "drawdown-duration",
  "volatility",
  "downside-deviation",
  "sharpe-ratio",
  "sortino-ratio",
  "calmar-ratio",
  "omega-ratio",
  "information-ratio",
  "treynor-ratio",
  "jensen-alpha",
  "tracking-error",
  "historical-value-at-risk",
  "parametric-value-at-risk",
  "conditional-value-at-risk",
  "maximum-adverse-excursion",
  "maximum-favorable-excursion",
  "profit-factor",
  "win-rate",
  "expectancy",
  "payoff-ratio",
  "kelly-fraction",
  "risk-of-ruin",
  "ulcer-performance-index",
  "gain-to-pain-ratio",
  "recovery-factor",
  "portfolio-beta",
  "marginal-risk-contribution",
  "concentration-hhi",
  "diversification-ratio",
  "correlation-stress",
  "inflation-drag",
]);
