import { defineProgramCategory } from './define-category';

export const TREND_PROGRAM_ENTRIES = defineProgramCategory("trend", [
  ["TRD-001", null, "Simple Moving Average (SMA)", "Average price over a fixed number of bars.", "sma, period, source", "Overlay", "All, P", ["P"], "T1", "Internal only", "unimplemented"],
  ["TRD-002", null, "Exponential Moving Average (EMA)", "Moving average that reacts faster to recent prices.", "ema, period, source", "Overlay", "All, P", ["P"], "T1", "Internal only", "unimplemented"],
  ["TRD-003", null, "Weighted Moving Average (WMA)", "Moving average with linearly larger weight on recent prices.", "wma, period", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["TRD-004", null, "Wilder Moving Average (RMA or SMMA)", "Slow recursive average used by RSI and ATR.", "rma, period", "Overlay", "All, P", ["P"], "T1", "Internal component", "unimplemented"],
  ["TRD-005", null, "Double EMA (DEMA)", "Reduced-lag combination of two EMAs.", "dema, period", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-006", null, "Triple EMA (TEMA)", "Reduced-lag combination of three EMAs.", "tema, period", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-007", null, "Hull Moving Average (HMA)", "Smooth trend line designed to reduce lag.", "hma, period", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-008", null, "Kaufman Adaptive Moving Average (KAMA)", "Speeds up in trends and slows down in noisy markets.", "kama, efficiency_period, fast, slow", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-009", null, "Fractal Adaptive Moving Average (FRAMA)", "Adapts to the market's fractal dimension and trend quality.", "frama, period, alpha limits", "Overlay", "All, P", ["P"], "T0", "Existing chart", "unimplemented"],
  ["TRD-010", null, "Variable Index Dynamic Average (VIDYA)", "EMA whose speed changes with momentum or volatility.", "vidya, period, momentum_period", "Overlay", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["TRD-011", null, "McGinley Dynamic", "Adaptive average intended to follow speed changes with less lag.", "mcginley, period", "Overlay", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["TRD-012", null, "Arnaud Legoux Moving Average (ALMA)", "Gaussian-weighted average balancing smoothness and responsiveness.", "alma, period, offset, sigma", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-013", null, "Least Squares Moving Average (LSMA)", "End value of a rolling linear regression.", "lsma, period, offset", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-014", null, "Triangular Moving Average (TMA)", "Twice-smoothed SMA with strong noise reduction.", "tma, period", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-015", null, "Zero-Lag EMA (ZLEMA)", "EMA adjusted to compensate for estimated lag.", "zlema, period", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-016", null, "Moving Average Ribbon", "Several averages showing trend alignment and compression.", "ribbon lines, periods, average type", "Overlay", "All, P", ["P"], "T1", "New composite", "unimplemented"],
  ["TRD-017", null, "Guppy Multiple Moving Average (GMMA)", "Short and long EMA groups showing trader versus investor behavior.", "short ribbon, long ribbon", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-018", null, "Moving-average slope", "Direction and steepness of any chosen moving average.", "slope, normalized_slope, period", "Pane", "All, P", ["P"], "T1", "New primitive", "unimplemented"],
  ["TRD-019", null, "Moving-average distance", "Percentage distance between price and a moving average.", "distance_pct, average, period", "Pane", "All, P", ["P"], "T1", "New primitive", "unimplemented"],
  ["TRD-020", null, "Moving-average spread", "Distance between a fast and slow moving average.", "spread, spread_pct, fast, slow", "Pane", "All, P", ["P"], "T1", "New primitive", "unimplemented"],
  ["TRD-021", null, "Moving-average crossover", "Event when a fast average crosses a slow average.", "cross_up, cross_down, fast, slow", "Overlay", "All, P", ["P"], "T1", "Builder template", "unimplemented"],
  ["TRD-022", null, "Moving-average compression", "Detects tightly packed averages before possible expansion.", "compression_pct, periods, threshold", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-023", null, "Moving-average trend score", "Counts how many averages are bullishly or bearishly aligned.", "score, alignment_state, periods", "Pane", "All, P", ["P"], "T2", "New composite", "unimplemented"],
  ["TRD-024", null, "MACD", "Difference between fast and slow EMAs with a signal line.", "macd, signal, histogram, 12, 26, 9", "Pane", "All, P", ["P"], "T1", "Internal only", "unimplemented"],
  ["TRD-025", null, "Percentage Price Oscillator (PPO)", "MACD expressed as a percentage for comparison across assets.", "ppo, signal, histogram", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["TRD-026", null, "Percentage Volume Oscillator (PVO)", "Fast versus slow volume trend expressed as a percentage.", "pvo, signal, histogram", "Pane", "All with V", ["V"], "T2", "New", "unimplemented"],
  ["TRD-027", null, "TRIX", "Momentum of a triple-smoothed EMA that filters short-term noise.", "trix, signal, period", "Pane", "All, P", ["P"], "T2", "Internal only", "unimplemented"],
  ["TRD-028", null, "Aroon", "Measures how recently new highs and lows occurred.", "aroon_up, aroon_down, oscillator, period", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["TRD-029", null, "Vortex Indicator", "Compares positive and negative trend movement.", "vi_plus, vi_minus, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-030", null, "Directional Movement Index (DMI)", "Separates positive and negative directional pressure.", "plus_di, minus_di, period", "Pane", "All, P", ["P"], "T1", "Internal component", "unimplemented"],
  ["TRD-031", null, "Average Directional Index (ADX)", "Measures trend strength without saying whether it is up or down.", "adx, plus_di, minus_di, period", "Pane", "All, P", ["P"], "T1", "Internal only", "unimplemented"],
  ["TRD-032", null, "ADX Rating (ADXR)", "Smoothed ADX used to confirm persistent trend strength.", "adxr, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-033", null, "Supertrend", "ATR-based trend line that flips between bullish and bearish states.", "line, direction, period, multiplier", "Overlay", "All, P", ["P"], "T1", "Internal component", "unimplemented"],
  ["TRD-034", null, "Parabolic SAR", "Trailing stop dots that accelerate as a trend develops.", "sar, direction, step, maximum", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["TRD-035", null, "Ichimoku Cloud", "Multi-line trend, momentum, and support/resistance system.", "tenkan, kijun, spans A/B, chikou, 9, 26, 52", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["TRD-036", null, "Donchian Trend State", "Trend state based on breaks of rolling highs and lows.", "upper, lower, middle, breakout_state", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["TRD-037", null, "Chandelier Trend State", "ATR-based trailing line anchored to rolling extremes.", "long_stop, short_stop, period, multiplier", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-038", null, "Trend Intensity Index (TII)", "Measures how consistently price stays above or below its mean.", "tii_0_100, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-039", null, "Vertical Horizontal Filter (VHF)", "Distinguishes trending from ranging behavior.", "vhf, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["TRD-040", null, "Mass Index", "Detects range expansion patterns that can precede trend reversals.", "mass_index, ema_period, sum_period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
], [
  "simple-moving-average",
  "exponential-moving-average",
  "weighted-moving-average",
  "wilder-moving-average",
  "double-exponential-moving-average",
  "triple-exponential-moving-average",
  "hull-moving-average",
  "kaufman-adaptive-moving-average",
  "fractal-adaptive-moving-average",
  "variable-index-dynamic-average",
  "mcginley-dynamic",
  "arnaud-legoux-moving-average",
  "least-squares-moving-average",
  "triangular-moving-average",
  "zero-lag-exponential-moving-average",
  "moving-average-ribbon",
  "guppy-multiple-moving-average",
  "moving-average-slope",
  "moving-average-distance",
  "moving-average-spread",
  "moving-average-crossover",
  "moving-average-compression",
  "moving-average-trend-score",
  "macd",
  "percentage-price-oscillator",
  "percentage-volume-oscillator",
  "trix",
  "aroon",
  "vortex-indicator",
  "directional-movement-index",
  "average-directional-index",
  "adx-rating",
  "supertrend",
  "parabolic-sar",
  "ichimoku-cloud",
  "donchian-trend-state",
  "chandelier-trend-state",
  "trend-intensity-index",
  "vertical-horizontal-filter",
  "mass-index",
]);
