import { defineProgramCategory } from './define-category';

export const VOLATILITY_PROGRAM_ENTRIES = defineProgramCategory("volatility", [
  ["VOL-001", null, "Average True Range (ATR)", "Average gap-adjusted trading range in price units.", "atr, period", "Pane", "All, P", ["P"], "T1", "Internal only", "unimplemented"],
  ["VOL-002", null, "ATR percentage", "ATR divided by price so different assets can be compared.", "atr_pct, period", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["VOL-003", null, "Normalized ATR", "ATR normalized against its own recent range or history.", "normalized_atr, periods", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["VOL-004", null, "Bollinger Bands", "Moving average with standard-deviation bands.", "middle, upper, lower, period, deviation", "Overlay", "All, P", ["P"], "T1", "Internal only", "unimplemented"],
  ["VOL-005", null, "Bollinger Percent B", "Position of price inside or outside Bollinger Bands.", "percent_b", "Pane", "All, P", ["P"], "T1", "Internal component", "unimplemented"],
  ["VOL-006", null, "Bollinger Bandwidth", "Width of Bollinger Bands as a volatility measure.", "bandwidth_pct", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["VOL-007", null, "Bollinger Squeeze", "Detects unusually narrow Bollinger Bands.", "squeeze_state, percentile, lookback", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["VOL-008", null, "Keltner Channels", "EMA envelope based on ATR.", "middle, upper, lower, period, multiplier", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["VOL-009", null, "TTM Squeeze style state", "Compares Bollinger Bands with Keltner Channels for compression.", "squeeze_on, squeeze_off, momentum", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["VOL-010", null, "Donchian Channels", "Rolling highest high and lowest low.", "upper, lower, middle, period", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["VOL-011", null, "Price Channel", "General rolling high-low channel with configurable source.", "upper, lower, middle, period", "Overlay", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["VOL-012", null, "Standard Deviation", "Dispersion of price or returns around their average.", "stdev, period, source", "Pane", "All, P", ["P"], "T1", "New primitive", "unimplemented"],
  ["VOL-013", null, "Historical Volatility", "Annualized standard deviation of returns.", "volatility_pct, period, annualization", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["VOL-014", null, "Parkinson Volatility", "Range-based volatility using high and low prices.", "volatility_pct, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["VOL-015", null, "Garman-Klass Volatility", "Uses open, high, low, and close for efficient volatility estimation.", "volatility_pct, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["VOL-016", null, "Rogers-Satchell Volatility", "OHLC volatility estimator that tolerates price drift.", "volatility_pct, period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["VOL-017", null, "Yang-Zhang Volatility", "Combines overnight gaps and intraday movement.", "volatility_pct, period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["VOL-018", null, "Chaikin Volatility", "Rate of change of an EMA of the high-low range.", "chaikin_volatility, ema period, ROC period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["VOL-019", null, "Relative Volatility Index (RVI)", "RSI-like measure built from directional volatility.", "rvi_0_100, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["VOL-020", null, "Ulcer Index", "Depth and duration of downside drawdowns.", "ulcer_index, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["VOL-021", null, "Choppiness Index", "Measures whether price is ranging or trending.", "choppiness_0_100, period", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["VOL-022", null, "Volatility percentile", "Current volatility relative to its own history.", "percentile_0_100, short period, rank period", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["VOL-023", null, "Volatility regime", "Labels low, normal, high, or extreme volatility.", "state, thresholds, period", "Pane", "All, P", ["P"], "T2", "New composite", "unimplemented"],
  ["VOL-024", null, "Range Expansion Index (REI)", "Measures directional range expansion and exhaustion.", "rei, period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["VOL-025", null, "Average Daily Range (ADR)", "Average high-low movement over daily bars.", "adr, adr_pct, period", "Pane", "All, P", ["P"], "T1", "New", "unimplemented"],
  ["VOL-026", null, "Expected move from volatility", "Translates historical volatility into an expected price range.", "upper, lower, confidence, horizon", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["VOL-027", null, "ATR trailing stop", "A stop line that follows price by an ATR multiple.", "stop_line, direction, period, multiplier", "Overlay", "All, P", ["P"], "T1", "Internal component", "unimplemented"],
  ["VOL-028", null, "Chandelier Exit", "Trailing exits based on rolling extremes and ATR.", "long_exit, short_exit, period, multiplier", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["VOL-029", null, "Volatility Stop", "Trend-following stop that flips after price crosses an ATR stop.", "stop, state, period, multiplier", "Overlay", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["VOL-030", null, "Highest-lowest range ratio", "Current bar or window range versus its longer-term norm.", "expansion_ratio, short, long", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["VOL-031", null, "Gap volatility", "Frequency and size distribution of opening gaps.", "average_gap, positive_gap, negative_gap, period", "Pane", "All, P", ["P"], "T2", "New", "unimplemented"],
  ["VOL-032", null, "Realized semivolatility", "Separates volatility on positive and negative returns.", "upside_vol, downside_vol, period", "Pane", "All, P", ["P"], "T3", "New", "unimplemented"],
], [
  "average-true-range",
  "atr-percentage",
  "normalized-atr",
  "bollinger-bands",
  "bollinger-percent-b",
  "bollinger-bandwidth",
  "bollinger-squeeze",
  "keltner-channels",
  "ttm-squeeze-state",
  "donchian-channels",
  "price-channel",
  "standard-deviation",
  "historical-volatility",
  "parkinson-volatility",
  "garman-klass-volatility",
  "rogers-satchell-volatility",
  "yang-zhang-volatility",
  "chaikin-volatility",
  "relative-volatility-index",
  "ulcer-index",
  "choppiness-index",
  "volatility-percentile",
  "volatility-regime",
  "range-expansion-index",
  "average-daily-range",
  "expected-move-from-volatility",
  "atr-trailing-stop",
  "chandelier-exit",
  "volatility-stop",
  "highest-lowest-range-ratio",
  "gap-volatility",
  "realized-semivolatility",
]);
