import { defineProgramCategory } from './define-category';

export const VOLUME_FLOW_PROGRAM_ENTRIES = defineProgramCategory("volume-flow", [
  ["FLW-001", null, "Raw volume", "Number of shares or units traded in each bar.", "volume", "Pane", "Assets with V", ["V"], "T1", "New primitive", "unimplemented"],
  ["FLW-002", null, "Volume moving average", "Normal participation level over a selected period.", "volume_ma, period", "Pane", "Assets with V", ["V"], "T1", "New", "unimplemented"],
  ["FLW-003", null, "Relative Volume (RVOL)", "Current volume divided by its recent average.", "rvol_ratio, period", "Pane", "Assets with V", ["V"], "T1", "New", "unimplemented"],
  ["FLW-004", null, "Volume percentile", "Current volume relative to its own historical distribution.", "percentile_0_100, period", "Pane", "Assets with V", ["V"], "T2", "New", "unimplemented"],
  ["FLW-005", null, "Volume Rate of Change", "How quickly volume is expanding or contracting.", "volume_roc_pct, period", "Pane", "Assets with V", ["V"], "T1", "New", "unimplemented"],
  ["FLW-006", null, "On-Balance Volume (OBV)", "Cumulative volume added on up closes and removed on down closes.", "obv, smoothing", "Pane", "Assets with V", ["V"], "T1", "Internal only", "unimplemented"],
  ["FLW-007", null, "Accumulation/Distribution Line", "Cumulative volume weighted by where close sits in the bar.", "ad_line", "Pane", "Assets with V", ["V"], "T1", "New", "unimplemented"],
  ["FLW-008", null, "Chaikin Money Flow (CMF)", "Buying or selling pressure over a rolling period.", "cmf, period", "Pane", "Assets with V", ["V"], "T1", "New", "unimplemented"],
  ["FLW-009", null, "Chaikin Oscillator", "Fast versus slow EMA of the Accumulation/Distribution Line.", "oscillator, fast, slow", "Pane", "Assets with V", ["V"], "T2", "New", "unimplemented"],
  ["FLW-010", null, "Money Flow Index (MFI)", "Volume-weighted RSI-style oscillator.", "mfi_0_100, period", "Pane", "Assets with V", ["V"], "T1", "Internal only", "unimplemented"],
  ["FLW-011", null, "Volume Price Trend (VPT)", "Cumulative volume adjusted by percentage price changes.", "vpt", "Pane", "Assets with V", ["V"], "T1", "New", "unimplemented"],
  ["FLW-012", null, "Positive Volume Index (PVI)", "Tracks price behavior on higher-volume days.", "pvi, signal", "Pane", "Assets with V", ["V"], "T2", "New", "unimplemented"],
  ["FLW-013", null, "Negative Volume Index (NVI)", "Tracks price behavior on lower-volume days.", "nvi, signal", "Pane", "Assets with V", ["V"], "T2", "New", "unimplemented"],
  ["FLW-014", null, "Ease of Movement (EOM)", "Price movement relative to volume and trading range.", "eom, smoothed_eom, period", "Pane", "Assets with V", ["V"], "T2", "New", "unimplemented"],
  ["FLW-015", null, "Force Index", "Price change multiplied by volume.", "force_index, period", "Pane", "Assets with V", ["V"], "T1", "Internal only", "unimplemented"],
  ["FLW-016", null, "Elder Force Index", "Smoothed Force Index for trend confirmation.", "force, ema period", "Pane", "Assets with V", ["V"], "T2", "New", "unimplemented"],
  ["FLW-017", null, "Price Volume Trend divergence", "Confirmed disagreement between price and VPT or OBV.", "bullish, bearish, pivot windows", "Overlay", "Assets with V", ["V"], "T2", "New, confirmed delay", "unimplemented"],
  ["FLW-018", null, "VWAP", "Session price weighted by traded volume.", "vwap, anchor or session", "Overlay", "Intraday assets with V", ["V"], "T1", "New", "unimplemented"],
  ["FLW-019", null, "Anchored VWAP", "VWAP starting from a user-selected event or date.", "avwap, anchor", "Overlay", "Assets with V", ["V"], "T1", "New", "unimplemented"],
  ["FLW-020", null, "Rolling VWAP", "Fixed-window volume-weighted average price.", "rolling_vwap, period", "Overlay", "Assets with V", ["V"], "T1", "New", "unimplemented"],
  ["FLW-021", null, "VWAP bands", "Standard-deviation or percentage envelopes around VWAP.", "upper, lower, deviations", "Overlay", "Assets with V", ["V"], "T2", "New", "unimplemented"],
  ["FLW-022", null, "Volume Weighted Moving Average (VWMA)", "Moving average that gives more weight to high-volume bars.", "vwma, period", "Overlay", "Assets with V", ["V"], "T1", "New", "unimplemented"],
  ["FLW-023", null, "Volume Profile", "Volume distributed across price levels in a chosen range.", "price bins, POC, value area", "Overlay", "Assets with V", ["V"], "T2", "New", "unimplemented"],
  ["FLW-024", null, "Visible Range Volume Profile", "Volume profile calculated for the currently visible chart window.", "POC, VAH, VAL, bins", "Overlay", "Assets with V", ["V"], "T2", "New", "unimplemented"],
  ["FLW-025", null, "Fixed Range Volume Profile", "Volume profile between two selected dates.", "POC, VAH, VAL, bins", "Overlay", "Assets with V", ["V"], "T2", "New", "unimplemented"],
  ["FLW-026", null, "Time Price Opportunity profile", "Time spent at each price level rather than volume.", "POC, value area, letters or bins", "Overlay", "All, P", ["P"], "T3", "New", "unimplemented"],
  ["FLW-027", null, "Average Trade Size", "Turnover divided by verified number of trades.", "ats, average_ats, ratio", "Pane", "EGX equities, PVT", ["P", "V", "T"], "T0", "Existing chart", "unimplemented"],
  ["FLW-028", null, "Smart Money Flow", "Combines ATS, volume, spread, and close location into accumulation/distribution states.", "ATS, absorption, state, markers", "Pane", "EGX equities, PVT", ["P", "V", "T"], "T0", "Existing chart", "unimplemented"],
  ["FLW-029", null, "Turnover", "Traded value calculated from price and volume.", "turnover, rolling_turnover", "Pane", "Assets with V", ["V"], "T1", "New primitive", "unimplemented"],
  ["FLW-030", null, "Turnover velocity", "Turnover relative to free float or shares outstanding.", "turnover_ratio, period", "Pane", "Equities, V and FND", ["V", "FND"], "R", "Data-gated", "unimplemented"],
  ["FLW-031", null, "Amihud Illiquidity", "Absolute return divided by traded value.", "illiquidity, period", "Pane", "Assets with V", ["V"], "T3", "New", "unimplemented"],
  ["FLW-032", null, "Volume-synchronized probability of informed trading proxy", "Estimates unusual directional volume imbalance.", "vpin_proxy, bucket size", "Pane", "Intraday, OB or granular V", ["V", "OB"], "R", "Research", "unimplemented"],
  ["FLW-033", null, "Bid-ask spread", "Immediate transaction cost and liquidity measure.", "spread, spread_bps", "Pane", "Intraday, OB", ["OB"], "R", "Data-gated", "unimplemented"],
  ["FLW-034", null, "Order Book Imbalance", "Compares displayed bid and ask liquidity.", "imbalance, depth levels", "Pane", "Intraday, OB", ["OB"], "R", "Data-gated", "unimplemented"],
  ["FLW-035", null, "Cumulative Volume Delta", "Difference between buyer-initiated and seller-initiated volume.", "delta, cumulative_delta", "Pane", "Intraday trades, OB", ["OB"], "R", "Data-gated", "unimplemented"],
  ["FLW-036", null, "Trade intensity", "Number of trades per minute or bar relative to normal.", "trades_rate, relative_rate", "Pane", "EGX equities, T", ["T"], "T2", "New", "unimplemented"],
  ["FLW-037", null, "Block trade detector", "Flags unusually large trades relative to the asset's distribution.", "block_event, size_percentile", "Overlay", "Trade-level data", [], "R", "Data-gated", "unimplemented"],
  ["FLW-038", null, "Absorption ratio", "High volume with limited price range, separated by close direction.", "absorption, state, periods", "Pane", "Assets with V", ["V"], "T1", "Existing component", "unimplemented"],
], [
  "raw-volume",
  "volume-moving-average",
  "relative-volume",
  "volume-percentile",
  "volume-rate-of-change",
  "on-balance-volume",
  "accumulation-distribution-line",
  "chaikin-money-flow",
  "chaikin-oscillator",
  "money-flow-index",
  "volume-price-trend",
  "positive-volume-index",
  "negative-volume-index",
  "ease-of-movement",
  "force-index",
  "elder-force-index",
  "price-volume-trend-divergence",
  "vwap",
  "anchored-vwap",
  "rolling-vwap",
  "vwap-bands",
  "volume-weighted-moving-average",
  "volume-profile",
  "visible-range-volume-profile",
  "fixed-range-volume-profile",
  "time-price-opportunity-profile",
  "average-trade-size",
  "smart-money-flow",
  "turnover",
  "turnover-velocity",
  "amihud-illiquidity",
  "vpin-proxy",
  "bid-ask-spread",
  "order-book-imbalance",
  "cumulative-volume-delta",
  "trade-intensity",
  "block-trade-detector",
  "absorption-ratio",
]);
