import { createDiagnostic, type IndicatorOutputDefinition, type IndicatorOutputs, type MarketField, type TimeSeriesFrame, type TimeSeriesIndicatorDefinition } from '../../contracts';
import { ema, percentileRank, rollingStdDev, sma } from '../../core/series';
import { rollingSum } from '../../core/rolling/sum';
import { defineCategoryIndicator, type CategoryIndicatorSpec, type CategoryParameterRule } from '../shared/category-definition';
import * as indicatorLogic from './logic';
import { Params, Rules, category, change, divergence, event, integer, number, overlay, pane, profile, rollingVwap, trades, typical } from './shared';

interface Input { backlogId: string; id: string; name: string; ar: string; description: string; defaults?: Params; rules?: Rules; outputs: readonly IndicatorOutputDefinition[]; minimumHistory: number; compute: CategoryIndicatorSpec<Params>['compute']; requiredFields?: readonly MarketField[]; availabilityMessage?: string; confirmationDelay?: number; }
function define(input: Input): TimeSeriesIndicatorDefinition<Params> { return defineCategoryIndicator({ backlogId: input.backlogId, id: input.id, category: 'volume-flow', name: input.name, description: { en: input.description, ar: input.ar }, requiredFields: input.requiredFields ?? ['volume'], defaults: input.defaults ?? {}, parameterRules: input.rules ?? {}, outputs: input.outputs, minimumHistory: input.minimumHistory, tags: ['volume', 'flow'], references: ['Ticknal canonical volume and flow specification'], repaintBehavior: input.confirmationDelay ? 'confirmed-with-delay' : 'none', confirmationDelay: input.confirmationDelay, availability: input.availabilityMessage ? () => createDiagnostic('DATA_FIELD_MISSING', 'indicator.data.capabilityUnavailable', { capability: input.availabilityMessage }) : undefined, compute: input.compute }); }
const unavailable = (frame: TimeSeriesFrame, outputs: readonly IndicatorOutputDefinition[]): IndicatorOutputs => Object.fromEntries(outputs.map((output) => [output.key, Array(frame.bars.length).fill(null)]));

const turnoverOutputs = [pane('turnover_ratio', 'Turnover ratio', 'percent')];
const spreadOutputs = [pane('spread', 'Spread', 'price'), pane('spread_bps', 'Spread', 'percent')];
const imbalanceOutputs = [pane('imbalance', 'Order book imbalance', 'percent')];
const deltaOutputs = [pane('delta', 'Volume delta', 'volume'), pane('cumulative_delta', 'Cumulative delta', 'volume')];

export const VOLUME_FLOW_DEFINITIONS: readonly TimeSeriesIndicatorDefinition<object>[] = Object.freeze([
  define({ backlogId: 'FLW-001', id: 'raw-volume', name: 'Raw volume', ar: 'حجم التداول الخام', description: 'Shares or units traded in each bar.', outputs: [pane('volume', 'Volume', 'volume')], minimumHistory: 1, compute: indicatorLogic.rawVolume }),
  define({ backlogId: 'FLW-002', id: 'volume-moving-average', name: 'Volume moving average', ar: 'متوسط حجم التداول', description: 'Simple moving average of bar volume.', defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('volume_ma', 'Volume average', 'volume')], minimumHistory: 20, compute: indicatorLogic.volumeMovingAverage }),
  define({ backlogId: 'FLW-003', id: 'relative-volume', name: 'Relative Volume (RVOL)', ar: 'الحجم النسبي', description: 'Current volume divided by its recent average.', defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('rvol_ratio', 'Relative volume')], minimumHistory: 20, compute: indicatorLogic.relativeVolume }),
  define({ backlogId: 'FLW-004', id: 'volume-percentile', name: 'Volume percentile', ar: 'الرتبة المئوية للحجم', description: 'Current volume ranked within its recent distribution.', defaults: { period: 100 }, rules: { period: integer() }, outputs: [pane('percentile_0_100', 'Volume percentile', 'rank')], minimumHistory: 100, compute: indicatorLogic.volumePercentile }),
  define({ backlogId: 'FLW-005', id: 'volume-rate-of-change', name: 'Volume Rate of Change', ar: 'معدل تغير الحجم', description: 'Percentage change in volume over a selected period.', defaults: { period: 12 }, rules: { period: integer() }, outputs: [pane('volume_roc_pct', 'Volume ROC', 'percent')], minimumHistory: 13, compute: indicatorLogic.volumeRateOfChange }),
  define({ backlogId: 'FLW-006', id: 'on-balance-volume', name: 'On-Balance Volume (OBV)', ar: 'حجم التداول المتوازن', description: 'Cumulative signed volume by close direction.', requiredFields: ['close', 'volume'], defaults: { smoothing: 1 }, rules: { smoothing: integer() }, outputs: [pane('obv', 'OBV', 'volume'), pane('smoothed_obv', 'Smoothed OBV', 'volume')], minimumHistory: 1, compute: indicatorLogic.onBalanceVolume }),
  define({ backlogId: 'FLW-007', id: 'accumulation-distribution-line', name: 'Accumulation/Distribution Line', ar: 'خط التجميع والتصريف', description: 'Cumulative close-location-weighted volume.', requiredFields: ['high', 'low', 'close', 'volume'], outputs: [pane('ad_line', 'A/D Line', 'volume')], minimumHistory: 1, compute: indicatorLogic.accumulationDistributionLine }),
  define({ backlogId: 'FLW-008', id: 'chaikin-money-flow', name: 'Chaikin Money Flow (CMF)', ar: 'تدفق أموال تشايكين', description: 'Rolling close-location volume divided by total volume.', requiredFields: ['high', 'low', 'close', 'volume'], defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('cmf', 'CMF')], minimumHistory: 20, compute: indicatorLogic.chaikinMoneyFlow }),
  define({ backlogId: 'FLW-009', id: 'chaikin-oscillator', name: 'Chaikin Oscillator', ar: 'مذبذب تشايكين', description: 'Fast-minus-slow EMA of the accumulation/distribution line.', requiredFields: ['high', 'low', 'close', 'volume'], defaults: { fast: 3, slow: 10 }, rules: { fast: integer(), slow: integer() }, outputs: [pane('oscillator', 'Chaikin Oscillator', 'volume')], minimumHistory: 10, compute: indicatorLogic.chaikinOscillator }),
  define({ backlogId: 'FLW-010', id: 'money-flow-index', name: 'Money Flow Index (MFI)', ar: 'مؤشر تدفق الأموال', description: 'Volume-weighted gain-loss oscillator.', requiredFields: ['high', 'low', 'close', 'volume'], defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('mfi_0_100', 'MFI', 'percent')], minimumHistory: 15, compute: indicatorLogic.moneyFlowIndex }),
  define({ backlogId: 'FLW-011', id: 'volume-price-trend', name: 'Volume Price Trend (VPT)', ar: 'اتجاه السعر والحجم', description: 'Cumulative volume multiplied by percentage price change.', requiredFields: ['close', 'volume'], outputs: [pane('vpt', 'VPT', 'volume')], minimumHistory: 2, compute: indicatorLogic.volumePriceTrend }),
  define({ backlogId: 'FLW-012', id: 'positive-volume-index', name: 'Positive Volume Index (PVI)', ar: 'مؤشر الحجم الإيجابي', description: 'Cumulative price index updated on higher-volume bars.', requiredFields: ['close', 'volume'], defaults: { signalPeriod: 255 }, rules: { signalPeriod: integer() }, outputs: [pane('pvi', 'PVI'), pane('signal', 'Signal')], minimumHistory: 2, compute: indicatorLogic.positiveVolumeIndex }),
  define({ backlogId: 'FLW-013', id: 'negative-volume-index', name: 'Negative Volume Index (NVI)', ar: 'مؤشر الحجم السلبي', description: 'Cumulative price index updated on lower-volume bars.', requiredFields: ['close', 'volume'], defaults: { signalPeriod: 255 }, rules: { signalPeriod: integer() }, outputs: [pane('nvi', 'NVI'), pane('signal', 'Signal')], minimumHistory: 2, compute: indicatorLogic.negativeVolumeIndex }),
  define({ backlogId: 'FLW-014', id: 'ease-of-movement', name: 'Ease of Movement (EOM)', ar: 'سهولة الحركة', description: 'Midpoint movement scaled by range and volume.', requiredFields: ['high', 'low', 'volume'], defaults: { period: 14, volumeScale: 1000000 }, rules: { period: integer(), volumeScale: integer(1, 1000000000) }, outputs: [pane('eom', 'EOM'), pane('smoothed_eom', 'Smoothed EOM')], minimumHistory: 15, compute: indicatorLogic.easeOfMovement }),
  define({ backlogId: 'FLW-015', id: 'force-index', name: 'Force Index', ar: 'مؤشر القوة', description: 'Price change multiplied by volume and exponentially smoothed.', requiredFields: ['close', 'volume'], defaults: { period: 13 }, rules: { period: integer() }, outputs: [pane('force_index', 'Force Index', 'volume')], minimumHistory: 14, compute: indicatorLogic.forceIndex }),
  define({ backlogId: 'FLW-016', id: 'elder-force-index', name: 'Elder Force Index', ar: 'مؤشر قوة إلدر', description: 'EMA-smoothed price-change times volume.', requiredFields: ['close', 'volume'], defaults: { period: 13 }, rules: { period: integer() }, outputs: [pane('force', 'Elder Force', 'volume')], minimumHistory: 14, compute: indicatorLogic.elderForceIndex }),
  define({ backlogId: 'FLW-017', id: 'price-volume-trend-divergence', name: 'Price Volume Trend divergence', ar: 'تباعد اتجاه السعر والحجم', description: 'Confirmed price disagreement with Volume Price Trend.', requiredFields: ['close', 'volume'], defaults: { left: 5, right: 5 }, rules: { left: integer(), right: integer() }, outputs: [event('bullish', 'Bullish divergence'), event('bearish', 'Bearish divergence')], minimumHistory: 12, confirmationDelay: 5, compute: indicatorLogic.priceVolumeTrendDivergence }),
  define({ backlogId: 'FLW-018', id: 'vwap', name: 'VWAP', ar: 'متوسط السعر المرجح بالحجم', description: 'Cumulative typical price weighted by volume.', requiredFields: ['high', 'low', 'close', 'volume'], outputs: [overlay('vwap', 'VWAP')], minimumHistory: 1, compute: indicatorLogic.vwap }),
  define({ backlogId: 'FLW-019', id: 'anchored-vwap', name: 'Anchored VWAP', ar: 'متوسط السعر المرجح المثبت', description: 'Volume-weighted average anchored to the first loaded observation.', requiredFields: ['high', 'low', 'close', 'volume'], outputs: [overlay('avwap', 'Anchored VWAP')], minimumHistory: 1, compute: indicatorLogic.anchoredVwap }),
  define({ backlogId: 'FLW-020', id: 'rolling-vwap', name: 'Rolling VWAP', ar: 'متوسط السعر المرجح المتحرك', description: 'Fixed-window volume-weighted average price.', requiredFields: ['high', 'low', 'close', 'volume'], defaults: { period: 20 }, rules: { period: integer() }, outputs: [overlay('rolling_vwap', 'Rolling VWAP')], minimumHistory: 20, compute: indicatorLogic.rollingVwap }),
  define({ backlogId: 'FLW-021', id: 'vwap-bands', name: 'VWAP bands', ar: 'نطاقات متوسط السعر المرجح', description: 'Rolling VWAP with price standard-deviation envelopes.', requiredFields: ['high', 'low', 'close', 'volume'], defaults: { period: 20, deviations: 2 }, rules: { period: integer(), deviations: number(0.1, 10) }, outputs: [overlay('vwap', 'VWAP'), overlay('upper', 'Upper'), overlay('lower', 'Lower')], minimumHistory: 20, compute: indicatorLogic.vwapBands }),
  define({ backlogId: 'FLW-022', id: 'volume-weighted-moving-average', name: 'Volume Weighted Moving Average (VWMA)', ar: 'المتوسط المتحرك المرجح بالحجم', description: 'Closing-price average weighted by bar volume.', requiredFields: ['close', 'volume'], defaults: { period: 20 }, rules: { period: integer() }, outputs: [overlay('vwma', 'VWMA')], minimumHistory: 20, compute: indicatorLogic.volumeWeightedMovingAverage }),
  define({ backlogId: 'FLW-023', id: 'volume-profile', name: 'Volume Profile', ar: 'ملف الحجم', description: 'Rolling volume distribution by price with point of control and value area.', requiredFields: ['high', 'low', 'close', 'volume'], defaults: { bins: 24, period: 100 }, rules: { bins: integer(4, 200), period: integer() }, outputs: [overlay('poc', 'Point of control'), overlay('vah', 'Value-area high'), overlay('val', 'Value-area low')], minimumHistory: 1, compute: indicatorLogic.volumeProfile }),
  define({ backlogId: 'FLW-024', id: 'visible-range-volume-profile', name: 'Visible Range Volume Profile', ar: 'ملف حجم النطاق المرئي', description: 'Volume profile over the frame supplied by the visible-range request.', requiredFields: ['high', 'low', 'close', 'volume'], defaults: { bins: 24 }, rules: { bins: integer(4, 200) }, outputs: [overlay('poc', 'Point of control'), overlay('vah', 'Value-area high'), overlay('val', 'Value-area low')], minimumHistory: 1, compute: indicatorLogic.visibleRangeVolumeProfile }),
  define({ backlogId: 'FLW-025', id: 'fixed-range-volume-profile', name: 'Fixed Range Volume Profile', ar: 'ملف حجم النطاق الثابت', description: 'Volume profile over a fixed trailing bar range.', requiredFields: ['high', 'low', 'close', 'volume'], defaults: { bins: 24, period: 100 }, rules: { bins: integer(4, 200), period: integer() }, outputs: [overlay('poc', 'Point of control'), overlay('vah', 'Value-area high'), overlay('val', 'Value-area low')], minimumHistory: 1, compute: indicatorLogic.fixedRangeVolumeProfile }),
  define({ backlogId: 'FLW-026', id: 'time-price-opportunity-profile', name: 'Time Price Opportunity profile', ar: 'ملف فرص السعر الزمنية', description: 'Time-at-price distribution with point of control and value area.', requiredFields: ['high', 'low', 'close'], defaults: { bins: 24, period: 100 }, rules: { bins: integer(4, 200), period: integer() }, outputs: [overlay('poc', 'Point of control'), overlay('vah', 'Value-area high'), overlay('val', 'Value-area low')], minimumHistory: 1, compute: indicatorLogic.timePriceOpportunityProfile }),
  define({ backlogId: 'FLW-027', id: 'average-trade-size', name: 'Average Trade Size', ar: 'متوسط حجم الصفقة', description: 'Traded value divided by verified trade count.', requiredFields: ['high', 'low', 'close', 'volume', 'trades'], defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('ats', 'Average trade size', 'price'), pane('average_ats', 'Average ATS', 'price'), pane('ratio', 'ATS ratio')], minimumHistory: 20, compute: indicatorLogic.averageTradeSize }),
  define({ backlogId: 'FLW-028', id: 'smart-money-flow', name: 'Smart Money Flow', ar: 'تدفق الأموال الذكية', description: 'Trade-size, volume, range, and close-location accumulation heuristic.', requiredFields: ['high', 'low', 'close', 'volume', 'trades'], defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('ats_ratio', 'ATS ratio'), pane('absorption', 'Absorption'), category('state', 'State'), event('marker', 'Smart-money event')], minimumHistory: 20, compute: indicatorLogic.smartMoneyFlow }),
  define({ backlogId: 'FLW-029', id: 'turnover', name: 'Turnover', ar: 'قيمة التداول', description: 'Typical price multiplied by volume with rolling total.', requiredFields: ['high', 'low', 'close', 'volume'], defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('turnover', 'Turnover', 'price'), pane('rolling_turnover', 'Rolling turnover', 'price')], minimumHistory: 1, compute: indicatorLogic.turnover }),
  define({ backlogId: 'FLW-030', id: 'turnover-velocity', name: 'Turnover velocity', ar: 'سرعة دوران الأسهم', description: 'Turnover relative to point-in-time free float.', defaults: { period: 20 }, rules: { period: integer() }, outputs: turnoverOutputs, minimumHistory: 20, availabilityMessage: 'point-in-time free float or shares outstanding', compute: indicatorLogic.turnoverVelocity }),
  define({ backlogId: 'FLW-031', id: 'amihud-illiquidity', name: 'Amihud Illiquidity', ar: 'عدم سيولة أميهود', description: 'Rolling mean absolute return divided by traded value.', requiredFields: ['close', 'volume'], defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('illiquidity', 'Amihud illiquidity')], minimumHistory: 21, compute: indicatorLogic.amihudIlliquidity }),
  define({ backlogId: 'FLW-032', id: 'vpin-proxy', name: 'Volume-synchronized probability of informed trading proxy', ar: 'مؤشر احتمالية التداول المطلع', description: 'Bulk-volume directional imbalance proxy over rolling bars.', requiredFields: ['close', 'volume'], defaults: { bucketBars: 20 }, rules: { bucketBars: integer(2) }, outputs: [pane('vpin_proxy', 'VPIN proxy', 'probability')], minimumHistory: 21, compute: indicatorLogic.vpinProxy }),
  define({ backlogId: 'FLW-033', id: 'bid-ask-spread', name: 'Bid-ask spread', ar: 'فارق العرض والطلب', description: 'Observed best-ask minus best-bid transaction cost.', outputs: spreadOutputs, minimumHistory: 1, availabilityMessage: 'licensed order-book bid and ask observations', compute: indicatorLogic.bidAskSpread }),
  define({ backlogId: 'FLW-034', id: 'order-book-imbalance', name: 'Order Book Imbalance', ar: 'اختلال دفتر الأوامر', description: 'Displayed bid-versus-ask liquidity imbalance.', defaults: { depthLevels: 5 }, rules: { depthLevels: integer() }, outputs: imbalanceOutputs, minimumHistory: 1, availabilityMessage: 'licensed order-book depth observations', compute: indicatorLogic.orderBookImbalance }),
  define({ backlogId: 'FLW-035', id: 'cumulative-volume-delta', name: 'Cumulative Volume Delta', ar: 'دلتا الحجم التراكمية', description: 'Buyer-initiated minus seller-initiated traded volume.', outputs: deltaOutputs, minimumHistory: 1, availabilityMessage: 'aggressor-classified transaction volume', compute: indicatorLogic.cumulativeVolumeDelta }),
  define({ backlogId: 'FLW-036', id: 'trade-intensity', name: 'Trade intensity', ar: 'كثافة التداول', description: 'Verified trade count and its ratio to recent normal.', requiredFields: ['trades'], defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('trades_rate', 'Trades per bar', 'count'), pane('relative_rate', 'Relative trade rate')], minimumHistory: 20, compute: indicatorLogic.tradeIntensity }),
  define({ backlogId: 'FLW-037', id: 'block-trade-detector', name: 'Block trade detector', ar: 'كاشف الصفقات الكبيرة', description: 'Flags unusually large average trade value per bar.', requiredFields: ['high', 'low', 'close', 'volume', 'trades'], defaults: { period: 100, percentileThreshold: 95 }, rules: { period: integer(), percentileThreshold: number(50, 100) }, outputs: [event('block_event', 'Block event'), pane('size_percentile', 'Size percentile', 'rank')], minimumHistory: 100, compute: indicatorLogic.blockTradeDetector }),
  define({ backlogId: 'FLW-038', id: 'absorption-ratio', name: 'Absorption ratio', ar: 'نسبة الامتصاص', description: 'Relative volume divided by relative trading range with directional state.', requiredFields: ['high', 'low', 'close', 'volume'], defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('absorption', 'Absorption'), category('state', 'State')], minimumHistory: 20, compute: indicatorLogic.absorptionRatio }),
]);

const DATA_GATED_BACKLOG_IDS = new Set(['FLW-030', 'FLW-033', 'FLW-034', 'FLW-035']);
export const VOLUME_FLOW_OPERATIONAL_DEFINITIONS = Object.freeze(VOLUME_FLOW_DEFINITIONS.filter((definition) => !DATA_GATED_BACKLOG_IDS.has(definition.backlogId)));
