import { createDiagnostic,type IndicatorOutputDefinition,type MarketField,type TimeSeriesIndicatorDefinition } from '../../contracts';
import { defineCategoryIndicator,type CategoryIndicatorSpec } from '../shared/category-definition';
import * as indicatorLogic from './logic';
import { category,event,integer,number,pane,type Params,type Rules } from './shared';
interface Input{backlogId:string;id:string;name:string;ar:string;description:string;defaults:Params;rules:Rules;outputs:readonly IndicatorOutputDefinition[];minimumHistory:number;requiredFields:readonly MarketField[];requiredSymbol?:string;unavailableCapability?:string;compute:CategoryIndicatorSpec<Params>['compute'];}
function define(input:Input):TimeSeriesIndicatorDefinition<Params>{return defineCategoryIndicator({backlogId:input.backlogId,id:input.id,category:"breadth",name:input.name,description:{en:input.description,ar:input.ar},requiredFields:input.requiredFields,defaults:input.defaults,parameterRules:input.rules,outputs:input.outputs,minimumHistory:input.minimumHistory,tags:["breadth",'data-bound'],references:['Ticknal canonical indicator program'],availability:(frame)=>input.unavailableCapability?createDiagnostic('DATA_FIELD_MISSING','indicator.data.capabilityUnavailable',{capability:input.unavailableCapability}):input.requiredSymbol&&!frame.meta.symbol.toUpperCase().includes(input.requiredSymbol)?createDiagnostic('DATA_FIELD_MISSING','indicator.data.capabilityUnavailable',{capability:'selected '+input.requiredSymbol+' index series'}):null,compute:input.compute});}
export const BREADTH_DEFINITIONS:readonly TimeSeriesIndicatorDefinition<object>[]=Object.freeze([
  define({backlogId:"BRD-001",id:"breadth-advance-decline-line",name:"Advance-Decline Line",ar:"مؤشر Advance-Decline Line",description:"Cumulative number of advancing stocks minus declining stocks.",defaults:{},rules:{},outputs:[pane("ad-line","AD line","dimensionless"),pane("daily-net-advances","daily net advances","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthAdvanceDeclineLine}),
  define({backlogId:"BRD-002",id:"breadth-advance-decline-ratio",name:"Advance-Decline Ratio",ar:"مؤشر Advance-Decline Ratio",description:"Advancers divided by decliners.",defaults:{},rules:{},outputs:[pane("ad-ratio","AD ratio","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthAdvanceDeclineRatio}),
  define({backlogId:"BRD-003",id:"breadth-advance-decline-percent",name:"Advance-Decline Percent",ar:"مؤشر Advance-Decline Percent",description:"Net advances as a percentage of active stocks.",defaults:{},rules:{},outputs:[pane("ad-percent","AD percent","percent")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthAdvanceDeclinePercent}),
  define({backlogId:"BRD-004",id:"breadth-up-down-volume",name:"Up-Down Volume",ar:"مؤشر Up-Down Volume",description:"Advancing volume versus declining volume.",defaults:{},rules:{},outputs:[pane("up-volume","up volume","dimensionless"),pane("down-volume","down volume","dimensionless"),pane("net-volume","net volume","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, BV",compute:indicatorLogic.breadthUpDownVolume}),
  define({backlogId:"BRD-005",id:"breadth-up-down-volume-ratio",name:"Up-Down Volume Ratio",ar:"مؤشر Up-Down Volume Ratio",description:"Advancing volume divided by declining volume.",defaults:{},rules:{},outputs:[pane("volume-ratio","volume ratio","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, BV",compute:indicatorLogic.breadthUpDownVolumeRatio}),
  define({backlogId:"BRD-006",id:"breadth-arms-index-trin",name:"Arms Index (TRIN)",ar:"مؤشر Arms Index (TRIN)",description:"Advance-decline ratio adjusted by up-down volume.",defaults:{},rules:{},outputs:[pane("trin","TRIN","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, BV",compute:indicatorLogic.breadthArmsIndexTrin}),
  define({backlogId:"BRD-007",id:"breadth-mcclellan-oscillator",name:"McClellan Oscillator",ar:"مؤشر McClellan Oscillator",description:"Smoothed net advances showing breadth momentum.",defaults:{},rules:{},outputs:[pane("oscillator","oscillator","dimensionless"),pane("fast","fast","dimensionless"),pane("slow","slow","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthMcclellanOscillator}),
  define({backlogId:"BRD-008",id:"breadth-mcclellan-summation-index",name:"McClellan Summation Index",ar:"مؤشر McClellan Summation Index",description:"Cumulative breadth trend from the McClellan Oscillator.",defaults:{},rules:{},outputs:[pane("summation-index","summation_index","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthMcclellanSummationIndex}),
  define({backlogId:"BRD-009",id:"breadth-new-highs-new-lows",name:"New Highs-New Lows",ar:"مؤشر New Highs-New Lows",description:"Difference between stocks making new highs and new lows.",defaults:{},rules:{},outputs:[pane("net-highs","net highs","dimensionless"),pane("highs","highs","dimensionless"),pane("lows","lows","dimensionless"),pane("lookback","lookback","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthNewHighsNewLows}),
  define({backlogId:"BRD-010",id:"breadth-high-low-logic-index",name:"High-Low Logic Index",ar:"مؤشر High-Low Logic Index",description:"Identifies unusual simultaneous new highs and lows.",defaults:{},rules:{},outputs:[pane("logic-index","logic_index","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthHighLowLogicIndex}),
  define({backlogId:"BRD-011",id:"breadth-percent-above-moving-average",name:"Percent Above Moving Average",ar:"مؤشر Percent Above Moving Average",description:"Share of stocks above a chosen SMA or EMA.",defaults:{},rules:{},outputs:[pane("percent-above","percent_above","percent"),pane("period","period","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthPercentAboveMovingAverage}),
  define({backlogId:"BRD-012",id:"breadth-bullish-percent-index",name:"Bullish Percent Index",ar:"مؤشر Bullish Percent Index",description:"Share of stocks with bullish point-and-figure states.",defaults:{},rules:{},outputs:[event("bullish-percent","bullish_percent")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthBullishPercentIndex}),
  define({backlogId:"BRD-013",id:"breadth-breadth-thrust",name:"Breadth Thrust",ar:"مؤشر Breadth Thrust",description:"Sudden shift from weak to broad participation.",defaults:{},rules:{},outputs:[pane("thrust-value","thrust_value","dimensionless"),event("trigger-event","trigger event")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthBreadthThrust}),
  define({backlogId:"BRD-014",id:"breadth-zweig-breadth-thrust",name:"Zweig Breadth Thrust",ar:"مؤشر Zweig Breadth Thrust",description:"Ten-day smoothed advance ratio with classic thrust thresholds.",defaults:{},rules:{},outputs:[pane("zbt","ZBT","dimensionless"),event("trigger","trigger")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthZweigBreadthThrust}),
  define({backlogId:"BRD-015",id:"breadth-absolute-breadth-index",name:"Absolute Breadth Index",ar:"مؤشر Absolute Breadth Index",description:"Absolute difference between advancing and declining issues.",defaults:{},rules:{},outputs:[pane("abi","ABI","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthAbsoluteBreadthIndex}),
  define({backlogId:"BRD-016",id:"breadth-breadth-momentum",name:"Breadth Momentum",ar:"مؤشر Breadth Momentum",description:"Rate of change of advance-decline participation.",defaults:{},rules:{},outputs:[pane("breadth-roc","breadth_roc","dimensionless"),pane("period","period","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthBreadthMomentum}),
  define({backlogId:"BRD-017",id:"breadth-sector-breadth",name:"Sector Breadth",ar:"مؤشر Sector Breadth",description:"Participation measures calculated separately for each EGX sector.",defaults:{},rules:{},outputs:[pane("ad-percent","AD percent","percent"),pane("percent-above-ma","percent above MA","percent"),pane("highs-lows","highs-lows","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX sectors, B",compute:indicatorLogic.breadthSectorBreadth}),
  define({backlogId:"BRD-018",id:"breadth-index-participation-score",name:"Index Participation Score",ar:"مؤشر Index Participation Score",description:"Percentage of index members confirming the index direction.",defaults:{},rules:{},outputs:[pane("score-0-100","score_0_100","dimensionless"),pane("confirmed-count","confirmed_count","count")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX index membership, B",compute:indicatorLogic.breadthIndexParticipationScore}),
  define({backlogId:"BRD-019",id:"breadth-equal-weight-versus-cap-weight-spread",name:"Equal-Weight versus Cap-Weight Spread",ar:"مؤشر Equal-Weight versus Cap-Weight Spread",description:"Shows whether large stocks or the broader market lead.",defaults:{},rules:{},outputs:[pane("return-spread","return_spread","percent"),category("trend","trend")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthEqualWeightVersusCapWeightSpread}),
  define({backlogId:"BRD-020",id:"breadth-median-stock-return",name:"Median Stock Return",ar:"مؤشر Median Stock Return",description:"Typical constituent return, less distorted by the largest names.",defaults:{},rules:{},outputs:[pane("median-return","median_return","percent"),pane("horizon","horizon","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthMedianStockReturn}),
  define({backlogId:"BRD-021",id:"breadth-cross-sectional-dispersion",name:"Cross-sectional dispersion",ar:"مؤشر Cross-sectional dispersion",description:"Spread of constituent returns across the market.",defaults:{},rules:{},outputs:[pane("dispersion","dispersion","dimensionless"),pane("percentile","percentile","percent")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthCrossSectionalDispersion}),
  define({backlogId:"BRD-022",id:"breadth-market-concentration",name:"Market Concentration",ar:"مؤشر Market Concentration",description:"Share of index move or market cap controlled by top constituents.",defaults:{},rules:{},outputs:[pane("top-5-top-10-concentration","top 5 and top 10 concentration","dimensionless"),pane("hhi","HHI","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthMarketConcentration}),
  define({backlogId:"BRD-023",id:"breadth-breadth-divergence",name:"Breadth Divergence",ar:"مؤشر Breadth Divergence",description:"Index makes a new high or low without matching breadth.",defaults:{},rules:{},outputs:[event("bullish","bullish"),event("bearish-divergence","bearish divergence")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX index and B",compute:indicatorLogic.breadthBreadthDivergence}),
  define({backlogId:"BRD-024",id:"breadth-volume-breadth-divergence",name:"Volume Breadth Divergence",ar:"مؤشر Volume Breadth Divergence",description:"Index direction disagrees with up-down volume.",defaults:{},rules:{},outputs:[event("bullish","bullish"),event("bearish-divergence","bearish divergence")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, BV",compute:indicatorLogic.breadthVolumeBreadthDivergence}),
  define({backlogId:"BRD-025",id:"breadth-participation-regime",name:"Participation Regime",ar:"مؤشر Participation Regime",description:"Composite state from advances, volume, highs-lows, and MA breadth.",defaults:{},rules:{},outputs:[pane("broad-bull","broad bull","dimensionless"),pane("narrow-bull","narrow bull","dimensionless"),pane("broad-bear","broad bear","dimensionless"),pane("narrow-bear","narrow bear","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"cross-sectional EGX universe breadth observations: EGX universe, B",compute:indicatorLogic.breadthParticipationRegime}),
]);
const OPERATIONAL=new Set<string>([]);
export const BREADTH_OPERATIONAL_DEFINITIONS=Object.freeze(BREADTH_DEFINITIONS.filter((definition)=>OPERATIONAL.has(definition.backlogId)));
