import type { IndicatorOutputDefinition, MarketField, TimeSeriesFrame, TimeSeriesIndicatorDefinition } from '../../contracts';
import { percentileRank, rollingMax, rollingMin, sma } from '../../core/series';
import { defineCategoryIndicator, type CategoryIndicatorSpec, type CategoryParameterRule } from '../shared/category-definition';
import * as indicatorLogic from './logic';
import { Params, Rules, bodies, category, direction, event, integer, number, pane } from './shared';

interface Input { backlogId: string; id: string; name: string; ar: string; description: string; defaults?: Params; rules?: Rules; outputs: readonly IndicatorOutputDefinition[]; minimumHistory: number; compute: CategoryIndicatorSpec<Params>['compute']; requiredFields?: readonly MarketField[]; }
function define(input: Input): TimeSeriesIndicatorDefinition<Params> { return defineCategoryIndicator({ backlogId: input.backlogId, id: input.id, category: 'price-action', name: input.name, description: { en: input.description, ar: input.ar }, requiredFields: input.requiredFields ?? ['open', 'high', 'low', 'close'], defaults: input.defaults ?? {}, parameterRules: input.rules ?? {}, outputs: input.outputs, minimumHistory: input.minimumHistory, tags: ['price-action', 'candlestick'], references: ['Ticknal canonical candlestick specification'], compute: input.compute }); }

export const PRICE_ACTION_DEFINITIONS: readonly TimeSeriesIndicatorDefinition<object>[] = Object.freeze([
  define({ backlogId: 'PAT-001', id: 'candle-anatomy', name: 'Candle Anatomy', ar: 'تشريح الشمعة', description: 'Body and wick proportions of each candle.', outputs: [pane('body_pct', 'Body'), pane('upper_wick_pct', 'Upper wick'), pane('lower_wick_pct', 'Lower wick'), category('direction', 'Direction')], minimumHistory: 1, compute: indicatorLogic.candleAnatomy }),
  define({ backlogId: 'PAT-002', id: 'doji-family', name: 'Doji family', ar: 'عائلة الدوجي', description: 'Small-body candles classified by wick geometry.', defaults: { bodyThresholdPct: 10 }, rules: { bodyThresholdPct: number(0, 50) }, outputs: [event('doji', 'Doji'), event('long_legged', 'Long-legged doji'), event('dragonfly', 'Dragonfly doji'), event('gravestone', 'Gravestone doji')], minimumHistory: 1, compute: indicatorLogic.dojiFamily }),
  define({ backlogId: 'PAT-003', id: 'hammer-hanging-man', name: 'Hammer and Hanging Man', ar: 'المطرقة والرجل المشنوق', description: 'Small body with a lower rejection wick, classified by trend context.', defaults: { contextPeriod: 5, wickRatio: 2 }, rules: { contextPeriod: integer(), wickRatio: number(1, 10) }, outputs: [event('hammer', 'Hammer'), event('hanging_man', 'Hanging Man')], minimumHistory: 6, compute: indicatorLogic.hammerHangingMan }),
  define({ backlogId: 'PAT-004', id: 'inverted-hammer-shooting-star', name: 'Inverted Hammer and Shooting Star', ar: 'المطرقة المقلوبة والشهاب', description: 'Small body with an upper rejection wick, classified by trend context.', defaults: { contextPeriod: 5, wickRatio: 2 }, rules: { contextPeriod: integer(), wickRatio: number(1, 10) }, outputs: [event('inverted_hammer', 'Inverted Hammer'), event('shooting_star', 'Shooting Star')], minimumHistory: 6, compute: indicatorLogic.invertedHammerShootingStar }),
  define({ backlogId: 'PAT-005', id: 'bullish-bearish-engulfing', name: 'Bullish and Bearish Engulfing', ar: 'الابتلاع الصعودي والهبوطي', description: 'Opposing candle body fully engulfed by the current body.', outputs: [event('bullish', 'Bullish engulfing'), event('bearish', 'Bearish engulfing')], minimumHistory: 2, compute: indicatorLogic.bullishBearishEngulfing }),
  define({ backlogId: 'PAT-006', id: 'harami', name: 'Harami', ar: 'هارامي', description: 'Small opposing body contained within the previous body.', outputs: [event('bullish', 'Bullish harami'), event('bearish', 'Bearish harami')], minimumHistory: 2, compute: indicatorLogic.harami }),
  define({ backlogId: 'PAT-007', id: 'piercing-dark-cloud', name: 'Piercing Line and Dark Cloud Cover', ar: 'الخط الثاقب والسحابة الداكنة', description: 'Two-candle reversal with configurable penetration into the prior body.', defaults: { penetrationPct: 50 }, rules: { penetrationPct: number(1, 100) }, outputs: [event('bullish', 'Piercing line'), event('bearish', 'Dark cloud cover')], minimumHistory: 2, compute: indicatorLogic.piercingDarkCloud }),
  define({ backlogId: 'PAT-008', id: 'morning-evening-star', name: 'Morning and Evening Star', ar: 'نجمة الصباح والمساء', description: 'Three-candle reversal with a small middle body.', defaults: { smallBodyRatio: 0.5 }, rules: { smallBodyRatio: number(0.05, 1) }, outputs: [event('bullish', 'Morning star'), event('bearish', 'Evening star')], minimumHistory: 3, compute: indicatorLogic.morningEveningStar }),
  define({ backlogId: 'PAT-009', id: 'three-soldiers-crows', name: 'Three White Soldiers and Three Black Crows', ar: 'الجنود البيض والغربان السود', description: 'Three consecutive strong directional candles.', outputs: [event('bullish', 'Three white soldiers'), event('bearish', 'Three black crows')], minimumHistory: 3, compute: indicatorLogic.threeSoldiersCrows }),
  define({ backlogId: 'PAT-010', id: 'marubozu', name: 'Marubozu', ar: 'ماروبوزو', description: 'Directional candle with very small total wick.', defaults: { wickTolerancePct: 5 }, rules: { wickTolerancePct: number(0, 30) }, outputs: [event('bullish', 'Bullish marubozu'), event('bearish', 'Bearish marubozu')], minimumHistory: 1, compute: indicatorLogic.marubozu }),
  define({ backlogId: 'PAT-011', id: 'inside-bar', name: 'Inside Bar', ar: 'الشمعة الداخلية', description: 'Current range contained by the previous range.', outputs: [event('inside_bar', 'Inside bar'), pane('mother_range', 'Mother range', 'price')], minimumHistory: 2, compute: indicatorLogic.insideBar }),
  define({ backlogId: 'PAT-012', id: 'outside-bar', name: 'Outside Bar', ar: 'الشمعة الخارجية', description: 'Current range exceeds the previous range on both sides.', outputs: [event('outside_bar', 'Outside bar'), category('direction', 'Direction')], minimumHistory: 2, compute: indicatorLogic.outsideBar }),
  define({ backlogId: 'PAT-013', id: 'pin-bar', name: 'Pin Bar', ar: 'شمعة البن بار', description: 'Dominant rejection wick relative to body and opposite wick.', defaults: { wickRatio: 2 }, rules: { wickRatio: number(1, 10) }, outputs: [event('bullish', 'Bullish pin bar'), event('bearish', 'Bearish pin bar')], minimumHistory: 1, compute: indicatorLogic.pinBar }),
  define({ backlogId: 'PAT-014', id: 'tweezer-top-bottom', name: 'Tweezer Top and Bottom', ar: 'قمة وقاع الملقط', description: 'Consecutive highs or lows equal within a price tolerance.', defaults: { tolerancePct: 0.1 }, rules: { tolerancePct: number(0, 5) }, outputs: [event('top', 'Tweezer top'), event('bottom', 'Tweezer bottom')], minimumHistory: 2, compute: indicatorLogic.tweezerTopBottom }),
  define({ backlogId: 'PAT-015', id: 'gap-up-down', name: 'Gap Up and Gap Down', ar: 'فجوة صاعدة وهابطة', description: 'Full-range or opening gap relative to the previous bar.', outputs: [event('full_gap', 'Full gap'), event('partial_gap', 'Partial gap'), category('direction', 'Gap direction')], minimumHistory: 2, compute: indicatorLogic.gapUpDown }),
  define({ backlogId: 'PAT-016', id: 'nr4-nr7', name: 'NR4 and NR7', ar: 'أضيق نطاق 4 و7', description: 'Current range is the narrowest of the last four or seven bars.', outputs: [event('nr4', 'NR4'), event('nr7', 'NR7')], minimumHistory: 7, compute: indicatorLogic.nr4Nr7 }),
  define({ backlogId: 'PAT-017', id: 'wide-range-bar', name: 'Wide Range Bar', ar: 'شمعة واسعة النطاق', description: 'Range unusually large versus recent average and distribution.', defaults: { period: 20, ratioThreshold: 1.5 }, rules: { period: integer(), ratioThreshold: number(1, 10) }, outputs: [event('event', 'Wide range event'), pane('range_ratio', 'Range ratio', 'dimensionless'), pane('percentile', 'Range percentile', 'rank')], minimumHistory: 20, compute: indicatorLogic.wideRangeBar }),
  define({ backlogId: 'PAT-018', id: 'climax-volume-candle', name: 'Climax Volume Candle', ar: 'شمعة ذروة الحجم', description: 'Wide candle with extreme relative volume.', requiredFields: ['open', 'high', 'low', 'close', 'volume'], defaults: { period: 20, volumeRatio: 2, rangeRatio: 1.5 }, rules: { period: integer(), volumeRatio: number(1, 20), rangeRatio: number(1, 20) }, outputs: [event('bullish', 'Bullish climax'), event('bearish', 'Bearish climax'), event('exhaustion', 'Exhaustion candidate')], minimumHistory: 20, compute: indicatorLogic.climaxVolumeCandle }),
  define({ backlogId: 'PAT-019', id: 'reversal-candle-score', name: 'Reversal Candle Score', ar: 'درجة شمعة الانعكاس', description: 'Continuous rejection score from body, wick, gap, volume, and context.', requiredFields: ['open', 'high', 'low', 'close', 'volume'], defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('score', 'Reversal score', 'percent'), pane('wick_component', 'Wick component'), pane('volume_component', 'Volume component')], minimumHistory: 20, compute: indicatorLogic.reversalCandleScore }),
  define({ backlogId: 'PAT-020', id: 'multi-candle-pattern-filter', name: 'Multi-candle Pattern Filter', ar: 'مرشح نمط متعدد الشموع', description: 'Configurable sequence of consecutive directional candle bodies.', defaults: { length: 3, minimumBodyPct: 50 }, rules: { length: integer(2, 20), minimumBodyPct: number(0, 100) }, outputs: [event('sequence_match', 'Sequence match'), category('direction', 'Sequence direction')], minimumHistory: 3, compute: indicatorLogic.multiCandlePatternFilter }),
]);
