import type { IndicatorOutputDefinition, IndicatorOutputs, MarketField, TimeSeriesFrame, TimeSeriesIndicatorDefinition } from '../../contracts';
import { atr, ema, linearRegressionEnd, percentileRank, rma, rollingMax, rollingMin, rollingStdDev, sma, trueRange } from '../../core/series';
import { rollingSum } from '../../core/rolling/sum';
import { defineCategoryIndicator, type CategoryIndicatorSpec, type CategoryParameterRule } from '../shared/category-definition';
import * as indicatorLogic from './logic';
import { Params, Rules, bollinger, category, change, event, integer, number, overlay, pane } from './shared';

interface Input { backlogId: string; id: string; name: string; ar: string; description: string; defaults: Params; rules: Rules; outputs: readonly IndicatorOutputDefinition[]; minimumHistory: number; compute: CategoryIndicatorSpec<Params>['compute']; requiredFields?: readonly MarketField[]; }
function define(input: Input): TimeSeriesIndicatorDefinition<Params> {
  return defineCategoryIndicator({ backlogId: input.backlogId, id: input.id, category: 'volatility', name: input.name,
    description: { en: input.description, ar: input.ar }, requiredFields: input.requiredFields ?? ['close'], defaults: input.defaults,
    parameterRules: input.rules, outputs: input.outputs, minimumHistory: input.minimumHistory, tags: ['volatility', 'risk'],
    references: ['Ticknal canonical formula specification'], compute: input.compute });
}

export const VOLATILITY_DEFINITIONS: readonly TimeSeriesIndicatorDefinition<object>[] = Object.freeze([
  define({ backlogId: 'VOL-001', id: 'average-true-range', name: 'Average True Range (ATR)', ar: 'متوسط النطاق الحقيقي', description: 'Wilder average of gap-adjusted true range.', requiredFields: ['high', 'low', 'close'], defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('atr', 'ATR', 'price')], minimumHistory: 14, compute: indicatorLogic.averageTrueRange }),
  define({ backlogId: 'VOL-002', id: 'atr-percentage', name: 'ATR percentage', ar: 'نسبة متوسط النطاق الحقيقي', description: 'Average true range divided by closing price.', requiredFields: ['high', 'low', 'close'], defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('atr_pct', 'ATR percentage', 'percent')], minimumHistory: 14, compute: indicatorLogic.atrPercentage }),
  define({ backlogId: 'VOL-003', id: 'normalized-atr', name: 'Normalized ATR', ar: 'متوسط النطاق الحقيقي المعياري', description: 'ATR percentage ranked against its own history.', requiredFields: ['high', 'low', 'close'], defaults: { atrPeriod: 14, rankPeriod: 100 }, rules: { atrPeriod: integer(), rankPeriod: integer() }, outputs: [pane('normalized_atr', 'Normalized ATR', 'rank')], minimumHistory: 114, compute: indicatorLogic.normalizedAtr }),
  define({ backlogId: 'VOL-004', id: 'bollinger-bands', name: 'Bollinger Bands', ar: 'نطاقات بولينجر', description: 'Simple moving average with standard-deviation envelopes.', defaults: { period: 20, deviation: 2 }, rules: { period: integer(), deviation: number(0.1, 10) }, outputs: [overlay('middle', 'Middle band'), overlay('upper', 'Upper band'), overlay('lower', 'Lower band')], minimumHistory: 20, compute: indicatorLogic.bollingerBands }),
  define({ backlogId: 'VOL-005', id: 'bollinger-percent-b', name: 'Bollinger Percent B', ar: 'نسبة بولينجر المئوية', description: 'Close position relative to Bollinger envelopes.', defaults: { period: 20, deviation: 2 }, rules: { period: integer(), deviation: number(0.1, 10) }, outputs: [pane('percent_b', 'Percent B', 'percent')], minimumHistory: 20, compute: indicatorLogic.bollingerPercentB }),
  define({ backlogId: 'VOL-006', id: 'bollinger-bandwidth', name: 'Bollinger Bandwidth', ar: 'عرض نطاقات بولينجر', description: 'Bollinger envelope width as a percentage of the middle band.', defaults: { period: 20, deviation: 2 }, rules: { period: integer(), deviation: number(0.1, 10) }, outputs: [pane('bandwidth_pct', 'Bandwidth', 'percent')], minimumHistory: 20, compute: indicatorLogic.bollingerBandwidth }),
  define({ backlogId: 'VOL-007', id: 'bollinger-squeeze', name: 'Bollinger Squeeze', ar: 'انضغاط بولينجر', description: 'Bandwidth percentile and low-volatility squeeze state.', defaults: { period: 20, deviation: 2, rankPeriod: 100, threshold: 20 }, rules: { period: integer(), deviation: number(0.1, 10), rankPeriod: integer(), threshold: number(0, 100) }, outputs: [event('squeeze_state', 'Squeeze'), pane('percentile', 'Bandwidth percentile', 'rank')], minimumHistory: 120, compute: indicatorLogic.bollingerSqueeze }),
  define({ backlogId: 'VOL-008', id: 'keltner-channels', name: 'Keltner Channels', ar: 'قنوات كيلتنر', description: 'EMA center with ATR envelopes.', requiredFields: ['high', 'low', 'close'], defaults: { period: 20, multiplier: 2 }, rules: { period: integer(), multiplier: number(0.1, 20) }, outputs: [overlay('middle', 'Middle'), overlay('upper', 'Upper'), overlay('lower', 'Lower')], minimumHistory: 20, compute: indicatorLogic.keltnerChannels }),
  define({ backlogId: 'VOL-009', id: 'ttm-squeeze-state', name: 'TTM Squeeze style state', ar: 'حالة انضغاط تي تي إم', description: 'Bollinger-inside-Keltner compression state with detrended momentum.', requiredFields: ['high', 'low', 'close'], defaults: { period: 20, bollingerDeviation: 2, keltnerMultiplier: 1.5 }, rules: { period: integer(), bollingerDeviation: number(0.1, 10), keltnerMultiplier: number(0.1, 20) }, outputs: [event('squeeze_on', 'Squeeze on'), event('squeeze_off', 'Squeeze off'), pane('momentum', 'Momentum', 'price')], minimumHistory: 20, compute: indicatorLogic.ttmSqueezeState }),
  define({ backlogId: 'VOL-010', id: 'donchian-channels', name: 'Donchian Channels', ar: 'قنوات دونشيان', description: 'Rolling highest high and lowest low channel.', requiredFields: ['high', 'low'], defaults: { period: 20 }, rules: { period: integer() }, outputs: [overlay('upper', 'Upper'), overlay('lower', 'Lower'), overlay('middle', 'Middle')], minimumHistory: 20, compute: indicatorLogic.donchianChannels }),
  define({ backlogId: 'VOL-011', id: 'price-channel', name: 'Price Channel', ar: 'قناة السعر', description: 'Rolling close-price high, low, and midpoint.', defaults: { period: 20 }, rules: { period: integer() }, outputs: [overlay('upper', 'Upper'), overlay('lower', 'Lower'), overlay('middle', 'Middle')], minimumHistory: 20, compute: indicatorLogic.priceChannel }),
  define({ backlogId: 'VOL-012', id: 'standard-deviation', name: 'Standard Deviation', ar: 'الانحراف المعياري', description: 'Population standard deviation of closing prices.', defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('stdev', 'Standard deviation', 'price')], minimumHistory: 20, compute: indicatorLogic.standardDeviation }),
  define({ backlogId: 'VOL-013', id: 'historical-volatility', name: 'Historical Volatility', ar: 'التقلب التاريخي', description: 'Annualized standard deviation of logarithmic returns.', defaults: { period: 20, annualization: 252 }, rules: { period: integer(), annualization: integer() }, outputs: [pane('volatility_pct', 'Historical volatility', 'percent')], minimumHistory: 21, compute: indicatorLogic.historicalVolatility }),
  define({ backlogId: 'VOL-014', id: 'parkinson-volatility', name: 'Parkinson Volatility', ar: 'تقلب باركنسون', description: 'Annualized high-low range volatility estimator.', requiredFields: ['high', 'low'], defaults: { period: 20, annualization: 252 }, rules: { period: integer(), annualization: integer() }, outputs: [pane('volatility_pct', 'Parkinson volatility', 'percent')], minimumHistory: 20, compute: indicatorLogic.parkinsonVolatility }),
  define({ backlogId: 'VOL-015', id: 'garman-klass-volatility', name: 'Garman-Klass Volatility', ar: 'تقلب جارمان كلاس', description: 'OHLC volatility estimator using range and open-to-close movement.', requiredFields: ['open', 'high', 'low', 'close'], defaults: { period: 20, annualization: 252 }, rules: { period: integer(), annualization: integer() }, outputs: [pane('volatility_pct', 'Garman-Klass volatility', 'percent')], minimumHistory: 20, compute: indicatorLogic.garmanKlassVolatility }),
  define({ backlogId: 'VOL-016', id: 'rogers-satchell-volatility', name: 'Rogers-Satchell Volatility', ar: 'تقلب روجرز ساتشيل', description: 'Drift-robust OHLC volatility estimator.', requiredFields: ['open', 'high', 'low', 'close'], defaults: { period: 20, annualization: 252 }, rules: { period: integer(), annualization: integer() }, outputs: [pane('volatility_pct', 'Rogers-Satchell volatility', 'percent')], minimumHistory: 20, compute: indicatorLogic.rogersSatchellVolatility }),
  define({ backlogId: 'VOL-017', id: 'yang-zhang-volatility', name: 'Yang-Zhang Volatility', ar: 'تقلب يانج تشانج', description: 'Combined overnight, open-close, and Rogers-Satchell estimator.', requiredFields: ['open', 'high', 'low', 'close'], defaults: { period: 20, annualization: 252 }, rules: { period: integer(2), annualization: integer() }, outputs: [pane('volatility_pct', 'Yang-Zhang volatility', 'percent')], minimumHistory: 21, compute: indicatorLogic.yangZhangVolatility }),
  define({ backlogId: 'VOL-018', id: 'chaikin-volatility', name: 'Chaikin Volatility', ar: 'تقلب تشايكين', description: 'Rate of change of an EMA of the high-low range.', requiredFields: ['high', 'low'], defaults: { emaPeriod: 10, rocPeriod: 10 }, rules: { emaPeriod: integer(), rocPeriod: integer() }, outputs: [pane('chaikin_volatility', 'Chaikin volatility', 'percent')], minimumHistory: 20, compute: indicatorLogic.chaikinVolatility }),
  define({ backlogId: 'VOL-019', id: 'relative-volatility-index', name: 'Relative Volatility Index (RVI)', ar: 'مؤشر التقلب النسبي', description: 'RSI-style ratio of upward and downward standard deviation.', defaults: { period: 14, smoothing: 14 }, rules: { period: integer(), smoothing: integer() }, outputs: [pane('rvi_0_100', 'RVI', 'percent')], minimumHistory: 28, compute: indicatorLogic.relativeVolatilityIndex }),
  define({ backlogId: 'VOL-020', id: 'ulcer-index', name: 'Ulcer Index', ar: 'مؤشر القرحة', description: 'Root mean square downside drawdown from rolling highs.', defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('ulcer_index', 'Ulcer Index', 'percent')], minimumHistory: 27, compute: indicatorLogic.ulcerIndex }),
  define({ backlogId: 'VOL-021', id: 'choppiness-index', name: 'Choppiness Index', ar: 'مؤشر التذبذب الجانبي', description: 'Log-scaled true-range sum relative to the rolling price range.', requiredFields: ['high', 'low', 'close'], defaults: { period: 14 }, rules: { period: integer(2) }, outputs: [pane('choppiness_0_100', 'Choppiness', 'percent')], minimumHistory: 14, compute: indicatorLogic.choppinessIndex }),
  define({ backlogId: 'VOL-022', id: 'volatility-percentile', name: 'Volatility percentile', ar: 'الرتبة المئوية للتقلب', description: 'Short historical volatility ranked within its recent history.', defaults: { volatilityPeriod: 20, rankPeriod: 100, annualization: 252 }, rules: { volatilityPeriod: integer(), rankPeriod: integer(), annualization: integer() }, outputs: [pane('percentile_0_100', 'Volatility percentile', 'rank')], minimumHistory: 121, compute: indicatorLogic.volatilityPercentile }),
  define({ backlogId: 'VOL-023', id: 'volatility-regime', name: 'Volatility regime', ar: 'نظام التقلب', description: 'Low, normal, high, or extreme state from volatility percentile.', defaults: { volatilityPeriod: 20, rankPeriod: 100 }, rules: { volatilityPeriod: integer(), rankPeriod: integer() }, outputs: [category('state', 'Volatility regime')], minimumHistory: 121, compute: indicatorLogic.volatilityRegime }),
  define({ backlogId: 'VOL-024', id: 'range-expansion-index', name: 'Range Expansion Index (REI)', ar: 'مؤشر توسع النطاق', description: 'Directional range expansion divided by absolute range expansion.', requiredFields: ['high', 'low'], defaults: { period: 8, comparison: 2 }, rules: { period: integer(), comparison: integer() }, outputs: [pane('rei', 'REI', 'percent')], minimumHistory: 11, compute: indicatorLogic.rangeExpansionIndex }),
  define({ backlogId: 'VOL-025', id: 'average-daily-range', name: 'Average Daily Range (ADR)', ar: 'متوسط النطاق اليومي', description: 'Simple average of high-low range and its percentage of close.', requiredFields: ['high', 'low', 'close'], defaults: { period: 14 }, rules: { period: integer() }, outputs: [pane('adr', 'ADR', 'price'), pane('adr_pct', 'ADR percentage', 'percent')], minimumHistory: 14, compute: indicatorLogic.averageDailyRange }),
  define({ backlogId: 'VOL-026', id: 'expected-move-from-volatility', name: 'Expected move from volatility', ar: 'الحركة المتوقعة من التقلب', description: 'Annualized historical volatility translated into a confidence price range.', defaults: { period: 20, annualization: 252, horizon: 5, confidencePct: 95 }, rules: { period: integer(), annualization: integer(), horizon: integer(), confidencePct: number(50, 99.9) }, outputs: [overlay('upper', 'Expected upper'), overlay('lower', 'Expected lower')], minimumHistory: 21, compute: indicatorLogic.expectedMoveFromVolatility }),
  define({ backlogId: 'VOL-027', id: 'atr-trailing-stop', name: 'ATR trailing stop', ar: 'وقف متحرك بمتوسط النطاق الحقيقي', description: 'Direction-aware trailing stop separated from close by an ATR multiple.', requiredFields: ['high', 'low', 'close'], defaults: { period: 14, multiplier: 3 }, rules: { period: integer(), multiplier: number(0.1, 20) }, outputs: [overlay('stop_line', 'Stop line'), category('direction', 'Direction', 'overlay')], minimumHistory: 14, compute: indicatorLogic.atrTrailingStop }),
  define({ backlogId: 'VOL-028', id: 'chandelier-exit', name: 'Chandelier Exit', ar: 'خروج تشاندلير', description: 'ATR exits anchored to rolling highs and lows.', requiredFields: ['high', 'low', 'close'], defaults: { period: 22, multiplier: 3 }, rules: { period: integer(), multiplier: number(0.1, 20) }, outputs: [overlay('long_exit', 'Long exit'), overlay('short_exit', 'Short exit')], minimumHistory: 22, compute: indicatorLogic.chandelierExit }),
  define({ backlogId: 'VOL-029', id: 'volatility-stop', name: 'Volatility Stop', ar: 'وقف التقلب', description: 'ATR stop that flips when close crosses the active stop.', requiredFields: ['high', 'low', 'close'], defaults: { period: 14, multiplier: 2 }, rules: { period: integer(), multiplier: number(0.1, 20) }, outputs: [overlay('stop', 'Volatility stop'), category('state', 'State', 'overlay')], minimumHistory: 14, compute: indicatorLogic.volatilityStop }),
  define({ backlogId: 'VOL-030', id: 'highest-lowest-range-ratio', name: 'Highest-lowest range ratio', ar: 'نسبة نطاق الأعلى والأدنى', description: 'Short rolling price range divided by a longer rolling range.', requiredFields: ['high', 'low'], defaults: { short: 5, long: 20 }, rules: { short: integer(), long: integer() }, outputs: [pane('expansion_ratio', 'Expansion ratio')], minimumHistory: 20, compute: indicatorLogic.highestLowestRangeRatio }),
  define({ backlogId: 'VOL-031', id: 'gap-volatility', name: 'Gap volatility', ar: 'تقلب الفجوات', description: 'Average absolute, positive, and negative opening gaps.', requiredFields: ['open', 'close'], defaults: { period: 20 }, rules: { period: integer() }, outputs: [pane('average_gap', 'Average gap', 'percent'), pane('positive_gap', 'Positive gap', 'percent'), pane('negative_gap', 'Negative gap', 'percent')], minimumHistory: 21, compute: indicatorLogic.gapVolatility }),
  define({ backlogId: 'VOL-032', id: 'realized-semivolatility', name: 'Realized semivolatility', ar: 'شبه التقلب المحقق', description: 'Annualized upside and downside volatility from signed returns.', defaults: { period: 20, annualization: 252 }, rules: { period: integer(), annualization: integer() }, outputs: [pane('upside_vol', 'Upside volatility', 'percent'), pane('downside_vol', 'Downside volatility', 'percent')], minimumHistory: 21, compute: indicatorLogic.realizedSemivolatility }),
]);
