import { createDiagnostic,type IndicatorOutputDefinition,type MarketField,type TimeSeriesIndicatorDefinition } from '../../contracts';
import { defineCategoryIndicator,type CategoryIndicatorSpec } from '../shared/category-definition';
import * as indicatorLogic from './logic';
import { category,event,integer,number,pane,string,type Params,type Rules } from './shared';
interface Input{backlogId:string;id:string;name:string;ar:string;description:string;defaults:Params;rules:Rules;outputs:readonly IndicatorOutputDefinition[];minimumHistory:number;requiredFields:readonly MarketField[];requiredSymbol?:string;unavailableCapability?:string;requiredRoles?:readonly string[];compute:CategoryIndicatorSpec<Params>['compute'];}
function define(input:Input):TimeSeriesIndicatorDefinition<Params>{return defineCategoryIndicator({backlogId:input.backlogId,id:input.id,category:"egypt",name:input.name,description:{en:input.description,ar:input.ar},requiredFields:input.requiredFields,requiredCapabilities:input.requiredRoles?['numeric-series']:[],defaults:input.defaults,parameterRules:input.rules,outputs:input.outputs,minimumHistory:input.minimumHistory,tags:["egypt",'data-bound'],references:['Ticknal canonical indicator program'],availability:(frame,_parameters,inputs)=>{const missing=input.requiredRoles?.find((role)=>inputs.seriesByRole[role]===undefined);return missing?createDiagnostic('DATA_CAPABILITY_MISSING','indicator.data.requiredRoleMissing',{role:missing}):input.unavailableCapability?createDiagnostic('DATA_FIELD_MISSING','indicator.data.capabilityUnavailable',{capability:input.unavailableCapability}):input.requiredSymbol&&!frame.meta.symbol.toUpperCase().includes(input.requiredSymbol)?createDiagnostic('DATA_FIELD_MISSING','indicator.data.capabilityUnavailable',{capability:'selected '+input.requiredSymbol+' index series'}):null;},compute:input.compute});}
export const EGYPT_DEFINITIONS:readonly TimeSeriesIndicatorDefinition<object>[]=Object.freeze([
  define({backlogId:"EGY-001",id:"egypt-egx30-return-trend",name:"EGX30 Return and Trend",ar:"مؤشر EGX30 Return and Trend",description:"Performance and technical state of Egypt's large-cap benchmark.",defaults:{"period":20},rules:{period:integer(2)},outputs:[pane("return_pct","Return","percent"),category("trend","Trend"),pane("volatility_pct","Volatility","percent"),pane("drawdown_pct","Drawdown","percent")],minimumHistory:21,requiredFields:["close"],requiredSymbol:"EGX30",compute:indicatorLogic.egyptEgx30ReturnTrend}),
  define({backlogId:"EGY-002",id:"egypt-egx70-return-trend",name:"EGX70 Return and Trend",ar:"مؤشر EGX70 Return and Trend",description:"Performance and technical state of the smaller-company benchmark.",defaults:{"period":20},rules:{period:integer(2)},outputs:[pane("return_pct","Return","percent"),category("trend","Trend"),pane("volatility_pct","Volatility","percent"),pane("drawdown_pct","Drawdown","percent")],minimumHistory:21,requiredFields:["close"],requiredSymbol:"EGX70",compute:indicatorLogic.egyptEgx70ReturnTrend}),
  define({backlogId:"EGY-003",id:"egypt-egx100-return-trend",name:"EGX100 Return and Trend",ar:"مؤشر EGX100 Return and Trend",description:"Broad benchmark performance and state.",defaults:{"period":20},rules:{period:integer(2)},outputs:[pane("return_pct","Return","percent"),category("trend","Trend"),pane("volatility_pct","Volatility","percent"),pane("drawdown_pct","Drawdown","percent")],minimumHistory:21,requiredFields:["close"],requiredSymbol:"EGX100",compute:indicatorLogic.egyptEgx100ReturnTrend}),
  define({backlogId:"EGY-004",id:"egypt-egx-index-breadth",name:"EGX Index Breadth",ar:"مؤشر EGX Index Breadth",description:"Participation of constituents behind each EGX index move.",defaults:{},rules:{},outputs:[pane("ad-percent","AD percent","percent"),pane("percent-above-ma","percent above MA","percent"),pane("highs-lows","highs-lows","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: Index membership, B",compute:indicatorLogic.egyptEgxIndexBreadth}),
  define({backlogId:"EGY-005",id:"egypt-egyptian-investor-net-flow",name:"Egyptian Investor Net Flow",ar:"مؤشر Egyptian Investor Net Flow",description:"Net buying or selling by Egyptian investors.",defaults:{},rules:{},outputs:[pane("daily-cumulative-net-flow","daily and cumulative net flow","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: EGX investor flows, M",compute:indicatorLogic.egyptEgyptianInvestorNetFlow}),
  define({backlogId:"EGY-006",id:"egypt-arab-investor-net-flow",name:"Arab Investor Net Flow",ar:"مؤشر Arab Investor Net Flow",description:"Net buying or selling by Arab investors.",defaults:{},rules:{},outputs:[pane("daily-cumulative-net-flow","daily and cumulative net flow","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: EGX investor flows, M",compute:indicatorLogic.egyptArabInvestorNetFlow}),
  define({backlogId:"EGY-007",id:"egypt-foreign-investor-net-flow",name:"Foreign Investor Net Flow",ar:"مؤشر Foreign Investor Net Flow",description:"Net buying or selling by non-Arab foreign investors.",defaults:{},rules:{},outputs:[pane("daily-cumulative-net-flow","daily and cumulative net flow","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: EGX investor flows, M",compute:indicatorLogic.egyptForeignInvestorNetFlow}),
  define({backlogId:"EGY-008",id:"egypt-institutional-versus-retail-flow",name:"Institutional versus Retail Flow",ar:"مؤشر Institutional versus Retail Flow",description:"Net participation split by investor type.",defaults:{},rules:{},outputs:[pane("institutional-retail-net-flow","institutional and retail net flow","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: EGX investor flows, M",compute:indicatorLogic.egyptInstitutionalVersusRetailFlow}),
  define({backlogId:"EGY-009",id:"egypt-investor-flow-z-score",name:"Investor Flow Z-score",ar:"مؤشر Investor Flow Z-score",description:"Whether current investor flows are unusually large.",defaults:{},rules:{},outputs:[pane("z-score","z-score","dimensionless"),pane("percentile","percentile","percent"),pane("period","period","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: EGX flow history, M",compute:indicatorLogic.egyptInvestorFlowZScore}),
  define({backlogId:"EGY-010",id:"egypt-flow-trend-and-persistence",name:"Flow Trend and Persistence",ar:"مؤشر Flow Trend and Persistence",description:"Whether a participant group has accumulated or sold for several sessions.",defaults:{},rules:{},outputs:[pane("rolling-sum","rolling sum","dimensionless"),pane("streak","streak","dimensionless"),category("trend","trend")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: EGX flow history, M",compute:indicatorLogic.egyptFlowTrendAndPersistence}),
  define({backlogId:"EGY-011",id:"egypt-flow-price-divergence",name:"Flow-Price Divergence",ar:"مؤشر Flow-Price Divergence",description:"Index rises during foreign selling or falls during accumulation.",defaults:{},rules:{},outputs:[category("divergence-state","divergence state"),pane("strength","strength","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: EGX index and flows, M",compute:indicatorLogic.egyptFlowPriceDivergence}),
  define({backlogId:"EGY-012",id:"egypt-sector-rotation-score",name:"Sector Rotation Score",ar:"مؤشر Sector Rotation Score",description:"Relative momentum, breadth, flow, and volatility by EGX sector.",defaults:{},rules:{},outputs:[pane("score","score","dimensionless"),pane("rank","rank","dimensionless"),category("quadrant","quadrant")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: EGX sectors, B and M",compute:indicatorLogic.egyptSectorRotationScore}),
  define({backlogId:"EGY-013",id:"egypt-industry-group-rotation",name:"Industry Group Rotation",ar:"مؤشر Industry Group Rotation",description:"Same rotation framework at the industry-group level.",defaults:{},rules:{},outputs:[pane("score","score","dimensionless"),pane("rank","rank","dimensionless"),category("quadrant","quadrant")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: EGX taxonomy, B",compute:indicatorLogic.egyptIndustryGroupRotation}),
  define({backlogId:"EGY-014",id:"egypt-sector-concentration-risk",name:"Sector Concentration Risk",ar:"مؤشر Sector Concentration Risk",description:"Dependence of a sector move on its largest constituents.",defaults:{},rules:{},outputs:[pane("concentration","concentration","dimensionless"),pane("contribution","contribution","dimensionless"),pane("breadth-gap","breadth gap","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: EGX sectors, B",compute:indicatorLogic.egyptSectorConcentrationRisk}),
  define({backlogId:"EGY-015",id:"egypt-egx-market-heat-score",name:"EGX Market Heat Score",ar:"مؤشر EGX Market Heat Score",description:"Composite of breadth, volume, volatility, momentum, and flows.",defaults:{},rules:{},outputs:[pane("score-0-100","score_0_100","dimensionless"),category("regime","regime")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: EGX universe, BVM",compute:indicatorLogic.egyptEgxMarketHeatScore}),
  define({backlogId:"EGY-016",id:"egypt-official-usd-egp-trend",name:"Official USD/EGP Trend",ar:"مؤشر Official USD/EGP Trend",description:"Trend, momentum, and volatility of the official exchange rate.",defaults:{period:20,annualization:252},rules:{period:integer(2),annualization:integer()},outputs:[pane("rate","rate","price"),pane("return","return","percent"),category("trend","trend"),pane("volatility","volatility","percent")],minimumHistory:21,requiredFields:["close"],requiredRoles:['usdEgp'],compute:indicatorLogic.egyptOfficialUsdEgpTrend}),
  define({backlogId:"EGY-017",id:"egypt-real-usd-egp-fair-value",name:"Real USD/EGP Fair Value",ar:"مؤشر Real USD/EGP Fair Value",description:"Purchasing-power-parity estimate from Egyptian and US CPI.",defaults:{},rules:{},outputs:[pane("fair-value","fair value","price"),pane("misvaluation-pct","misvaluation_pct","percent"),pane("confidence","confidence","probability")],minimumHistory:1,requiredFields:["close"],requiredRoles:['egyptCpiIndex','usCpiIndex','usdEgp'],compute:indicatorLogic.egyptRealUsdEgpFairValue}),
  define({backlogId:"EGY-018",id:"egypt-fx-devaluation-risk",name:"FX Devaluation Risk",ar:"مؤشر FX Devaluation Risk",description:"Composite risk state from FX, reserves, inflation, rates, and liquidity.",defaults:{},rules:{},outputs:[pane("risk-score","risk score","dimensionless"),category("state","state"),pane("drivers","drivers","count")],minimumHistory:13,requiredFields:["close"],requiredRoles:['usdEgp','m2','egyptHeadlineInflationYoY','cbePolicyRate','netInternationalReserves'],compute:indicatorLogic.egyptFxDevaluationRisk}),
  define({backlogId:"EGY-019",id:"egypt-parallel-market-fx-premium",name:"Parallel-Market FX Premium",ar:"مؤشر Parallel-Market FX Premium",description:"Difference between official and verifiable alternative FX prices.",defaults:{},rules:{},outputs:[pane("premium-pct","premium_pct","percent"),category("trend","trend")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: Licensed or verified FX data, M",compute:indicatorLogic.egyptParallelMarketFxPremium}),
  define({backlogId:"EGY-020",id:"egypt-adr-implied-usd-egp",name:"ADR-Implied USD/EGP",ar:"مؤشر ADR-Implied USD/EGP",description:"FX rate implied by Egyptian local shares and corresponding overseas receipts.",defaults:{},rules:{},outputs:[pane("implied-fx","implied FX","dimensionless"),pane("premium","premium","percent"),category("stale-data-flag","stale-data flag")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: ADR pairs and FX, BM",compute:indicatorLogic.egyptAdrImpliedUsdEgp}),
  define({backlogId:"EGY-021",id:"egypt-gold-in-egp-per-gram",name:"Gold in EGP per Gram",ar:"مؤشر Gold in EGP per Gram",description:"International gold translated through USD/EGP into local units.",defaults:{period:1},rules:{period:integer()},outputs:[pane("egp-per-gram","EGP per gram","price"),pane("return","return","percent"),pane("premium","premium","percent")],minimumHistory:2,requiredFields:["close"],requiredRoles:['gold','usdEgp'],compute:indicatorLogic.egyptGoldInEgpPerGram}),
  define({backlogId:"EGY-022",id:"egypt-silver-in-egp-per-gram",name:"Silver in EGP per Gram",ar:"مؤشر Silver in EGP per Gram",description:"International silver translated through USD/EGP into local units.",defaults:{period:1},rules:{period:integer()},outputs:[pane("egp-per-gram","EGP per gram","price"),pane("return","return","percent"),pane("premium","premium","percent")],minimumHistory:2,requiredFields:["close"],requiredRoles:['silver','usdEgp'],compute:indicatorLogic.egyptSilverInEgpPerGram}),
  define({backlogId:"EGY-023",id:"egypt-local-gold-premium",name:"Local Gold Premium",ar:"مؤشر Local Gold Premium",description:"Local retail bullion price versus international implied EGP value.",defaults:{},rules:{},outputs:[pane("premium-pct","premium_pct","percent"),pane("spread","spread","percent")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: Verified local gold quotes, M",compute:indicatorLogic.egyptLocalGoldPremium}),
  define({backlogId:"EGY-024",id:"egypt-gold-versus-egp-hedge-effectiveness",name:"Gold versus EGP Hedge Effectiveness",ar:"مؤشر Gold versus EGP Hedge Effectiveness",description:"How well local gold has offset Egyptian inflation.",defaults:{},rules:{},outputs:[pane("correlation","correlation","dimensionless"),pane("hedge-ratio","hedge ratio","dimensionless"),pane("real-return","real return","percent")],minimumHistory:13,requiredFields:["close"],requiredRoles:['gold','usdEgp','egyptCpiIndex'],compute:indicatorLogic.egyptGoldVersusEgpHedgeEffectiveness}),
  define({backlogId:"EGY-025",id:"egypt-cbe-policy-rate",name:"CBE Policy Rate",ar:"مؤشر CBE Policy Rate",description:"Current rate, direction, and real rate after inflation.",defaults:{},rules:{},outputs:[pane("nominal-rate","nominal rate","percent"),pane("real-rate","real rate","percent"),pane("change","change","percent")],minimumHistory:1,requiredFields:["close"],requiredRoles:['cbePolicyRate','egyptHeadlineInflationYoY'],compute:indicatorLogic.egyptCbePolicyRate}),
  define({backlogId:"EGY-026",id:"egypt-yield-curve-slope",name:"Yield Curve Slope",ar:"مؤشر Yield Curve Slope",description:"Difference between 12-month and 3-month Egyptian Treasury yields.",defaults:{},rules:{},outputs:[pane("spreads","spreads","percent"),category("inversion-state","inversion state")],minimumHistory:1,requiredFields:["close"],requiredRoles:['treasury3mYield','treasury12mYield'],compute:indicatorLogic.egyptYieldCurveSlope}),
  define({backlogId:"EGY-027",id:"egypt-inflation-momentum",name:"Inflation Momentum",ar:"مؤشر Inflation Momentum",description:"Annual Egyptian CPI inflation and its month-over-month acceleration.",defaults:{},rules:{},outputs:[pane("cpi-momentum","CPI momentum","percent"),pane("acceleration","acceleration","percent")],minimumHistory:13,requiredFields:["close"],requiredRoles:['egyptCpiIndex'],compute:indicatorLogic.egyptInflationMomentum}),
  define({backlogId:"EGY-028",id:"egypt-real-equity-return",name:"Real Equity Return",ar:"مؤشر Real Equity Return",description:"EGX return after Egyptian inflation.",defaults:{},rules:{},outputs:[pane("real-return","real return","percent"),pane("real-drawdown","real drawdown","percent")],minimumHistory:13,requiredFields:["close"],requiredRoles:['egyptCpiIndex'],compute:indicatorLogic.egyptRealEquityReturn}),
  define({backlogId:"EGY-029",id:"egypt-m2-liquidity-growth",name:"M2 Liquidity Growth",ar:"مؤشر M2 Liquidity Growth",description:"Growth and acceleration of Egyptian broad money.",defaults:{monthPeriod:1,yearPeriod:12},rules:{monthPeriod:integer(),yearPeriod:integer()},outputs:[pane("yoy","YoY","percent"),pane("mom","MoM","percent"),pane("acceleration","acceleration","percent")],minimumHistory:13,requiredFields:["close"],requiredRoles:['m2'],compute:indicatorLogic.egyptM2LiquidityGrowth}),
  define({backlogId:"EGY-030",id:"egypt-liquidity-versus-egx-divergence",name:"Liquidity versus EGX Divergence",ar:"مؤشر Liquidity versus EGX Divergence",description:"Difference between money growth and equity-market performance.",defaults:{period:12,liquidityPeriod:1},rules:{period:integer(2),liquidityPeriod:integer()},outputs:[pane("divergence","divergence","percent"),pane("rolling-beta","rolling beta","dimensionless")],minimumHistory:13,requiredFields:["close"],requiredRoles:['m2'],compute:indicatorLogic.egyptLiquidityVersusEgxDivergence}),
  define({backlogId:"EGY-031",id:"egypt-fund-discount-or-premium",name:"Fund Discount or Premium",ar:"مؤشر Fund Discount or Premium",description:"Fund market price versus reported NAV where both exist.",defaults:{},rules:{},outputs:[pane("premium-discount-pct","premium_discount_pct","percent"),pane("z-score","z-score","dimensionless")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: Listed funds and NAV",compute:indicatorLogic.egyptFundDiscountOrPremium}),
  define({backlogId:"EGY-032",id:"egypt-fund-tracking-difference",name:"Fund Tracking Difference",ar:"مؤشر Fund Tracking Difference",description:"Fund return minus its user-selected benchmark return.",defaults:{period:60,annualization:252,benchmarkSymbol:'EGX30'},rules:{period:integer(2),annualization:integer(),benchmarkSymbol:string()},outputs:[pane("active-return","active return","percent"),pane("tracking-error","tracking error","percent")],minimumHistory:61,requiredFields:["close"],requiredRoles:['benchmark'],compute:indicatorLogic.egyptFundTrackingDifference}),
  define({backlogId:"EGY-033",id:"egypt-egx-trading-activity-pulse",name:"EGX Trading Activity Pulse",ar:"مؤشر EGX Trading Activity Pulse",description:"Composite of turnover, trades count, active tickers, and volume breadth.",defaults:{},rules:{},outputs:[pane("pulse-0-100","pulse_0_100","dimensionless"),category("state","state")],minimumHistory:1,requiredFields:["close"],unavailableCapability:"authenticated Egypt market or macro series required by this definition: EGX trade statistics, BVT",compute:indicatorLogic.egyptEgxTradingActivityPulse}),
  define({backlogId:"EGY-034",id:"egypt-suspension-staleness-flag",name:"Suspension and Staleness Flag",ar:"مؤشر Suspension and Staleness Flag",description:"Warns when an asset has missing sessions, stale NAV, or suspended trading.",defaults:{"staleBars":3},rules:{staleBars:integer(1,100)},outputs:[event("stale","Stale"),pane("missing_bars","Missing bars","count"),category("last_valid_time","Last valid time")],minimumHistory:1,requiredFields:["close"],compute:indicatorLogic.egyptSuspensionStalenessFlag}),
  define({backlogId:"EGY-035",id:"egypt-corporate-action-integrity-flag",name:"Corporate Action Integrity Flag",ar:"مؤشر Corporate Action Integrity Flag",description:"Identifies price discontinuities that may require split or dividend adjustment.",defaults:{"thresholdPct":30},rules:{thresholdPct:number(1,500)},outputs:[event("suspected_event","Suspected event"),pane("gap_pct","Gap","percent"),category("adjusted_state","Adjustment state")],minimumHistory:2,requiredFields:["close"],compute:indicatorLogic.egyptCorporateActionIntegrityFlag}),
  define({backlogId:"EGY-036",id:"egypt-egp-purchasing-power-index",name:"EGP Purchasing Power Index",ar:"مؤشر EGP Purchasing Power Index",description:"Indexed value of one EGP after cumulative inflation.",defaults:{},rules:{},outputs:[pane("purchasing-power","purchasing_power","dimensionless"),pane("loss-pct","loss_pct","percent")],minimumHistory:1,requiredFields:["close"],requiredRoles:['egyptCpiIndex'],compute:indicatorLogic.egyptEgpPurchasingPowerIndex}),
]);
const OPERATIONAL=new Set([
  'EGY-001','EGY-002','EGY-003','EGY-016','EGY-021','EGY-022',
  'EGY-017','EGY-018','EGY-024','EGY-025','EGY-026','EGY-027','EGY-028',
  'EGY-029','EGY-030','EGY-032','EGY-034','EGY-035','EGY-036',
]);
export const EGYPT_OPERATIONAL_DEFINITIONS=Object.freeze(EGYPT_DEFINITIONS.filter((definition)=>OPERATIONAL.has(definition.backlogId)));
