import { createDiagnostic, type IndicatorOutputDefinition, type TimeSeriesIndicatorDefinition } from '../../contracts';
import { defineCategoryIndicator, type CategoryIndicatorSpec } from '../shared/category-definition';
import * as indicatorLogic from './logic';
import { category, event, integer, number, overlay, pane, type Params, type Rules } from './shared';

interface Input { backlogId: string; id: string; name: string; ar: string; description: string; defaults: Params; rules: Rules; outputs: readonly IndicatorOutputDefinition[]; minimumHistory: number; repaintBehavior: CategoryIndicatorSpec<Params>['repaintBehavior']; confirmationDelay: number; unavailableCapability?: string; compute: CategoryIndicatorSpec<Params>['compute']; }
function define(input: Input): TimeSeriesIndicatorDefinition<Params> { return defineCategoryIndicator({ backlogId: input.backlogId, id: input.id, category: 'cycles', name: input.name, description: { en: input.description, ar: input.ar }, requiredFields: ['close'], defaults: input.defaults, parameterRules: input.rules, outputs: input.outputs, minimumHistory: input.minimumHistory, tags: ['cycles', 'signal-processing'], references: ['John F. Ehlers digital signal processing methods', 'Ticknal canonical cycle specification'], repaintBehavior: input.repaintBehavior, confirmationDelay: input.confirmationDelay, availability: input.unavailableCapability ? () => createDiagnostic('DATA_FIELD_MISSING', 'indicator.data.capabilityUnavailable', { capability: input.unavailableCapability }) : undefined, compute: input.compute }); }

export const CYCLE_DEFINITIONS: readonly TimeSeriesIndicatorDefinition<object>[] = Object.freeze([
  define({ backlogId: 'CYC-001', id: 'even-better-sinewave', name: "Even Better Sinewave", ar: "موجة جيبية محسنة", description: "Low-lag normalized cycle wave with a one-bar projection and reversal events.", defaults: {"period":20}, rules: { period: integer(4) }, outputs: [pane('wave', 'Wave', 'dimensionless'), pane('projected', 'Projected', 'dimensionless'), event('reversal_up', 'Up reversal'), event('reversal_down', 'Down reversal')], minimumHistory: 24, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.evenBetterSinewave }),
  define({ backlogId: 'CYC-002', id: 'ehlers-sinewave', name: "Ehlers Sinewave", ar: "موجة إهلرز الجيبية", description: "Dominant-cycle phase transformed into sine and leading-sine curves.", defaults: {"window":48,"minPeriod":8,"maxPeriod":40}, rules: { window: integer(16), minPeriod: integer(4), maxPeriod: integer(8) }, outputs: [pane('sine', 'Sine', 'dimensionless'), pane('lead_sine', 'Lead sine', 'dimensionless'), pane('phase', 'Phase', 'dimensionless')], minimumHistory: 48, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.ehlersSinewave }),
  define({ backlogId: 'CYC-003', id: 'hilbert-transform-dominant-cycle-period', name: "Hilbert Transform Dominant Cycle Period", ar: "فترة الدورة المهيمنة بتحويل هيلبرت", description: "Rolling spectral phase estimate of the dominant market cycle.", defaults: {"window":48,"minPeriod":8,"maxPeriod":40}, rules: { window: integer(16), minPeriod: integer(4), maxPeriod: integer(8) }, outputs: [pane('dominant_period', 'Dominant period', 'count')], minimumHistory: 48, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.hilbertTransformDominantCyclePeriod }),
  define({ backlogId: 'CYC-004', id: 'hilbert-transform-trend-mode', name: "Hilbert Transform Trend Mode", ar: "وضع الاتجاه بتحويل هيلبرت", description: "Separates trend and cycle modes using dominant-period movement efficiency.", defaults: {"window":48,"minPeriod":8,"maxPeriod":40}, rules: { window: integer(16), minPeriod: integer(4), maxPeriod: integer(8) }, outputs: [event('trend_mode', 'Trend mode'), event('cycle_mode', 'Cycle mode')], minimumHistory: 48, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.hilbertTransformTrendMode }),
  define({ backlogId: 'CYC-005', id: 'mesa-adaptive-moving-average', name: "MESA Adaptive Moving Average (MAMA)", ar: "المتوسط المتحرك المتكيف ميسا", description: "Phase-rate adaptive average with a slower following average.", defaults: {"window":48,"minPeriod":8,"maxPeriod":40,"fastLimit":0.5,"slowLimit":0.05}, rules: { window: integer(16), minPeriod: integer(4), maxPeriod: integer(8), fastLimit: number(0.01,1), slowLimit: number(0.001,1) }, outputs: [overlay('mama', 'MAMA'), overlay('fama', 'FAMA'), event('cross_up', 'Cross up'), event('cross_down', 'Cross down')], minimumHistory: 48, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.mesaAdaptiveMovingAverage }),
  define({ backlogId: 'CYC-006', id: 'cyber-cycle', name: "Cyber Cycle", ar: "الدورة السيبرانية", description: "Recursive Ehlers cycle oscillator with a lagged trigger.", defaults: {"period":20,"alpha":0.07}, rules: { period: integer(4), alpha: number(0.001,1) }, outputs: [pane('cycle', 'Cycle', 'dimensionless'), pane('trigger', 'Trigger', 'dimensionless'), pane('period', 'Period', 'count')], minimumHistory: 6, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.cyberCycle }),
  define({ backlogId: 'CYC-007', id: 'roofing-filter', name: "Roofing Filter", ar: "مرشح السقف", description: "Two-pole high-pass followed by a two-pole super smoother.", defaults: {"highPassPeriod":48,"lowPassPeriod":10}, rules: { highPassPeriod: integer(4), lowPassPeriod: integer(2) }, outputs: [pane('filtered_series', 'Filtered series', 'dimensionless'), pane('high_pass', 'High pass', 'dimensionless')], minimumHistory: 48, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.roofingFilter }),
  define({ backlogId: 'CYC-008', id: 'super-smoother-filter', name: "Super Smoother Filter", ar: "مرشح التنعيم الفائق", description: "One- or two-pole low-lag digital low-pass filter.", defaults: {"period":10,"poles":2}, rules: { period: integer(2), poles: integer(1,2) }, outputs: [overlay('smoothed_series', 'Smoothed series')], minimumHistory: 3, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.superSmootherFilter }),
  define({ backlogId: 'CYC-009', id: 'two-pole-high-pass-filter', name: "Two-pole High-Pass Filter", ar: "مرشح تمرير عال ثنائي القطب", description: "Second-order filter that removes slow trend components.", defaults: {"period":20}, rules: { period: integer(4) }, outputs: [pane('high_pass', 'High pass', 'dimensionless')], minimumHistory: 3, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.twoPoleHighPassFilter }),
  define({ backlogId: 'CYC-010', id: 'band-pass-filter', name: "Band-Pass Filter", ar: "مرشح تمرير نطاقي", description: "High- and low-pass cascade isolating movement near a selected period.", defaults: {"period":20,"bandwidth":0.3}, rules: { period: integer(4), bandwidth: number(0.05,0.9) }, outputs: [pane('band_pass', 'Band pass', 'dimensionless'), pane('trigger', 'Trigger', 'dimensionless'), pane('period', 'Period', 'count')], minimumHistory: 24, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.bandPassFilter }),
  define({ backlogId: 'CYC-011', id: 'decycler', name: "Decycler", ar: "مزيل الدورات", description: "Super-smoothed trend remaining after shorter cycles are removed.", defaults: {"period":20}, rules: { period: integer(4) }, outputs: [overlay('decycler', 'Decycler')], minimumHistory: 3, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.decycler }),
  define({ backlogId: 'CYC-012', id: 'decycler-oscillator', name: "Decycler Oscillator", ar: "مذبذب إزالة الدورات", description: "Percentage deviation of price from its decycled trend.", defaults: {"period":20}, rules: { period: integer(4) }, outputs: [pane('oscillator', 'Oscillator', 'percent')], minimumHistory: 3, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.decyclerOscillator }),
  define({ backlogId: 'CYC-013', id: 'instantaneous-trendline', name: "Instantaneous Trendline", ar: "خط الاتجاه اللحظي", description: "Low-lag recursive trendline with a two-bar trigger.", defaults: {"alpha":0.07}, rules: { alpha: number(0.001,1) }, outputs: [overlay('itrend', 'Instantaneous trend'), overlay('trigger', 'Trigger')], minimumHistory: 7, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.instantaneousTrendline }),
  define({ backlogId: 'CYC-014', id: 'autocorrelation-periodogram', name: "Autocorrelation Periodogram", ar: "مخطط الارتباط الذاتي الدوري", description: "Rolling dominant period and normalized spectral power.", defaults: {"window":64,"minPeriod":8,"maxPeriod":48}, rules: { window: integer(20), minPeriod: integer(4), maxPeriod: integer(8) }, outputs: [pane('power', 'Power', 'dimensionless'), pane('dominant_period', 'Dominant period', 'count')], minimumHistory: 64, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.autocorrelationPeriodogram }),
  define({ backlogId: 'CYC-015', id: 'fourier-dominant-cycle', name: "Fourier dominant cycle", ar: "الدورة المهيمنة بفورييه", description: "Rolling discrete Fourier search for dominant period, amplitude, and phase.", defaults: {"window":64,"minPeriod":8,"maxPeriod":48}, rules: { window: integer(20), minPeriod: integer(4), maxPeriod: integer(8) }, outputs: [pane('dominant_period', 'Dominant period', 'count'), pane('amplitude', 'Amplitude', 'dimensionless'), pane('phase', 'Phase', 'dimensionless')], minimumHistory: 64, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.fourierDominantCycle }),
  define({ backlogId: 'CYC-016', id: 'goertzel-cycle-detector', name: "Goertzel Cycle Detector", ar: "كاشف دورات جورتزل", description: "Goertzel power at a selected period with a rolling dominant-period scan.", defaults: {"window":64,"targetPeriod":20,"minPeriod":8,"maxPeriod":48}, rules: { window: integer(20), targetPeriod: integer(4), minPeriod: integer(4), maxPeriod: integer(8) }, outputs: [pane('target_power', 'Target power', 'dimensionless'), pane('dominant_period', 'Dominant period', 'count')], minimumHistory: 64, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.goertzelCycleDetector }),
  define({ backlogId: 'CYC-017', id: 'wavelet-energy', name: "Wavelet energy", ar: "طاقة المويجات", description: "Haar-like short, medium, and long scale energy decomposition.", defaults: {"short":4,"medium":12,"long":32}, rules: { short: integer(2), medium: integer(4), long: integer(8) }, outputs: [pane('short_energy', 'Short energy', 'dimensionless'), pane('medium_energy', 'Medium energy', 'dimensionless'), pane('long_energy', 'Long energy', 'dimensionless'), category('dominant_scale', 'Dominant scale')], minimumHistory: 32, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.waveletEnergy }),
  define({ backlogId: 'CYC-018', id: 'hodrick-prescott-trend-cycle', name: "Hodrick-Prescott trend and cycle", ar: "اتجاه ودورة هودريك بريسكوت", description: "Penalized second-difference trend and residual cycle component.", defaults: {"lambda":1600}, rules: { lambda: number(0.1,1000000) }, outputs: [overlay('trend', 'Trend'), pane('cycle', 'Cycle', 'dimensionless')], minimumHistory: 3, repaintBehavior: 'provisional-latest', confirmationDelay: 0, compute: indicatorLogic.hodrickPrescottTrendCycle }),
  define({ backlogId: 'CYC-019', id: 'baxter-king-cycle-filter', name: "Baxter-King cycle filter", ar: "مرشح دورة باكستر كينغ", description: "Symmetric finite band-pass filter with zero-sum Baxter-King weights.", defaults: {"lowPeriod":6,"highPeriod":32,"leadLag":12}, rules: { lowPeriod: integer(2), highPeriod: integer(4), leadLag: integer(2) }, outputs: [pane('cycle_component', 'Cycle component', 'dimensionless')], minimumHistory: 25, repaintBehavior: 'confirmed-with-delay', confirmationDelay: 12, compute: indicatorLogic.baxterKingCycleFilter }),
  define({ backlogId: 'CYC-020', id: 'christiano-fitzgerald-filter', name: "Christiano-Fitzgerald filter", ar: "مرشح كريستيانو فيتزجيرالد", description: "Practical asymmetric band-pass approximation for trend-cycle separation.", defaults: {"lowPeriod":6,"highPeriod":32}, rules: { lowPeriod: integer(2), highPeriod: integer(4) }, outputs: [overlay('trend', 'Trend'), pane('cycle', 'Cycle', 'dimensionless')], minimumHistory: 32, repaintBehavior: 'provisional-latest', confirmationDelay: 0, compute: indicatorLogic.christianoFitzgeraldFilter }),
  define({ backlogId: 'CYC-021', id: 'seasonal-return-profile', name: "Seasonal return profile", ar: "ملف العائد الموسمي", description: "Expanding weekday return mean, win rate, and sample count without lookahead.", defaults: {}, rules: {  }, outputs: [pane('seasonal_mean', 'Seasonal mean', 'percent'), pane('win_rate', 'Win rate', 'percent'), pane('sample_count', 'Sample count', 'count')], minimumHistory: 2, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.seasonalReturnProfile }),
  define({ backlogId: 'CYC-022', id: 'ramadan-holiday-seasonality', name: "Ramadan and holiday seasonality", ar: "موسمية رمضان والعطلات", description: "Egyptian calendar-event return and volume profile requiring verified calendar annotations.", defaults: {}, rules: {  }, outputs: [pane('average_return', 'Average return', 'percent'), pane('volume_ratio', 'Volume ratio', 'dimensionless'), pane('sample_count', 'Sample count', 'count')], minimumHistory: 2, repaintBehavior: 'none', confirmationDelay: 0, unavailableCapability: "verified Egypt Ramadan and exchange-holiday calendar annotations", compute: indicatorLogic.ramadanHolidaySeasonality }),
  define({ backlogId: 'CYC-023', id: 'cycle-phase-state', name: "Cycle phase state", ar: "حالة طور الدورة", description: "Dominant-cycle phase mapped to rising, peak, falling, and trough states.", defaults: {"window":48,"minPeriod":8,"maxPeriod":40}, rules: { window: integer(16), minPeriod: integer(4), maxPeriod: integer(8) }, outputs: [category('phase_state', 'Phase state'), pane('phase_angle', 'Phase angle', 'dimensionless')], minimumHistory: 48, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.cyclePhaseState }),
  define({ backlogId: 'CYC-024', id: 'filter-bank-consensus', name: "Filter bank consensus", ar: "إجماع بنك المرشحات", description: "Agreement across short, medium, and long band-pass filters.", defaults: {"short":10,"medium":20,"long":40,"bandwidth":0.3}, rules: { short: integer(4), medium: integer(6), long: integer(8), bandwidth: number(0.05,0.9) }, outputs: [pane('score', 'Score', 'count'), category('dominant_horizon', 'Dominant horizon'), category('state', 'State')], minimumHistory: 44, repaintBehavior: 'none', confirmationDelay: 0, compute: indicatorLogic.filterBankConsensus }),
]);
const GATED = new Set(['CYC-022']);
export const CYCLE_OPERATIONAL_DEFINITIONS = Object.freeze(CYCLE_DEFINITIONS.filter((definition) => !GATED.has(definition.backlogId)));
