export interface SndukFundConfig {
  symbol: string;
  fundId: number;
  companyName: string;
  sector: 'Funds';
  industry: string;
  industryGroup?: string;
  subIndustry?: string;
  logoUrl?: string | null;
  currency?: string;
  isIslamic?: boolean;
}

export type SndukFund = SndukFundConfig;

export const ALL_SNDUK_FUNDS: SndukFundConfig[] = [
  {
    "symbol": "EBF",
    "fundId": 23,
    "companyName": "Ezdehar sharia compliant balanced Fund - FAB",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Balanced Funds",
    "subIndustry": "Acumen Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777939111896-8la9mqeydsi.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "AFB",
    "fundId": 52,
    "companyName": "National Bank of Egypt Fund 1 - Balanced Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Balanced Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777508615629-t9msj6qwgbk.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AHB",
    "fundId": 78,
    "companyName": "NBE Al Ahly Hayah Balanced Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Balanced Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777588592586-kpgi22eqn1.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "ASF",
    "fundId": 77,
    "companyName": "NBE Seventh Mutual Fund (Fund of Egyptian Funds)",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Balanced Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777587847166-w7cvk0q2xg9.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "SNF",
    "fundId": 28,
    "companyName": "Sanadi Fund - Bank NXT Balanced fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Balanced Funds",
    "subIndustry": "Azimut Egypt Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777721314059-l8zwaxn0w1g.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "QTF",
    "fundId": 27,
    "companyName": "Tawazon QNB Al Ahli 2 Balanced Fund Tawazon",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Balanced Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777508440597-rajhfnf65g.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BMF",
    "fundId": 87,
    "companyName": "Banque Misr First Mutual Fund ( Quarterly periodic income )",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Balanced Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777812205207-sbff7c9of1f.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CTF",
    "fundId": 22,
    "companyName": "Takamol Fund CIB - Commercial International Bank Balanced Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Balanced Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777585942485-3lbzl6urjms.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "ABB",
    "fundId": 161,
    "companyName": "Egyptian Agricultural Bank Fund 1 ( Al Massy )",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Balanced Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1784457717359-gfw1sora0jv.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "ABF",
    "fundId": 25,
    "companyName": "Al Thiqa Balanced fund - Credit Agricole Egypt fourth Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Balanced Funds",
    "subIndustry": "HC Securities & Investment",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778113180430-dfc97uclun7.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BMT",
    "fundId": 24,
    "companyName": "Al Baraka Bank shariah compliant balanced Fund - Al Motawzeen",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Balanced Funds",
    "subIndustry": "Naeem Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777721142939-rpgc4ua0ppe.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "NAF",
    "fundId": 26,
    "companyName": "NBK Al-Mizan Balanced Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Balanced Funds",
    "subIndustry": "NBK Capital Egypt",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777720573118-0mlne8qwcu8f.jpg",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "GUF",
    "fundId": 93,
    "companyName": "Guard Fund - Arab African International Bank",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Capital Preservation Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778110507540-uabxcd28p6.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CHF",
    "fundId": 47,
    "companyName": "Hemaya Fund CIB - Commercial International Bank Fund 4",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Capital Preservation Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777586389503-2829riyygrg.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "ECP",
    "fundId": 212,
    "companyName": "Etmnan Fund - FAB Misr",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Capital Preservation Funds",
    "subIndustry": "HC Securities & Investment",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1786463710114-lblu8wagf0h.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BSL",
    "fundId": 50,
    "companyName": "Beltone Fadda Silver Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Commodities Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777719168342-ldygxy4d1mb.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MFD",
    "fundId": 156,
    "companyName": "Fadda Mubasher Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Commodities Funds",
    "subIndustry": "Mubasher Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1783778237442-m4bdittdq4.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "RAF",
    "fundId": 114,
    "companyName": "Al Raeed Fund ( Pioneers Fund 1 )",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "A I M FOR FINANCIAL INVESTMENTS",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780182888821-osdee437i1c.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "TAM",
    "fundId": 136,
    "companyName": "Al Tameer Fund - Housing and Development Bank",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780757301430-4n6mmjl3mdg.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AGF",
    "fundId": 41,
    "companyName": "Gosour Equity Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778422456806-qyln08kehd.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "KSF",
    "fundId": 46,
    "companyName": "Kenz EGX33 Shariah Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778112727311-jud50e6336.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "K35",
    "fundId": 202,
    "companyName": "Kenz EGX35 LV Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1786012406012-8qstflfsokn.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "K70",
    "fundId": 164,
    "companyName": "Kenz EGX70 EWI Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1784989959920-ctaqfgmovxu.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AKO",
    "fundId": 151,
    "companyName": "Kenz Foras Equity Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1783002634421-diey3pgg80l.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "SHF",
    "fundId": 35,
    "companyName": "Shield Equity Fund - Arab African International Bank",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777284436073-ad7n5medoxr.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BSF",
    "fundId": 34,
    "companyName": "Bashayer Islamic fund - NBE & El Baraka Bank of Egypt fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777501938382-k8s5tvkk4i.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "ATE",
    "fundId": 84,
    "companyName": "National Bank of Egypt Fund 3 - Equity",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777643364928-ho1icxkfj4o.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AFE",
    "fundId": 85,
    "companyName": "National Bank of Egypt Fund 5",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777650956244-bor6rwbxjh9.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AND",
    "fundId": 79,
    "companyName": "NBE Second Mutual Fund 2",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777589414103-vt9t6uoe7wf.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "OTR",
    "fundId": 126,
    "companyName": "Odin Equity Fund Trend",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Alpha Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780433414819-qfrwv4ivfj.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AWP",
    "fundId": 121,
    "companyName": "Waffrah Plus Fund - Aspire Capital",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Aspire Capital Holding",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780326506669-ggmugr8kchi.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "PHF",
    "fundId": 54,
    "companyName": "Pharos Fund 1",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Aton Pharos Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777504181240-vk1z0bdi6i.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "KEB",
    "fundId": 132,
    "companyName": "Al Khabeer Fund - Export Development Bank of Egypt",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Azimut Egypt Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780588657983-dxvigzmr1mb.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "ALV",
    "fundId": 38,
    "companyName": "Azimut az-LV Low Volatility Equity Opportunities Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Azimut Egypt Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777722462109-jo8mtqvhhm.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AZO",
    "fundId": 6,
    "companyName": "Azimut Equity Opportunities Fund (az-fors)",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Azimut Egypt Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777940578320-h3wilr4n1lg.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "ASO",
    "fundId": 11,
    "companyName": "Azimut Opportunities Shariah AZ",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Azimut Egypt Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777723771842-f8cmp9yhoqr.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "SBA",
    "fundId": 117,
    "companyName": "Al Ajial Fund - Suez Canal Bank",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780236374707-fkjptpuv0pr.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "B70",
    "fundId": 138,
    "companyName": "Beltone B-70 Fund ( B70 )",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780835519593-l0gnuavseir.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BAL",
    "fundId": 40,
    "companyName": "Beltone B-Alpha Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777719250710-98s4lue9u47.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "B35",
    "fundId": 110,
    "companyName": "Beltone B35 Fund - EGX35 LV",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780164012798-29f6r751u.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BCO",
    "fundId": 101,
    "companyName": "Beltone Consumer Sectorial Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1779710309532-35whn0cx9f6.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BFF",
    "fundId": 75,
    "companyName": "Beltone Financial Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777719468209-8d60d8piuwc.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BIF",
    "fundId": 81,
    "companyName": "Beltone Industrial Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777719552985-0e3qp1ppfjj8.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BMM",
    "fundId": 2,
    "companyName": "Beltone Meya Meya (100/100) EGX100 Index Equity Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777719777573-ik5ft4zg42p.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BRE",
    "fundId": 49,
    "companyName": "Beltone Real Estate Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777719667382-1xpz129io5l.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BWA",
    "fundId": 1,
    "companyName": "Beltone Wafra EGX33 Shariah fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777547111377-na98mh042g.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "MGR",
    "fundId": 182,
    "companyName": "Menthum Grow Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1785418029795-hbdc40vmvlm.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MBF",
    "fundId": 127,
    "companyName": "MID BANK First Mutual Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780437662633-8mbk23n9erl.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CCM",
    "fundId": 63,
    "companyName": "Cairo Capital Momentum Cumulative Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CFH Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778112973935-b47ey3xfpva.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "WSF",
    "fundId": 31,
    "companyName": "Al Wefak Shariah Compliant Investment Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777537666904-os5rlgirdke.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "FCA",
    "fundId": 15,
    "companyName": "Aman Fund - Faisal & CIB shariah compliant Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777585837092-azgzpmdfa5r.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "BM4",
    "fundId": 5,
    "companyName": "Banque Misr Fourth Fund EL Hessn fund - Sharia Compliant",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777506405916-gidrmwj5pbe.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "BMS",
    "fundId": 102,
    "companyName": "Banque Misr Second Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1779981904752-wrrum2n2gld.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MTE",
    "fundId": 57,
    "companyName": "Banque Misr Third Mutual Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777554307875-g4e5dk1985e.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "C20",
    "fundId": 124,
    "companyName": "CI 20HD Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780359973867-a58l5riaers.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CCF",
    "fundId": 43,
    "companyName": "CI Consumer Sectorial Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777587362021-3x2i307931e.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CEX",
    "fundId": 62,
    "companyName": "CI Exporters Sectorial Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777587291012-3niva146mum.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CFF",
    "fundId": 64,
    "companyName": "CI Financial and Fintech Sectoral Fund - CFF",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777587403310-4oqeae5jone.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CIP",
    "fundId": 55,
    "companyName": "CI IPO Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777586588721-y854np6nak.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CRE",
    "fundId": 135,
    "companyName": "CI Real Estate Sectoral Fund ( CRE )",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780741475557-77vw5jhpya5.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CTT",
    "fundId": 94,
    "companyName": "CI Telecom & IT Sectoral Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778203937466-3v8aagzzzb5.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CI_QUANT",
    "fundId": 123,
    "companyName": "CI The Quant Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780357545756-9yoqpms6r0o.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CIF",
    "fundId": 99,
    "companyName": "Istithmar Fund - Commercial International Bank (CIB)",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1779549764768-j2pljto98q.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CME",
    "fundId": 82,
    "companyName": "Misr Equity Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777723153827-r1let4i63i.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "SSF",
    "fundId": 30,
    "companyName": "Sanabel Islamic Fund - ADIB Egypt & SAIB",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777499130777-2z6f9d246a9.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "BEF",
    "fundId": 148,
    "companyName": "Al Baraka Bank Islamic Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1782319998836-u6fj2quyi8s.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "KAE",
    "fundId": 60,
    "companyName": "Alpha Shariaa Compliant Equity Fund - KFH Bank",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777508982275-ij1ywywtf4p.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "AXF",
    "fundId": 76,
    "companyName": "Bank of Alexandria Mutual Fund 1",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777553977038-b940wmfqzav.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CEF",
    "fundId": 48,
    "companyName": "BDC First Fund (Equity Fund)",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777720226148-spswe52aky.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CAF",
    "fundId": 146,
    "companyName": "Credit Agricole Mutual Fund No. 1",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1782317427633-ydqpv6wfwff.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "HEF",
    "fundId": 103,
    "companyName": "EFG Hermes Equity Fund - Issuance 1",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1779984620048-tklqno44la.webp",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "HSE",
    "fundId": 139,
    "companyName": "EFG Hermes Islamic Equity Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780925249713-qjl17wn3uxo.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "FIF",
    "fundId": 100,
    "companyName": "Faisal Islamic Bank of Egypt Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1779553229185-cot1mb1r2a7.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "NHF",
    "fundId": 42,
    "companyName": "Helal Fund - Bank NXT ( Sharia Compliant )",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777506256429-iffycw7te6t.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "SA2",
    "fundId": 116,
    "companyName": "SAIB Bank Fund 2",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780233806619-04zv696c5474.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MOS",
    "fundId": 157,
    "companyName": "Misr Al Mostakbal Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "HC Securities & Investment",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1783866249209-x3tcz2rchbf.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "QTE",
    "fundId": 109,
    "companyName": "Tadawol QNB Equity Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "HC Securities & Investment",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780150686344-1472ly9e95g.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MEF",
    "fundId": 80,
    "companyName": "Mubasher Equity Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Mubasher Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777723378171-hdeoff1tpp7.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "NMF",
    "fundId": 95,
    "companyName": "Naeem Misr Sharia Equity Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Naeem Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778269533913-cy4829t1iz.jpeg",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "NHE",
    "fundId": 45,
    "companyName": "Al Hayah NBK Islamic Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "NBK Capital Egypt",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777720649048-51unqnwhrox.jpg",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "NEF",
    "fundId": 56,
    "companyName": "Namaa Equity Fund - NBK EGYPT",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "NBK Capital Egypt",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777720476750-usajtjeegf.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "NSF",
    "fundId": 39,
    "companyName": "Sahmy 70 Fund - NI Capital",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "NI Capital",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777722072878-tvmk5uo2e6.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "NSE",
    "fundId": 108,
    "companyName": "Sahmy Fund - NI Capital",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "NI Capital",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780148578030-4urf76wocw.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "EBK",
    "fundId": 131,
    "companyName": "Konooz fund - Export Development Bank of Egypt",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Prime Investments asset management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780585084936-k9pje6bsfyo.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "PNF",
    "fundId": 143,
    "companyName": "Prime Holding 1st Equity Fund ( Prime Nmw )",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Prime Investments asset management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1781542807946-x9tv6g0f7ad.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "SRF",
    "fundId": 188,
    "companyName": "Ruya Equity Fund - Sigma Capital",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Sigma Capital",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1785667937794-da2smldweb4.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "T70",
    "fundId": 92,
    "companyName": "Thndr T70 Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Thndr Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778108518699-nw9d0sby61r.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "ZEM",
    "fundId": 112,
    "companyName": "Zaldi El Masry Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Equity Funds",
    "subIndustry": "Zaldi Capital",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780171597273-jwlhkthqdb.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AFQ",
    "fundId": 130,
    "companyName": "Afaaq Fixed Income Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780579244962-miongu4fult.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BFI",
    "fundId": 3,
    "companyName": "Bareeq Fixed Income Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777555223856-9xk4ld7t3x5.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AGO",
    "fundId": 91,
    "companyName": "Gozoor Fixed Income Fund - AAIB",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777988756134-l4koxv0a4ka.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "IWA",
    "fundId": 61,
    "companyName": "Istsmar w Aman Fixed Income Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780582640744-l04gpwdahst.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AF9",
    "fundId": 128,
    "companyName": "National Bank of Egypt Fund 9 – El Waed",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780440457896-1xk6lqn06ml.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AEF",
    "fundId": 189,
    "companyName": "Azimut Fixed Income Fund - Edkhar AZ",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "Azimut Egypt Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1785677598389-htiamw0hrgn.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "ANF",
    "fundId": 33,
    "companyName": "Azimut Nasser Islamic Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "Azimut Egypt Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777940509278-yskz8hs0cio.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "COB",
    "fundId": 247,
    "companyName": "Beltone B-Cobonat Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1788693561142-lnr0rev5r7h.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BSC",
    "fundId": 122,
    "companyName": "Beltone B-Secure Fixed Income Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780335739192-fnmjixuj7du.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BBY",
    "fundId": 256,
    "companyName": "Beltone B-Yawmy Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1789810904358-r9vsvyrbpwl.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CCS",
    "fundId": 118,
    "companyName": "Stream Fixed Income Fund - Cairo Capital",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "CFH Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780312020858-z7zktudkza.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CFI",
    "fundId": 184,
    "companyName": "CI Asset Management Fixed Income Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1785421643449-b2krm145xe6.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "TCF",
    "fundId": 166,
    "companyName": "El Thabet Fixed Income Fund - Banque du Caire",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1784992251768-7bbuwxssgjw.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CTH",
    "fundId": 66,
    "companyName": "Thabat Fund CIB",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777586006043-v4iytts3y08.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "ATH",
    "fundId": 181,
    "companyName": "Bank of Alexandria Fixed Income Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1785415677156-h5sv0fmji87.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "GRA",
    "fundId": 12,
    "companyName": "Granite Fixed Income Fund EGP",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "Granite Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777721920879-y82f04z6jxc.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CMF",
    "fundId": 155,
    "companyName": "Mubasher Capital Daily Cumulative Return Fund - Cash Mubasher",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "Mubasher Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1783762691819-cs32lmh5vh.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "N15",
    "fundId": 111,
    "companyName": "NI Capital 15/30 Fixed Income Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "NI Capital",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780166204493-3c114vlhhg7.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "TFI",
    "fundId": 142,
    "companyName": "Target First Fixed Income Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "Target Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1781538536024-q3jonvq8qq.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "OZE",
    "fundId": 113,
    "companyName": "Maksab OZ Euro Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Fixed Income Funds",
    "subIndustry": "Zaldi Capital",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780174708822-ys3m7uokm0j.png",
    "currency": "EUR",
    "isIslamic": false
  },
  {
    "symbol": "BOU",
    "fundId": 134,
    "companyName": "Bond$ Fixed Income Fund (USD)",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "USD Fixed Income Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780699217408-z2jnolp5uv.png",
    "currency": "USD",
    "isIslamic": false
  },
  {
    "symbol": "AZ30",
    "fundId": 10,
    "companyName": "Azimut Istihqaq 2030 USD – Az-30 Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "USD Fixed Income Funds",
    "subIndustry": "Azimut Egypt Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777722497802-aoaaubhg3yp.png",
    "currency": "USD",
    "isIslamic": false
  },
  {
    "symbol": "BUS",
    "fundId": 67,
    "companyName": "Beltone Fixed Income USD Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "USD Fixed Income Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777589940667-876a72l613j.png",
    "currency": "USD",
    "isIslamic": false
  },
  {
    "symbol": "MUF",
    "fundId": 13,
    "companyName": "Menthum USD Fixed Income Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "USD Fixed Income Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777590365747-jlx2nnbwyu.webp",
    "currency": "USD",
    "isIslamic": false
  },
  {
    "symbol": "HFU",
    "fundId": 104,
    "companyName": "EFG Hermes Fixed Income Fund (USD)",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "USD Fixed Income Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780004766060-4m8lo1yjjq.jpeg",
    "currency": "USD",
    "isIslamic": false
  },
  {
    "symbol": "GUS",
    "fundId": 179,
    "companyName": "Granite USD Fixed Income Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "USD Fixed Income Funds",
    "subIndustry": "Granite Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1785410951791-f2p4b9x0kvb.png",
    "currency": "USD",
    "isIslamic": false
  },
  {
    "symbol": "MFU",
    "fundId": 187,
    "companyName": "Mubasher Fixed Income Fund USD",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "USD Fixed Income Funds",
    "subIndustry": "Mubasher Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1785664507452-z9ckg4gh7u.png",
    "currency": "USD",
    "isIslamic": false
  },
  {
    "symbol": "OZU",
    "fundId": 59,
    "companyName": "Maksab OZ USD - Fixed Income Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "USD Fixed Income Funds",
    "subIndustry": "Zaldi Capital",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777590817172-qx1p50wc109.png",
    "currency": "USD",
    "isIslamic": false
  },
  {
    "symbol": "ADF",
    "fundId": 53,
    "companyName": "Al Ahly Dahab Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Gold Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777587912769-0m35y8f5lyg.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AZG",
    "fundId": 7,
    "companyName": "Azimut Gold Fund - AZ Gold Islamic Shariah compliant",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Gold Funds",
    "subIndustry": "Azimut Egypt Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777538713543-q0uscbyqpyh.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "BSB",
    "fundId": 14,
    "companyName": "Beltone Sabayek Gold Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Gold Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777719308805-sj25ej85u9.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "SHK",
    "fundId": 211,
    "companyName": "El Shakmagya Bokra Gold Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Gold Funds",
    "subIndustry": "Bokra Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1786460261285-u2o76rs7zd.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "CGF",
    "fundId": 8,
    "companyName": "CIAM Gold Fund - Gold Masr ( Islamic Shariah compliant )",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Gold Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777586655542-2c3jd7uvcbi.jpg",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "HGF",
    "fundId": 105,
    "companyName": "EFG Hermes Gold Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Gold Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780007194758-mznwtaiux4b.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MGF",
    "fundId": 9,
    "companyName": "Dahab Mubasher  - Mubasher Evolve Gold Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Gold Funds",
    "subIndustry": "Mubasher Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777723418155-3qed9046aki.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CSF",
    "fundId": 29,
    "companyName": "Misr Shariah Equity Fund – CIAM Islamic Fund (EGX33)",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Index Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777723206634-mot47dnay6c.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "DMF",
    "fundId": 36,
    "companyName": "Diamond Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777721657459-1s2iyi7b20u.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "FMF",
    "fundId": 83,
    "companyName": "El Fanar Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777503605694-n94czj0h8q.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AIM",
    "fundId": 150,
    "companyName": "Iskan Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1782999009530-0pat17v7f2p.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "JMF",
    "fundId": 37,
    "companyName": "Juman Money Market Fund - AAIB",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778113285348-882m81eqqlt.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MTF",
    "fundId": 4,
    "companyName": "Misr Takaful Money Market Fund - Sharia Compliant",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "AAIB Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777849150406-hrq7ackd8o5.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "ATF",
    "fundId": 17,
    "companyName": "Al-Ahly Tamayoz Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1782131759390-6ef1eo35t.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "HMF",
    "fundId": 89,
    "companyName": "Horas Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777846734446-1q8tp2r0x8w.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AFF",
    "fundId": 18,
    "companyName": "NBE Fourth Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777587759379-vc9l7ullax.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "WMM",
    "fundId": 133,
    "companyName": "Wethaq Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Al Ahly Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780676303861-1dg9rauuxtu.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "OFO",
    "fundId": 125,
    "companyName": "Odin 4 Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Alpha Financial Investments",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780395683623-563tbttvts.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "RMM",
    "fundId": 115,
    "companyName": "Rawajj Money Market Fund - Aspire Capital",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Aspire Capital Holding",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780227155651-mcbimdbq3kd.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MCF",
    "fundId": 145,
    "companyName": "Menthum Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Azimut Egypt Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1782314526334-dei5eolhs8e.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "THC",
    "fundId": 120,
    "companyName": "Thndr Savings Clouds ( az-thndr )",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Azimut Egypt Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780316342870-oydk8z57zr9.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "CYO",
    "fundId": 180,
    "companyName": "Banque du Caire Second Fund - Cairo Daily",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1785413155099-jak7sdtpl5.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AAF",
    "fundId": 32,
    "companyName": "El Naharda ADIB Egypt shariah compliant money market fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777721445047-c715owyqqma.jpg",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "MMM",
    "fundId": 186,
    "companyName": "Mazaya Money Market Fund - Bank ABC",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1785426721107-r6lvyvt8qy.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MBM",
    "fundId": 258,
    "companyName": "MID BANK Second Mutual fund (Money Market)",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1789823745383-xbwrkebtjzm.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "YAB",
    "fundId": 154,
    "companyName": "Yomaty Money Market Fund - Arab Bank",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Beltone Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1783428625095-olfjf52u0g.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "AMM",
    "fundId": 119,
    "companyName": "Arope Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "CFH Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780314026310-hmzfykoxsop.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "ANZ",
    "fundId": 185,
    "companyName": "Allianz Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1785424527312-2ljo9ul54jw.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "YYU",
    "fundId": 141,
    "companyName": "Banque Misr Day by Day Fund ( USD )",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1781181267854-97qkc1y4a1n.png",
    "currency": "USD",
    "isIslamic": false
  },
  {
    "symbol": "MYY",
    "fundId": 58,
    "companyName": "Banque Misr Day by Day Fund Daily Cumulative Return",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777554434923-b2zikknwfpe.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MEM",
    "fundId": 149,
    "companyName": "Banque Misr Mutual Fund in Euro ( day by day Euro )",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1782993315460-fv0bwgvmu1.png",
    "currency": "EUR",
    "isIslamic": false
  },
  {
    "symbol": "FWY",
    "fundId": 160,
    "companyName": "Fawry Money Market Fund ( Fawry Youmy )",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1784379492954-kig3qkqdnr.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CMY",
    "fundId": 140,
    "companyName": "Misr Daily Fund - CIAM",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1781175613673-bihud5yzuv.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "OSOUL",
    "fundId": 16,
    "companyName": "Osoul Fund - Commercial International Bank Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777586064877-t780xncyncb.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "RUB",
    "fundId": 153,
    "companyName": "Rakhaa Money Market Fund - The United Bank",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1783422743437-kxhcg61p9v.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "SCM",
    "fundId": 159,
    "companyName": "Suez Canal Bank Money Market Fund - Al Suez Al youmi",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "CI Capital Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1784041236262-ic1wwmgll1.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "BBM",
    "fundId": 97,
    "companyName": "Al Barakat Fund - Al Baraka Bank Egypt",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778676003275-ya07j89xw6q.jpeg",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "NBM",
    "fundId": 158,
    "companyName": "Bank NXT Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1784031125368-p5bg3k67p8.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "CAT",
    "fundId": 183,
    "companyName": "Credit Agricole Egypt Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1785419617667-lnzuki8z5cg.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "HMM",
    "fundId": 178,
    "companyName": "EFG Hermes Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1785408551912-jc80m6k04s.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MIF",
    "fundId": 210,
    "companyName": "Manasek Islamic Fund - Al Baraka Capital",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1786377452366-fpapoy893l.png",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "MMF",
    "fundId": 88,
    "companyName": "Mazid Money Market Fund - Emirates NBD",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777843750166-xkf5monljbg.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MFA",
    "fundId": 152,
    "companyName": "Modkharaty Money Market Fund - FAB MISR",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1783009553722-4gs62jbbb8c.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "TKF",
    "fundId": 144,
    "companyName": "Tharwa Money Market Fund - Kuwait Finance House Bank",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1781706923702-2tmh1zju7dy.jpeg",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "QTH",
    "fundId": 90,
    "companyName": "Themar Money Market Fund - QNB Al Ahli",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "EFG Hermes Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777982495878-2dhalvhystm.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "HYF",
    "fundId": 65,
    "companyName": "Al Hasad Daily Fund - Agricultural Bank of Egypt",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "HC Securities & Investment",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778112801839-u2exkq03sg.jpg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "EMM",
    "fundId": 162,
    "companyName": "Ishraq Money Market Fund - NBK",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "NBK Capital Egypt",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1784463659759-q7xloalwatf.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "MG2",
    "fundId": 98,
    "companyName": "Makaseb Money Market Fund - GIG Egypt Takaful Shariah",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "NI Capital",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778699457765-2f3if8eb9h.webp",
    "currency": "EGP",
    "isIslamic": true
  },
  {
    "symbol": "SMM",
    "fundId": 96,
    "companyName": "Siula Money Market Fund - NI Capital",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "NI Capital",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1778598943924-3mo9n77eq7g.jpeg",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "PMF",
    "fundId": 106,
    "companyName": "Mawared Money Market Fund – HD BANK",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "PFI Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780757433639-4jb4ng7vhva.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "PCM",
    "fundId": 107,
    "companyName": "PFI Cashi Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "PFI Asset Management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780099015634-pzscowmu6w9.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "THF",
    "fundId": 137,
    "companyName": "Tharaa Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Prime Investments asset management",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1780761845420-r992d3f4xg.png",
    "currency": "EGP",
    "isIslamic": false
  },
  {
    "symbol": "ZST",
    "fundId": 86,
    "companyName": "Zaldi Star Money Market Fund",
    "sector": "Funds",
    "industryGroup": "Investment Funds",
    "industry": "Money Market Funds",
    "subIndustry": "Zaldi Capital",
    "logoUrl": "https://kshqrzzohabbsjipkunh.supabase.co/storage/v1/object/public/funds/1777802765157-qo0vcm96aeh.png",
    "currency": "EGP",
    "isIslamic": false
  }
];
