import { createDiagnostic, type IndicatorOutputDefinition, type IndicatorOutputs, type TimeSeriesFrame, type TimeSeriesIndicatorDefinition } from '../../contracts';
import { ema, percentileRank, rollingStdDev, sma } from '../../core/series';
import { defineCategoryIndicator, type CategoryIndicatorSpec, type CategoryParameterRule } from '../shared/category-definition';
import * as indicatorLogic from './logic';
import { Params, Rules, category, close, event, integer, mean, median, number, overlay, pane, permutationEntropy, regression, returns, sampleEntropy, shannonEntropy, variance } from './shared';

interface Input { backlogId: string; id: string; name: string; ar: string; description: string; defaults?: Params; rules?: Rules; outputs: readonly IndicatorOutputDefinition[]; minimumHistory: number; compute: CategoryIndicatorSpec<Params>['compute']; unavailableCapability?: string; requiredRole?: string; }
function define(input: Input): TimeSeriesIndicatorDefinition<Params> { return defineCategoryIndicator({ backlogId: input.backlogId, id: input.id, category: 'quantitative', name: input.name, description: { en: input.description, ar: input.ar }, requiredFields: ['close'], requiredCapabilities: input.requiredRole ? ['numeric-series'] : [], defaults: input.defaults ?? {}, parameterRules: input.rules ?? {}, outputs: input.outputs, minimumHistory: input.minimumHistory, tags: ['quantitative', 'statistics'], references: ['Ticknal canonical quantitative specification'], availability: (_frame,_parameters,inputs) => input.requiredRole !== undefined && inputs.seriesByRole[input.requiredRole] === undefined ? createDiagnostic('DATA_CAPABILITY_MISSING', 'indicator.data.requiredRoleMissing', { role: input.requiredRole }) : input.unavailableCapability ? createDiagnostic('DATA_FIELD_MISSING', 'indicator.data.capabilityUnavailable', { capability: input.unavailableCapability }) : null, compute: input.compute }); }
const corrOutputs = [pane('correlation', 'Correlation')], covOutputs = [pane('covariance', 'Covariance')], betaOutputs = [pane('beta', 'Beta'), pane('alpha', 'Alpha', 'percent')], alphaOutputs = [pane('alpha_pct', 'Alpha', 'percent')];

export const QUANTITATIVE_DEFINITIONS: readonly TimeSeriesIndicatorDefinition<object>[] = Object.freeze([
  define({ backlogId: 'QNT-001', id: 'z-score', name: 'Z-score', ar: 'الدرجة المعيارية', description: 'Distance from rolling mean in standard-deviation units.', defaults: { period: 20 }, rules: { period: integer(2) }, outputs: [pane('z_score', 'Z-score')], minimumHistory: 20, compute: indicatorLogic.zScore }),
  define({ backlogId: 'QNT-002', id: 'rolling-mean-variance', name: 'Rolling mean and variance', ar: 'المتوسط والتباين المتحركان', description: 'Rolling arithmetic mean and population variance.', defaults: { period: 20 }, rules: { period: integer(2) }, outputs: [pane('mean', 'Mean', 'price'), pane('variance', 'Variance')], minimumHistory: 20, compute: indicatorLogic.rollingMeanVariance }),
  define({ backlogId: 'QNT-003', id: 'rolling-median-mad', name: 'Rolling median and MAD', ar: 'الوسيط والانحراف المطلق الوسيط', description: 'Robust rolling center, dispersion, and robust Z-score.', defaults: { period: 20 }, rules: { period: integer(2) }, outputs: [pane('median', 'Median', 'price'), pane('mad', 'MAD', 'price'), pane('robust_z', 'Robust Z-score')], minimumHistory: 20, compute: indicatorLogic.rollingMedianMad }),
  define({ backlogId: 'QNT-004', id: 'quantile-percentile-rank', name: 'Percentile rank', ar: 'الرتبة المئوية', description: 'Position of closing price within its rolling history.', defaults: { period: 100 }, rules: { period: integer() }, outputs: [pane('percentile_0_100', 'Percentile', 'rank')], minimumHistory: 100, compute: indicatorLogic.quantilePercentileRank }),
  define({ backlogId: 'QNT-005', id: 'rolling-skewness', name: 'Rolling skewness', ar: 'الالتواء المتحرك', description: 'Third standardized moment of returns.', defaults: { period: 60 }, rules: { period: integer(3) }, outputs: [pane('skewness', 'Skewness')], minimumHistory: 61, compute: indicatorLogic.rollingSkewness }),
  define({ backlogId: 'QNT-006', id: 'rolling-kurtosis', name: 'Rolling kurtosis', ar: 'التفلطح المتحرك', description: 'Fourth standardized moment and excess kurtosis of returns.', defaults: { period: 60 }, rules: { period: integer(4) }, outputs: [pane('kurtosis', 'Kurtosis'), pane('excess_kurtosis', 'Excess kurtosis')], minimumHistory: 61, compute: indicatorLogic.rollingKurtosis }),
  define({ backlogId: 'QNT-007', id: 'rolling-correlation', name: 'Rolling correlation', ar: 'الارتباط المتحرك', description: 'Rolling correlation with an authenticated comparison series.', defaults: { period: 20, comparisonSymbol: 'COMPARISON' }, rules: { period: integer(2), comparisonSymbol: { kind: 'string', minLength: 1 } }, outputs: corrOutputs, minimumHistory: 21, requiredRole: 'comparison', compute: indicatorLogic.rollingCorrelation }),
  define({ backlogId: 'QNT-008', id: 'rolling-covariance', name: 'Rolling covariance', ar: 'التغاير المتحرك', description: 'Rolling covariance with an authenticated comparison series.', defaults: { period: 20, comparisonSymbol: 'COMPARISON' }, rules: { period: integer(2), comparisonSymbol: { kind: 'string', minLength: 1 } }, outputs: covOutputs, minimumHistory: 21, requiredRole: 'comparison', compute: indicatorLogic.rollingCovariance }),
  define({ backlogId: 'QNT-009', id: 'rolling-beta', name: 'Rolling beta', ar: 'بيتا المتحركة', description: 'Asset sensitivity and intercept against an authenticated benchmark.', defaults: { period: 60, annualization: 252, benchmarkSymbol: 'EGX30' }, rules: { period: integer(2), annualization: integer(), benchmarkSymbol: { kind: 'string', minLength: 1 } }, outputs: betaOutputs, minimumHistory: 61, requiredRole: 'benchmark', compute: indicatorLogic.rollingBeta }),
  define({ backlogId: 'QNT-010', id: 'rolling-alpha', name: 'Rolling alpha', ar: 'ألفا المتحركة', description: 'Return unexplained by an authenticated benchmark beta.', defaults: { period: 60, annualization: 252, benchmarkSymbol: 'EGX30' }, rules: { period: integer(2), annualization: integer(), benchmarkSymbol: { kind: 'string', minLength: 1 } }, outputs: alphaOutputs, minimumHistory: 61, requiredRole: 'benchmark', compute: indicatorLogic.rollingAlpha }),
  define({ backlogId: 'QNT-011', id: 'linear-regression-slope', name: 'Linear regression slope', ar: 'ميل الانحدار الخطي', description: 'Rolling least-squares slope and intercept.', defaults: { period: 20 }, rules: { period: integer(2) }, outputs: [pane('slope', 'Slope', 'price'), pane('intercept', 'Intercept', 'price')], minimumHistory: 20, compute: indicatorLogic.linearRegressionSlope }),
  define({ backlogId: 'QNT-012', id: 'regression-r-squared', name: 'Regression R-squared', ar: 'معامل تحديد الانحدار', description: 'Share of rolling price variance explained by a linear trend.', defaults: { period: 20 }, rules: { period: integer(2) }, outputs: [pane('r_squared', 'R squared')], minimumHistory: 20, compute: indicatorLogic.regressionRSquared }),
  define({ backlogId: 'QNT-013', id: 'regression-residual-z-score', name: 'Regression residual Z-score', ar: 'الدرجة المعيارية لبواقي الانحدار', description: 'Current regression residual normalized by rolling residual dispersion.', defaults: { period: 20 }, rules: { period: integer(3) }, outputs: [pane('residual', 'Residual', 'price'), pane('z_score', 'Residual Z-score')], minimumHistory: 39, compute: indicatorLogic.regressionResidualZScore }),
  define({ backlogId: 'QNT-014', id: 'kalman-adaptive-velocity', name: 'Kalman Adaptive Velocity', ar: 'سرعة كالمان المتكيفة', description: 'Two-state recursive fair-value and velocity estimate with innovation bands.', defaults: { processNoise: 0.01, measurementNoise: 1, bandMultiple: 2 }, rules: { processNoise: number(0.000001, 100), measurementNoise: number(0.000001, 1000), bandMultiple: number(0.1, 10) }, outputs: [overlay('mean', 'Kalman mean'), pane('velocity', 'Velocity', 'price'), overlay('upper', 'Upper'), overlay('lower', 'Lower'), pane('shock_z', 'Innovation shock')], minimumHistory: 2, compute: indicatorLogic.kalmanAdaptiveVelocity }),
  define({ backlogId: 'QNT-015', id: 'kalman-trend-state', name: 'Kalman trend state', ar: 'حالة اتجاه كالمان', description: 'Velocity-derived trend direction and confidence.', defaults: { smoothing: 10 }, rules: { smoothing: integer() }, outputs: [category('direction', 'Direction'), pane('confidence', 'Confidence', 'probability'), pane('velocity', 'Velocity', 'price')], minimumHistory: 11, compute: indicatorLogic.kalmanTrendState }),
  define({ backlogId: 'QNT-016', id: 'hurst-exponent', name: 'Hurst Exponent', ar: 'أس هيرست', description: 'Rolling rescaled-range estimate of long memory.', defaults: { period: 100 }, rules: { period: integer(20) }, outputs: [pane('hurst', 'Hurst exponent'), category('state', 'State')], minimumHistory: 100, compute: indicatorLogic.hurstExponent }),
  define({ backlogId: 'QNT-017', id: 'variance-ratio', name: 'Variance Ratio', ar: 'نسبة التباين', description: 'Variance of multi-bar returns relative to one-bar returns.', defaults: { period: 100, horizon: 5 }, rules: { period: integer(10), horizon: integer(2, 100) }, outputs: [pane('variance_ratio', 'Variance ratio')], minimumHistory: 105, compute: indicatorLogic.varianceRatio }),
  define({ backlogId: 'QNT-018', id: 'augmented-dickey-fuller-state', name: 'Augmented Dickey-Fuller state', ar: 'حالة ديكي فولر المعززة', description: 'Rolling lag-level regression stationarity approximation.', defaults: { period: 100 }, rules: { period: integer(20) }, outputs: [pane('test_statistic', 'ADF statistic'), pane('p_value', 'Approximate p-value', 'probability'), event('stationary', 'Stationary')], minimumHistory: 101, compute: indicatorLogic.augmentedDickeyFullerState }),
  define({ backlogId: 'QNT-019', id: 'half-life-mean-reversion', name: 'Half-life of mean reversion', ar: 'نصف عمر العودة للمتوسط', description: 'Half-life implied by rolling AR(1) decay coefficient.', defaults: { period: 100 }, rules: { period: integer(20) }, outputs: [pane('half_life', 'Half-life', 'count'), pane('ar_coefficient', 'AR coefficient')], minimumHistory: 101, compute: indicatorLogic.halfLifeMeanReversion }),
  define({ backlogId: 'QNT-020', id: 'permutation-entropy', name: 'Permutation Entropy', ar: 'إنتروبيا التبديل', description: 'Normalized ordinal-pattern entropy of returns.', defaults: { period: 50, dimension: 3 }, rules: { period: integer(10), dimension: integer(2, 6) }, outputs: [pane('entropy', 'Permutation entropy'), category('regime', 'Regime'), overlay('adaptive_upper', 'Adaptive upper'), overlay('adaptive_lower', 'Adaptive lower')], minimumHistory: 51, compute: indicatorLogic.permutationEntropy }),
  define({ backlogId: 'QNT-021', id: 'shannon-entropy', name: 'Shannon Entropy', ar: 'إنتروبيا شانون', description: 'Normalized information entropy of discretized returns.', defaults: { period: 50, bins: 10 }, rules: { period: integer(10), bins: integer(2, 100) }, outputs: [pane('entropy', 'Entropy'), pane('normalized_entropy', 'Normalized entropy')], minimumHistory: 51, compute: indicatorLogic.shannonEntropy }),
  define({ backlogId: 'QNT-022', id: 'sample-entropy', name: 'Sample Entropy', ar: 'إنتروبيا العينة', description: 'Template-match complexity excluding self-matches.', defaults: { period: 50, dimension: 2, tolerance: 0.2 }, rules: { period: integer(10), dimension: integer(1, 5), tolerance: number(0.01, 2) }, outputs: [pane('sample_entropy', 'Sample entropy')], minimumHistory: 51, compute: indicatorLogic.sampleEntropy }),
  define({ backlogId: 'QNT-023', id: 'approximate-entropy', name: 'Approximate Entropy', ar: 'الإنتروبيا التقريبية', description: 'Template-match regularity including self-matches.', defaults: { period: 50, dimension: 2, tolerance: 0.2 }, rules: { period: integer(10), dimension: integer(1, 5), tolerance: number(0.01, 2) }, outputs: [pane('approximate_entropy', 'Approximate entropy')], minimumHistory: 51, compute: indicatorLogic.approximateEntropy }),
  define({ backlogId: 'QNT-024', id: 'fractal-dimension-index', name: 'Fractal Dimension Index', ar: 'مؤشر البعد الكسري', description: 'Katz fractal dimension of rolling price paths.', defaults: { period: 30 }, rules: { period: integer(3) }, outputs: [pane('dimension_1_2', 'Fractal dimension')], minimumHistory: 30, compute: indicatorLogic.fractalDimensionIndex }),
  define({ backlogId: 'QNT-025', id: 'detrended-fluctuation-analysis', name: 'Detrended Fluctuation Analysis', ar: 'تحليل التذبذب منزوع الاتجاه', description: 'Rolling two-scale detrended fluctuation exponent.', defaults: { period: 100 }, rules: { period: integer(32) }, outputs: [pane('scaling_exponent', 'Scaling exponent')], minimumHistory: 101, compute: indicatorLogic.detrendedFluctuationAnalysis }),
  define({ backlogId: 'QNT-026', id: 'rescaled-range-analysis', name: 'Rescaled Range Analysis', ar: 'تحليل النطاق المعاد قياسه', description: 'Rolling rescaled range and implied Hurst estimate.', defaults: { period: 100 }, rules: { period: integer(20) }, outputs: [pane('r_over_s', 'R/S'), pane('hurst_estimate', 'Hurst estimate')], minimumHistory: 101, compute: indicatorLogic.rescaledRangeAnalysis }),
  define({ backlogId: 'QNT-027', id: 'change-point-detector', name: 'Change-point detector', ar: 'كاشف نقاط التغير', description: 'Difference between adjacent rolling half-window means in pooled-volatility units.', defaults: { period: 40, threshold: 2 }, rules: { period: integer(10), threshold: number(0.1, 20) }, outputs: [event('change_event', 'Change event'), pane('score', 'Change score'), category('state', 'State')], minimumHistory: 40, compute: indicatorLogic.changePointDetector }),
  define({ backlogId: 'QNT-028', id: 'cusum-filter', name: 'CUSUM Filter', ar: 'مرشح المجموع التراكمي', description: 'Positive and negative cumulative standardized-return deviations.', defaults: { period: 20, threshold: 5 }, rules: { period: integer(2), threshold: number(0.1, 100) }, outputs: [pane('positive_cusum', 'Positive CUSUM'), pane('negative_cusum', 'Negative CUSUM'), event('event', 'CUSUM event')], minimumHistory: 21, compute: indicatorLogic.cusumFilter }),
  define({ backlogId: 'QNT-029', id: 'bayesian-online-change-point', name: 'Bayesian Online Change Point', ar: 'نقطة التغير البايزية الآنية', description: 'Hazard-weighted probability of a standardized return regime break.', defaults: { period: 20, hazardPct: 2 }, rules: { period: integer(5), hazardPct: number(0.01, 100) }, outputs: [pane('change_probability', 'Change probability', 'probability'), pane('run_length', 'Run length', 'count')], minimumHistory: 21, compute: indicatorLogic.bayesianOnlineChangePoint }),
  define({ backlogId: 'QNT-030', id: 'hidden-markov-regime', name: 'Hidden Markov regime', ar: 'نظام ماركوف المخفي', description: 'Four-state Gaussian-emission forward filter over return and volatility.', defaults: { period: 20 }, rules: { period: integer(5) }, outputs: [pane('bull_probability', 'Bull probability', 'probability'), pane('bear_probability', 'Bear probability', 'probability'), pane('calm_probability', 'Calm probability', 'probability'), pane('volatile_probability', 'Volatile probability', 'probability'), category('active_state', 'Active state')], minimumHistory: 21, compute: indicatorLogic.hiddenMarkovRegime }),
  define({ backlogId: 'QNT-031', id: 'gaussian-mixture-regime', name: 'Gaussian Mixture regime', ar: 'نظام المزيج الغاوسي', description: 'Soft assignment to calm, directional, and volatile return clusters.', defaults: { period: 20 }, rules: { period: integer(5), }, outputs: [category('cluster', 'Cluster'), pane('calm_probability', 'Calm probability', 'probability'), pane('trend_probability', 'Trend probability', 'probability'), pane('volatile_probability', 'Volatile probability', 'probability')], minimumHistory: 21, compute: indicatorLogic.gaussianMixtureRegime }),
  define({ backlogId: 'QNT-032', id: 'mahalanobis-anomaly-score', name: 'Mahalanobis anomaly score', ar: 'درجة شذوذ ماهالانوبيس', description: 'Bivariate rolling distance using return and range observations.', defaults: { period: 60 }, rules: { period: integer(10) }, outputs: [pane('anomaly_score', 'Anomaly score'), pane('percentile', 'Anomaly percentile', 'rank')], minimumHistory: 61, compute: indicatorLogic.mahalanobisAnomalyScore }),
  define({ backlogId: 'QNT-033', id: 'rolling-sharpe-signal', name: 'Rolling Sharpe signal', ar: 'إشارة شارب المتحركة', description: 'Annualized excess return per unit of rolling volatility.', defaults: { period: 60, annualization: 252, riskFreeAnnualPct: 0 }, rules: { period: integer(2), annualization: integer(), riskFreeAnnualPct: number(-100, 100) }, outputs: [pane('rolling_sharpe', 'Rolling Sharpe')], minimumHistory: 61, compute: indicatorLogic.rollingSharpeSignal }),
  define({ backlogId: 'QNT-034', id: 'rolling-sortino-signal', name: 'Rolling Sortino signal', ar: 'إشارة سورتينو المتحركة', description: 'Annualized excess return per unit of downside deviation.', defaults: { period: 60, annualization: 252, targetAnnualPct: 0 }, rules: { period: integer(2), annualization: integer(), targetAnnualPct: number(-100, 100) }, outputs: [pane('rolling_sortino', 'Rolling Sortino')], minimumHistory: 61, compute: indicatorLogic.rollingSortinoSignal }),
  define({ backlogId: 'QNT-035', id: 'trend-quality-score', name: 'Trend quality score', ar: 'درجة جودة الاتجاه', description: 'Composite of regression slope, fit, persistence, and volatility.', defaults: { period: 40 }, rules: { period: integer(10) }, outputs: [pane('score_0_100', 'Trend quality', 'percent'), category('state', 'State')], minimumHistory: 41, compute: indicatorLogic.trendQualityScore }),
  define({ backlogId: 'QNT-036', id: 'mean-reversion-score', name: 'Mean-reversion score', ar: 'درجة العودة للمتوسط', description: 'Composite of Z-score magnitude, entropy, and AR decay.', defaults: { period: 60 }, rules: { period: integer(20) }, outputs: [pane('score_0_100', 'Mean-reversion score', 'percent'), category('direction', 'Direction')], minimumHistory: 61, compute: indicatorLogic.meanReversionScore }),
  define({ backlogId: 'QNT-037', id: 'hydra-binary-index', name: 'HYDRA Binary Index', ar: 'مؤشر هايدرا الثنائي', description: 'Independent canonical adaptive trend-regime curve; it does not import protected strategy code.', defaults: { fast: 10, slow: 30, signal: 9 }, rules: { fast: integer(), slow: integer(), signal: integer() }, outputs: [pane('continuous_value', 'Continuous value'), event('binary_state', 'Bullish state'), event('cross_up', 'Bullish marker'), event('cross_down', 'Bearish marker')], minimumHistory: 39, compute: indicatorLogic.hydraBinaryIndex }),
  define({ backlogId: 'QNT-038', id: 'ensemble-regime-consensus', name: 'Ensemble regime consensus', ar: 'إجماع أنظمة السوق', description: 'Agreement across trend, volatility, entropy, and change-point votes.', defaults: { period: 40 }, rules: { period: integer(10) }, outputs: [category('regime', 'Regime'), pane('confidence', 'Confidence', 'probability'), pane('component_votes', 'Component votes', 'count')], minimumHistory: 41, compute: indicatorLogic.ensembleRegimeConsensus }),
]);

const GATED = new Set<string>();
export const QUANTITATIVE_OPERATIONAL_DEFINITIONS = Object.freeze(QUANTITATIVE_DEFINITIONS.filter((definition) => !GATED.has(definition.backlogId)));
